
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class APA106:
    def fill() -> None: ...
    def write() -> None: ...
class NeoPixel:
    def fill() -> None: ...
    def write() -> None: ...
