from typing import Any

Node = Any

class Partition:
    def find() -> None: ...
    def get_next_update() -> None: ...
    def info() -> None: ...
    def ioctl() -> None: ...
    def mark_app_valid_cancel_rollback() -> None: ...
    def readblocks() -> None: ...
    def set_boot() -> None: ...
    def writeblocks() -> None: ...
