from typing import Any

class Event:
    def __init__(self, *args) -> None: ...
    def clear(self, *args) -> Any: ...
    def set(self, *args) -> Any: ...
    wait: Any
    def is_set(self, *args) -> Any: ...

class ThreadSafeFlag:
    def __init__(self, *args) -> None: ...
    def set(self, *args) -> Any: ...
    def ioctl(self, *args) -> Any: ...
    wait: Any
