"""
Module: 'base64' on micropython-v1.29.0-webassembly-pyscript
"""

# MCU: {'family': 'micropython', 'version': '1.29.0', 'build': '', 'ver': '1.29.0', 'port': 'webassembly', 'board': 'pyscript', 'board_id': 'pyscript', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.28.6
from __future__ import annotations

from typing import Any, AsyncGenerator, Final, Generator

from _typeshed import Incomplete

MAXBINSIZE: Final[int] = 57
_b32tab: list = []
_b32rev: dict = {}
MAXLINESIZE: Final[int] = 76
_b32alphabet: dict = {}
bytes_types: tuple = ()

def decodestring(x0) -> Incomplete: ...
def b64decode(x0, x1, x2) -> Incomplete: ...
def b64encode(x0, x1) -> Incomplete: ...
def decodebytes(x0) -> Incomplete: ...
def b32encode(x0) -> Incomplete: ...
def test() -> Incomplete: ...
def encodebytes(x0) -> Incomplete: ...
def urlsafe_b64decode(x0) -> Incomplete: ...
def encodestring(x0) -> Incomplete: ...
def standard_b64encode(x0) -> Incomplete: ...
def standard_b64decode(x0) -> Incomplete: ...
def urlsafe_b64encode(x0) -> Incomplete: ...
def _bytes_from_decode_data(x0) -> Incomplete: ...
def encode(x0, x1) -> Incomplete: ...
def decode(x0, x1) -> Incomplete: ...
def main() -> Incomplete: ...
def b32decode(x0, x1, x2) -> Incomplete: ...
def b16decode(x0, x1) -> Incomplete: ...
def _maketrans(x0, x1) -> Incomplete: ...
def b16encode(x0) -> Incomplete: ...
def _translate(x0, x1) -> Incomplete: ...
