"""
Module: 'inspect' on micropython-v1.29.0-webassembly-pyscript
"""

# MCU: {'family': 'micropython', 'version': '1.29.0', 'build': '', 'ver': '1.29.0', 'port': 'webassembly', 'board': 'pyscript', 'board_id': 'pyscript', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.28.6
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

def isclass(x0) -> Incomplete: ...
def signature(x0) -> Incomplete: ...
def iscoroutine(x0) -> Incomplete: ...
def getmro(x0) -> Incomplete: ...
def getsourcefile(x0) -> Incomplete: ...
def getsource(x0) -> Incomplete: ...
def ismethod(x0) -> Incomplete: ...
def iscoroutinefunction(x0) -> Incomplete: ...
def ismodule(x0) -> Incomplete: ...
def isfunction(x0) -> Incomplete: ...
def isgeneratorfunction(x0) -> Incomplete: ...
def isgenerator(x0) -> Incomplete: ...
def getargspec(x0) -> Incomplete: ...
def getmodule(x0, x1) -> Incomplete: ...
def currentframe() -> Incomplete: ...
def getmembers(x0, x1) -> Incomplete: ...
def getfile(x0) -> Incomplete: ...
def getframeinfo(x0, x1) -> Incomplete: ...

class Signature:
    def __init__(self, *argv, **kwargs) -> None: ...

async def _g() -> Incomplete: ...

class _ct:
    def __init__(self, *argv, **kwargs) -> None: ...

class _Class:
    def meth(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

_Instance: Incomplete  ## <class '_Class'> = <_Class object at ...>
