"""
Module: 'urandom' on micropython-v1.26.0-esp32-ESP32_GENERIC-SPIRAM
"""

# MCU: {'variant': 'SPIRAM', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'board_id': 'ESP32_GENERIC-SPIRAM', 'mpy': 'v6.3', 'ver': '1.26.0', 'family': 'micropython', 'cpu': 'ESP32', 'version': '1.26.0'}
# Stubber: v1.25.1
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

def randrange(*args, **kwargs) -> Incomplete: ...
def random(*args, **kwargs) -> Incomplete: ...
def seed(*args, **kwargs) -> Incomplete: ...
def uniform(*args, **kwargs) -> Incomplete: ...
def choice(*args, **kwargs) -> Incomplete: ...
def randint(*args, **kwargs) -> Incomplete: ...
def getrandbits(*args, **kwargs) -> Incomplete: ...
