"""
Module: 'urandom' on micropython-v1.28.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.28.0'}
# Stubber: v1.28.0
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

def randrange(*args, **kwargs) -> Incomplete: ...
def random() -> Incomplete: ...
def seed(*args, **kwargs) -> Incomplete: ...
def uniform(x0, x1) -> Incomplete: ...
def choice(x0) -> Incomplete: ...
def randint(x0, x1) -> Incomplete: ...
def getrandbits(x0) -> Incomplete: ...
