"""
Module: 'urequests' on micropython-v1.28.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.28.0'}
# Stubber: v1.28.0
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

def delete(x0) -> Incomplete: ...
def head(x0) -> Incomplete: ...
def patch(x0) -> Incomplete: ...
def post(x0) -> Incomplete: ...
def request(x0, x1, x2, x3, x4) -> Incomplete: ...
def put(x0) -> Incomplete: ...
def get(x0) -> Incomplete: ...

class Response:
    def json(self) -> Incomplete: ...
    def close(self) -> Incomplete: ...

    content: Incomplete  ## <class 'property'> = <property>
    text: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...
