from typing import Any

Node = Any

class OneWire:
    def _search_rom() -> None: ...
    def crc8() -> None: ...
    def readbit() -> None: ...
    def readbyte() -> None: ...
    def readinto() -> None: ...
    def reset() -> None: ...
    def scan() -> None: ...
    def select_rom() -> None: ...
    def write() -> None: ...
    def writebit() -> None: ...
    def writebyte() -> None: ...

class OneWireError: ...
