from _typeshed import Incomplete

class CBORDecodeError(Exception): ...

break_marker: Incomplete

class CBORSimpleValue:
    value: Incomplete
    def __init__(self, value) -> None: ...
    def __eq__(self, other): ...
    def __repr__(self): ...

def decode_uint(decoder, subtype, allow_indefinite: bool = ...): ...
def decode_negint(decoder, subtype): ...
def decode_bytestring(decoder, subtype): ...
def decode_string(decoder, subtype): ...
def decode_array(decoder, subtype): ...
def decode_map(decoder, subtype): ...
def decode_special(decoder, subtype): ...
def decode_simple_value(decoder): ...
def decode_float16(decoder): ...
def decode_float32(decoder): ...
def decode_float64(decoder): ...

major_decoders: Incomplete
special_decoders: Incomplete

class CBORDecoder:
    fp: Incomplete
    def __init__(self, fp) -> None: ...
    def read(self, amount): ...
    def decode(self): ...

def loads(payload, **kwargs): ...
def load(fp, **kwargs): ...
