"""
Module: 'asyncio.core' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

_exc_context: dict = {}

def _promote_to_task(x0) -> Incomplete: ...
def ticks() -> Incomplete: ...
def ticks_diff(x0, x1) -> Incomplete: ...
def ticks_add(x0, x1) -> Incomplete: ...
def new_event_loop() -> Incomplete: ...
def run_until_complete(x0) -> Incomplete: ...
def create_task(x0) -> Incomplete: ...
def get_event_loop(x0, x1) -> Incomplete: ...
def current_task() -> Incomplete: ...
def sleep(x0) -> Incomplete: ...
def run(x0) -> Incomplete: ...
def sleep_ms(x0, x1) -> Incomplete: ...

cur_task: Incomplete  ## <class 'NoneType'> = None

async def _stopper() -> Incomplete: ...

_task_queue: Incomplete  ## <class 'TaskQueue'> = <TaskQueue>

class CancelledError(Exception): ...

class Task:
    def __init__(self, *argv, **kwargs) -> None: ...

class TaskQueue:
    def push(self, *args, **kwargs) -> Incomplete: ...
    def peek(self, *args, **kwargs) -> Incomplete: ...
    def remove(self, *args, **kwargs) -> Incomplete: ...
    def pop(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Loop:
    def get_exception_handler(self) -> Incomplete: ...
    def default_exception_handler(self, x1) -> Incomplete: ...
    def set_exception_handler(self) -> Incomplete: ...
    def run_forever(self) -> Incomplete: ...
    def run_until_complete(self) -> Incomplete: ...
    def stop(self) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    def create_task(self) -> Incomplete: ...
    def call_exception_handler(self) -> Incomplete: ...

    _exc_handler: Incomplete  ## <class 'NoneType'> = None
    def __init__(self, *argv, **kwargs) -> None: ...

class SingletonGenerator:
    def __init__(self, *argv, **kwargs) -> None: ...

class IOQueue:
    def queue_read(self, x1) -> Incomplete: ...
    def wait_io_event(self, x1) -> Incomplete: ...
    def queue_write(self, x1) -> Incomplete: ...
    def remove(self, x1) -> Incomplete: ...
    def _enqueue(self, x1, x2) -> Incomplete: ...
    def _dequeue(self, x1) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

_stop_task: Incomplete  ## <class 'NoneType'> = None
_io_queue: Incomplete  ## <class 'IOQueue'> = <IOQueue object at ...>

class TimeoutError(Exception): ...
