"""
Module: 'asyncio.event' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

class ThreadSafeFlag:
    def set(self) -> Incomplete: ...
    def ioctl(self, x1, x2) -> Incomplete: ...
    def clear(self) -> Incomplete: ...
    async def wait(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Event:
    def set(self) -> Incomplete: ...
    def is_set(self) -> Incomplete: ...
    def clear(self) -> Incomplete: ...
    async def wait(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
