from typing import Any, Tuple

e: float
pi: float

def acos(x) -> float: ...
def acosh(x) -> float: ...
def asin(x) -> float: ...
def asinh(x) -> float: ...
def atan(x) -> float: ...
def atan2(y, x) -> float: ...
def atanh(x) -> float: ...
def ceil(x) -> int: ...
def copysign(x, y) -> Any: ...
def cos(x) -> float: ...
def cosh(x) -> float: ...
def degrees(x) -> Any: ...
def erf(x) -> Any: ...
def erfc(x) -> Any: ...
def exp(x) -> float: ...
def expm1(x) -> Any: ...
def fabs(x) -> Any: ...
def floor(x) -> int: ...
def fmod(x, y) -> Any: ...
def frexp(x) -> Any: ...
def gamma(x) -> Any: ...
def isfinite(x) -> bool: ...
def isinf(x) -> bool: ...
def isnan(x) -> bool: ...
def ldexp(x, exp) -> Any: ...
def lgamma(x) -> float: ...
def log(x) -> float: ...
def log10(x) -> float: ...
def log2(x) -> float: ...
def modf(x) -> Tuple: ...
def pow(x, y) -> Any: ...
def radians(x) -> Any: ...
def sin(x) -> float: ...
def sinh(x) -> float: ...
def sqrt(x) -> Any: ...
def tan(x) -> float: ...
def tanh(x) -> float: ...
def trunc(x) -> int: ...
