from typing import Any

class Cellular:
    def _getResponse() -> None: ...
    def _waitResponse() -> None: ...
    def _writeAT() -> None: ...
    def connect() -> None: ...
    def connected() -> None: ...
    def deinit() -> None: ...
    def getAvailable() -> None: ...
    def getLocalIP() -> None: ...
    def getNetworkState() -> None: ...
    def getSimState() -> None: ...
    def gprsConnect() -> None: ...
    def gprsDisconnect() -> None: ...
    def init() -> None: ...
    def read() -> None: ...
    def restart() -> None: ...
    def send() -> None: ...
    def sendline() -> None: ...
    def testAT() -> None: ...

machine: Any
time: Any

def wait_ms() -> None: ...
