from typing import Any

class Lorawan:
    def _monitor() -> None: ...
    def _reset() -> None: ...
    def _setMode() -> None: ...
    def _uart_cb() -> None: ...
    def _waitTimeout() -> None: ...
    def _write() -> None: ...
    def deinit() -> None: ...
    def initP2PMode() -> None: ...
    def initRxMode() -> None: ...
    def txStr() -> None: ...

machine: Any
module: Any
timEx: Any
time: Any
