from _typeshed import Incomplete

def partial(func, *args, **kwargs): ...
def update_wrapper(wrapper, wrapped, assigned: Incomplete | None = ..., updated: Incomplete | None = ...): ...
def wraps(wrapped, assigned: Incomplete | None = ..., updated: Incomplete | None = ...): ...
def reduce(function, iterable, initializer: Incomplete | None = ...): ...
