"""
Module: 'usb.device.cdc' on micropython-v1.26.1-mimxrt-MIMXRT1010_EVK
"""

# MCU: {'variant': '', 'build': '', 'arch': 'armv7emsp', 'port': 'mimxrt', 'board': 'MIMXRT1010_EVK', 'board_id': 'MIMXRT1010_EVK', 'mpy': 'v6.3', 'ver': '1.26.1', 'family': 'micropython', 'cpu': 'MIMXRT1011DAE5A', 'version': '1.26.1'}
# Stubber: v1.26.3
from __future__ import annotations
from typing import Final
from _typeshed import Incomplete

_STOP_BITS_REPR: tuple = ()
_PARITY_BITS_REPR: Final[str] = "NOEMS"

def split_bmRequestType(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class Buffer:
    def finish_read(self, *args, **kwargs) -> Incomplete: ...
    def pend_write(self, *args, **kwargs) -> Incomplete: ...
    def finish_write(self, *args, **kwargs) -> Incomplete: ...
    def pend_read(self, *args, **kwargs) -> Incomplete: ...
    def readable(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def writable(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Interface:
    def on_interface_control_xfer(self, *args, **kwargs) -> Incomplete: ...
    def stall(self, *args, **kwargs) -> Incomplete: ...
    def on_device_control_xfer(self, *args, **kwargs) -> Incomplete: ...
    def xfer_pending(self, *args, **kwargs) -> Incomplete: ...
    def on_endpoint_control_xfer(self, *args, **kwargs) -> Incomplete: ...
    def is_open(self, *args, **kwargs) -> Incomplete: ...
    def num_itfs(self, *args, **kwargs) -> Incomplete: ...
    def submit_xfer(self, *args, **kwargs) -> Incomplete: ...
    def desc_cfg(self, *args, **kwargs) -> Incomplete: ...
    def on_reset(self, *args, **kwargs) -> Incomplete: ...
    def num_eps(self, *args, **kwargs) -> Incomplete: ...
    def on_open(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class CDCInterface:
    def xfer_pending(self, *args, **kwargs) -> Incomplete: ...
    def is_open(self, *args, **kwargs) -> Incomplete: ...
    def stall(self, *args, **kwargs) -> Incomplete: ...
    def _readinto(self, *args, **kwargs) -> Incomplete: ...
    def on_device_control_xfer(self, *args, **kwargs) -> Incomplete: ...
    def on_endpoint_control_xfer(self, *args, **kwargs) -> Incomplete: ...
    def on_interface_control_xfer(self, *args, **kwargs) -> Incomplete: ...
    def _wr_cb(self, *args, **kwargs) -> Incomplete: ...
    def _wr_xfer(self, *args, **kwargs) -> Incomplete: ...
    def _rd_cb(self, *args, **kwargs) -> Incomplete: ...
    def set_break_cb(self, *args, **kwargs) -> Incomplete: ...
    def set_line_state_cb(self, *args, **kwargs) -> Incomplete: ...
    def _rd_xfer(self, *args, **kwargs) -> Incomplete: ...
    def set_line_coding_cb(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def flush(self, *args, **kwargs) -> Incomplete: ...
    def ioctl(self, *args, **kwargs) -> Incomplete: ...
    def submit_xfer(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def num_eps(self, *args, **kwargs) -> Incomplete: ...
    def desc_cfg(self, *args, **kwargs) -> Incomplete: ...
    def num_itfs(self, *args, **kwargs) -> Incomplete: ...
    def on_reset(self, *args, **kwargs) -> Incomplete: ...
    def on_open(self, *args, **kwargs) -> Incomplete: ...

    baudrate: Incomplete  ## <class 'property'> = <property>
    rts: Incomplete  ## <class 'property'> = <property>
    parity: Incomplete  ## <class 'property'> = <property>
    dtr: Incomplete  ## <class 'property'> = <property>
    stop_bits: Incomplete  ## <class 'property'> = <property>
    data_bits: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...
