"""
Module: 'mip' on micropython-v1.25.0-preview-rp2-UNKNOWN_BOARD
"""

# MCU: {'family': 'micropython', 'version': '1.25.0-preview', 'build': 'preview.236.gbfb1bee6f', 'ver': '1.25.0-preview-preview.236.gbfb1bee6f', 'port': 'rp2', 'board': 'UNKNOWN_BOARD', 'cpu': 'RP2350', 'mpy': 'v6.3', 'arch': 'armv7emsp'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

_CHUNK_SIZE: int = 128

def _ensure_path_exists(*args, **kwargs) -> Incomplete: ...
def _download_file(*args, **kwargs) -> Incomplete: ...
def _install_json(*args, **kwargs) -> Incomplete: ...
def _install_package(*args, **kwargs) -> Incomplete: ...
def _rewrite_url(*args, **kwargs) -> Incomplete: ...
def _chunk(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...
def install(*args, **kwargs) -> Incomplete: ...
def _check_exists(*args, **kwargs) -> Incomplete: ...
