"""
Module: 'datetime' on micropython-v1.28.0-webassembly-pyscript
"""

# MCU: {'family': 'micropython', 'version': '1.28.0', 'build': '', 'ver': '1.28.0', 'port': 'webassembly', 'board': 'pyscript', 'board_id': 'pyscript', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.28.3
from __future__ import annotations

from typing import Any, AsyncGenerator, Final, Generator

from _typeshed import Incomplete

MAXYEAR: Final[int] = 9999
MINYEAR: Final[int] = 1

def _iso2t(x0) -> Incomplete: ...
def _iso2d(x0) -> Incomplete: ...
def _t2iso(x0, x1, x2, x3) -> Incomplete: ...
def _leap(x0) -> Incomplete: ...
def _o2ymd(x0) -> Incomplete: ...
def _d2iso(x0) -> Incomplete: ...
def _time(x0, x1, x2, x3, x4) -> Incomplete: ...
def _dim(x0, x1) -> Incomplete: ...
def _date(x0, x1, x2) -> Incomplete: ...
def _dbm(x0, x1) -> Incomplete: ...

class datetime:
    def isoweekday(self) -> Incomplete: ...
    def dst(self) -> Incomplete: ...
    def tzname(self) -> Incomplete: ...
    def date(self) -> Incomplete: ...
    def isoformat(self, x1, x2) -> Incomplete: ...
    def toordinal(self) -> Incomplete: ...
    def timestamp(self) -> Incomplete: ...
    def timetuple(self) -> Incomplete: ...
    def timetz(self) -> Incomplete: ...
    def weekday(self) -> Incomplete: ...
    def time(self) -> Incomplete: ...
    def tuple(self) -> Incomplete: ...
    def replace(self, x1, x2, x3, x4, x5) -> Incomplete: ...
    def utcoffset(self) -> Incomplete: ...
    def _cmp(self, x1) -> Incomplete: ...
    def astimezone(self, x1) -> Incomplete: ...
    def _sub(self, x1) -> Incomplete: ...
    def _mktime(self) -> Incomplete: ...

    year: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def now(cls, *args, **kwargs) -> Incomplete: ...

    second: Incomplete  ## <class 'property'> = <property>
    tzinfo: Incomplete  ## <class 'property'> = <property>
    day: Incomplete  ## <class 'property'> = <property>
    fold: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromisoformat(cls, *args, **kwargs) -> Incomplete: ...
    @classmethod
    def combine(cls, *args, **kwargs) -> Incomplete: ...

    EPOCH: Incomplete  ## <class 'datetime'> = datetime.datetime(1970, 1, 1, 0, 0, 0, 0, datetime.timezone(datetime.timedelta(microseconds=0), None), fold=0)
    month: Incomplete  ## <class 'property'> = <property>
    microsecond: Incomplete  ## <class 'property'> = <property>
    minute: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromordinal(cls, *args, **kwargs) -> Incomplete: ...

    hour: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromtimestamp(cls, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class timedelta:
    def _tuple(self, x1) -> Incomplete: ...
    def _fmt(self, x1) -> Incomplete: ...
    def isoformat(self) -> Incomplete: ...
    def total_seconds(self) -> Incomplete: ...
    def tuple(self) -> Incomplete: ...

    min: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=-86399999913600000000)
    resolution: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=1)
    seconds: Incomplete  ## <class 'property'> = <property>
    max: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=86399999999999999999)
    microseconds: Incomplete  ## <class 'property'> = <property>
    days: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...

class timezone:
    def isoformat(self, x1) -> Incomplete: ...
    def tzname(self, x1) -> Incomplete: ...
    def utcoffset(self, x1) -> Incomplete: ...
    def fromutc(self, x1) -> Incomplete: ...
    def dst(self, x1) -> Incomplete: ...

    utc: Incomplete  ## <class 'timezone'> = datetime.timezone(datetime.timedelta(microseconds=0), None)
    def __init__(self, *argv, **kwargs) -> None: ...

class tzinfo:
    def isoformat(self, x1) -> Incomplete: ...
    def tzname(self, x1) -> Incomplete: ...
    def utcoffset(self, x1) -> Incomplete: ...
    def fromutc(self, x1) -> Incomplete: ...
    def dst(self, x1) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class time:
    def _sub(self, x1) -> Incomplete: ...
    def dst(self) -> Incomplete: ...
    def isoformat(self, x1) -> Incomplete: ...
    def tzname(self) -> Incomplete: ...
    def utcoffset(self) -> Incomplete: ...
    def tuple(self) -> Incomplete: ...
    def replace(self, x1, x2, x3, x4, x5, x6) -> Incomplete: ...

    resolution: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=1)
    minute: Incomplete  ## <class 'property'> = <property>
    second: Incomplete  ## <class 'property'> = <property>
    tzinfo: Incomplete  ## <class 'property'> = <property>
    min: Incomplete  ## <class 'time'> = datetime.time(microsecond=0, tzinfo=None, fold=0)
    fold: Incomplete  ## <class 'property'> = <property>
    max: Incomplete  ## <class 'time'> = datetime.time(microsecond=86399999999, tzinfo=None, fold=0)
    microsecond: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromisoformat(cls, *args, **kwargs) -> Incomplete: ...

    hour: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...

class date:
    def timetuple(self) -> Incomplete: ...
    def toordinal(self) -> Incomplete: ...
    def isoformat(self) -> Incomplete: ...
    def isoweekday(self) -> Incomplete: ...
    def weekday(self) -> Incomplete: ...
    def replace(self, x1, x2, x3) -> Incomplete: ...
    def tuple(self) -> Incomplete: ...
    @classmethod
    def today(cls, *args, **kwargs) -> Incomplete: ...

    resolution: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=86400000000)
    month: Incomplete  ## <class 'property'> = <property>
    year: Incomplete  ## <class 'property'> = <property>
    min: Incomplete  ## <class 'date'> = datetime.date(0, 0, 1)
    @classmethod
    def fromtimestamp(cls, *args, **kwargs) -> Incomplete: ...

    max: Incomplete  ## <class 'date'> = datetime.date(0, 0, 3652059)
    @classmethod
    def fromordinal(cls, *args, **kwargs) -> Incomplete: ...

    day: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromisoformat(cls, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
