from . import core as core
from typing import Any

class Lock:
    state: int
    waiting: Any
    def __init__(self) -> None: ...
    def locked(self): ...
    def release(self) -> None: ...
    async def acquire(self): ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...
