from typing import Any

class Lock:
    def __init__(self, *argv, **kwargs) -> None: ...
    def release(self, *args, **kwargs) -> Any: ...
    def locked(self, *args, **kwargs) -> Any: ...
    acquire: Any
