from typing import Any

class C_Pointer: ...

class LCT:
    GREY: int
    GREY_ALPHA: int
    MAX_OCTET_VALUE: int
    PALETTE: int
    RGB: int
    RGBA: int

class LodePNGColorMode: ...
class LodePNGDecoderSettings: ...
class LodePNGDecompressSettings: ...
class LodePNGInfo: ...
class LodePNGState: ...
class LodePNGTime: ...

def add_itext(*args) -> Any: ...
def add_text(*args) -> Any: ...
def can_have_alpha(*args) -> Any: ...
def chunk_ancillary(*args) -> Any: ...
def chunk_append(*args) -> Any: ...
def chunk_check_crc(*args) -> Any: ...
def chunk_create(*args) -> Any: ...
def chunk_data(*args) -> Any: ...
def chunk_data_const(*args) -> Any: ...
def chunk_find(*args) -> Any: ...
def chunk_find_const(*args) -> Any: ...
def chunk_generate_crc(*args) -> Any: ...
def chunk_length(*args) -> Any: ...
def chunk_next(*args) -> Any: ...
def chunk_next_const(*args) -> Any: ...
def chunk_private(*args) -> Any: ...
def chunk_safetocopy(*args) -> Any: ...
def chunk_type(*args) -> Any: ...
def chunk_type_equals(*args) -> Any: ...
def clear_icc(*args) -> Any: ...
def clear_itext(*args) -> Any: ...
def clear_text(*args) -> Any: ...
def color_mode_cleanup(*args) -> Any: ...
def color_mode_copy(*args) -> Any: ...
def color_mode_init(*args) -> Any: ...
def color_mode_make(*args) -> Any: ...
def convert(*args) -> Any: ...
def crc32(*args) -> Any: ...
def decode(*args) -> Any: ...
def decode24(*args) -> Any: ...
def decode32(*args) -> Any: ...
def decode_memory(*args) -> Any: ...
def decoder_settings_init(*args) -> Any: ...
def decompress_settings_init(*args) -> Any: ...

default_decompress_settings: Any

def error_text(*args) -> Any: ...
def get_bpp(*args) -> Any: ...
def get_channels(*args) -> Any: ...
def get_raw_size(*args) -> Any: ...
def has_palette_alpha(*args) -> Any: ...
def inflate(*args) -> Any: ...
def info_cleanup(*args) -> Any: ...
def info_copy(*args) -> Any: ...
def info_init(*args) -> Any: ...
def inspect(*args) -> Any: ...
def inspect_chunk(*args) -> Any: ...
def is_alpha_type(*args) -> Any: ...
def is_greyscale_type(*args) -> Any: ...
def is_palette_type(*args) -> Any: ...
def palette_add(*args) -> Any: ...
def palette_clear(*args) -> Any: ...
def set_icc(*args) -> Any: ...
def state_cleanup(*args) -> Any: ...
def state_copy(*args) -> Any: ...
def state_init(*args) -> Any: ...
def zlib_decompress(*args) -> Any: ...
