from _typeshed import Incomplete
from ssd1306 import SSD1306_I2C

class OLED(SSD1306_I2C):
    _reset: Incomplete
    def __init__(self, i2c, reset) -> None: ...
    def reset(self, reinit: bool = ...) -> None: ...
    def test(self) -> None: ...
    def display_wifi(self) -> None: ...
