"""
Module: 'dht' on micropython-v1.20.0-esp32-GENERIC_S3
"""

# MCU: OrderedDict({'version': '1.20.0', 'mpy': 'v6.1', 'port': 'esp32', 'board': 'GENERIC_S3', 'family': 'micropython', 'build': '', 'arch': 'xtensawin', 'ver': 'v1.20.0', 'cpu': 'ESP32S3'})
# Stubber: v1.13.7
from typing import Any


def dht_readinto(*args, **kwargs) -> Any: ...


class DHT22:
    def humidity(self, *args, **kwargs) -> Any: ...

    def temperature(self, *args, **kwargs) -> Any: ...

    def measure(self, *args, **kwargs) -> Any: ...

    def __init__(self, *argv, **kwargs) -> None: ...


class DHT11:
    def humidity(self, *args, **kwargs) -> Any: ...

    def temperature(self, *args, **kwargs) -> Any: ...

    def measure(self, *args, **kwargs) -> Any: ...

    def __init__(self, *argv, **kwargs) -> None: ...


class DHTBase:
    def measure(self, *args, **kwargs) -> Any: ...

    def __init__(self, *argv, **kwargs) -> None: ...
