"""
Module: 'onewire' on micropython-v1.20.0-esp32-GENERIC_S3
"""

# MCU: OrderedDict({'version': '1.20.0', 'mpy': 'v6.1', 'port': 'esp32', 'board': 'GENERIC_S3', 'family': 'micropython', 'build': '', 'arch': 'xtensawin', 'ver': 'v1.20.0', 'cpu': 'ESP32S3'})
# Stubber: v1.13.7
from typing import Any


class OneWire:
    MATCH_ROM = 85  # type: int
    SKIP_ROM = 204  # type: int
    SEARCH_ROM = 240  # type: int

    def select_rom(self, *args, **kwargs) -> Any: ...

    def writebyte(self, *args, **kwargs) -> Any: ...

    def crc8(self, *args, **kwargs) -> Any: ...

    def write(self, *args, **kwargs) -> Any: ...

    def readinto(self, *args, **kwargs) -> Any: ...

    def readbyte(self, *args, **kwargs) -> Any: ...

    def readbit(self, *args, **kwargs) -> Any: ...

    def writebit(self, *args, **kwargs) -> Any: ...

    def reset(self, *args, **kwargs) -> Any: ...

    def scan(self, *args, **kwargs) -> Any: ...

    def __init__(self, *argv, **kwargs) -> None: ...


class OneWireError(Exception): ...
