"""
Module: 'lsm6dsox' on micropython-v1.26.0-rp2
"""

# MCU: {'family': 'micropython', 'version': '1.26.0', 'build': '', 'ver': '1.26.0', 'port': 'rp2', 'board': '', 'cpu': 'RP2040', 'mpy': 'v6.3', 'arch': 'armv6m'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def const(*args, **kwargs) -> Incomplete: ...

class LSM6DSOX:
    def load_mlc(self, *args, **kwargs) -> Incomplete: ...
    def gyro(self, *args, **kwargs) -> Incomplete: ...
    def set_mem_bank(self, *args, **kwargs) -> Incomplete: ...
    def mlc_output(self, *args, **kwargs) -> Incomplete: ...
    def set_embedded_functions(self, *args, **kwargs) -> Incomplete: ...
    def _read_reg(self, *args, **kwargs) -> Incomplete: ...
    def reset(self, *args, **kwargs) -> Incomplete: ...
    def accel(self, *args, **kwargs) -> Incomplete: ...
    def _read_reg_into(self, *args, **kwargs) -> Incomplete: ...
    def _write_reg(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
