"""
Module: 'random' on micropython-v1.26.0-rp2
"""

# MCU: {'family': 'micropython', 'version': '1.26.0', 'build': '', 'ver': '1.26.0', 'port': 'rp2', 'board': '', 'cpu': 'RP2040', 'mpy': 'v6.3', 'arch': 'armv6m'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def randrange(*args, **kwargs) -> Incomplete: ...
def random(*args, **kwargs) -> Incomplete: ...
def seed(*args, **kwargs) -> Incomplete: ...
def uniform(*args, **kwargs) -> Incomplete: ...
def choice(*args, **kwargs) -> Incomplete: ...
def randint(*args, **kwargs) -> Incomplete: ...
def getrandbits(*args, **kwargs) -> Incomplete: ...
