from typing import Any

Node = Any

class Server:
    def close() -> None: ...

class Stream:
    def close() -> None: ...
    def get_extra_info() -> None: ...
    def write() -> None: ...

class StreamReader:
    def close() -> None: ...
    def get_extra_info() -> None: ...
    def write() -> None: ...

class StreamWriter:
    def close() -> None: ...
    def get_extra_info() -> None: ...
    def write() -> None: ...
