"""
Module: 'json' on micropython-v1.26.0-preview-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': 'preview.434.g096ff8b9e', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.26.0-preview-preview.434.g096ff8b9e', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.26.0-preview'}
# Stubber: v1.25.0
from __future__ import annotations
from _typeshed import Incomplete

def loads(*args, **kwargs) -> Incomplete: ...
def load(*args, **kwargs) -> Incomplete: ...
def dumps(*args, **kwargs) -> Incomplete: ...
def dump(*args, **kwargs) -> Incomplete: ...
