"""
Module: 'ds18x20' on micropython-v1.28.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.28.0'}
# Stubber: v1.28.0
from __future__ import annotations
from _typeshed import Incomplete

def const(x0) -> Incomplete: ...

class DS18X20:
    def read_scratch(self, x1) -> Incomplete: ...
    def read_temp(self, x1) -> Incomplete: ...
    def write_scratch(self, x1, x2) -> Incomplete: ...
    def convert_temp(self) -> Incomplete: ...
    def scan(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
