from _typeshed import Incomplete as Incomplete

def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def log_error(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class L2CAPDisconnectedError(Exception): ...
