from typing import Any

class Encode:
    def _available() -> None: ...
    def _update() -> None: ...
    def clearValue() -> None: ...
    def deinit() -> None: ...
    def getDir() -> None: ...
    def getPress() -> None: ...
    def getValue() -> None: ...
    def setLed() -> None: ...

i2c_bus: Any
time: Any
