from typing import Any

class Keyboard:
    def _available() -> None: ...
    def _update() -> None: ...
    def clearStr() -> None: ...
    def deinit() -> None: ...
    def deleteStrLast() -> None: ...
    def isNewKeyPress() -> None: ...
    def readKey() -> None: ...
    def readStr() -> None: ...

i2c_bus: Any
time: Any
