from _typeshed import Incomplete as Incomplete

def log_error(*args, **kwargs) -> Incomplete: ...
def ensure_active(*args, **kwargs) -> Incomplete: ...
def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def log_info(*args, **kwargs) -> Incomplete: ...
def log_warn(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class Device:
    def addr_hex(self, *args, **kwargs) -> Incomplete: ...
    connect: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class DeviceConnection:
    def timeout(self, *args, **kwargs) -> Incomplete: ...
    def is_connected(self, *args, **kwargs) -> Incomplete: ...
    def services(self, *args, **kwargs) -> Incomplete: ...
    l2cap_connect: Incomplete
    l2cap_accept: Incomplete
    pair: Incomplete
    service: Incomplete
    disconnect: Incomplete
    device_task: Incomplete
    disconnected: Incomplete
    exchange_mtu: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

ble: Incomplete

class DeviceTimeout:
    def __init__(self, *argv, **kwargs) -> None: ...

advertise: Incomplete
