"""
Module: 'lsm6dsox' on micropython-v1.28.0-rp2-ARDUINO_NANO_RP2040_CONNECT
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.28.0', 'arch': 'armv6m', 'version': '1.28.0', 'port': 'rp2', 'board': 'ARDUINO_NANO_RP2040_CONNECT', 'family': 'micropython', 'board_id': 'ARDUINO_NANO_RP2040_CONNECT', 'variant': '', 'cpu': 'RP2040'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

def const(*args, **kwargs) -> Incomplete: ...

class LSM6DSOX:
    def mlc_output(self, *args, **kwargs) -> Incomplete: ...
    def pedometer_config(self, *args, **kwargs) -> Incomplete: ...
    def load_mlc(self, *args, **kwargs) -> Incomplete: ...
    def gyro(self, *args, **kwargs) -> Incomplete: ...
    def set_mem_bank(self, *args, **kwargs) -> Incomplete: ...
    def pedometer_reset(self, *args, **kwargs) -> Incomplete: ...
    def set_embedded_functions(self, *args, **kwargs) -> Incomplete: ...
    def steps(self, *args, **kwargs) -> Incomplete: ...
    def _modify_bits(self, *args, **kwargs) -> Incomplete: ...
    def _read_reg(self, *args, **kwargs) -> Incomplete: ...
    def reset(self, *args, **kwargs) -> Incomplete: ...
    def accel(self, *args, **kwargs) -> Incomplete: ...
    def _write_reg(self, *args, **kwargs) -> Incomplete: ...
    def _read_reg_into(self, *args, **kwargs) -> Incomplete: ...
    def _select_page(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
