[tool.micropython-stubber]
# New config
"mpy-stubs-path" = "."

#-----------------
# < v1.18 config
stub-path = "./stubs"
publish-path = "./publish"
template-path = "./publish/template"
#-----------------





#-----------------
[tool.black]
# use same config as -stubber
line-length = 140
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
    /(
        | tests
    )/
)
'''

[tool.pytest.ini_options]
minversion = "7.0"
python_functions = ["test_", "*_test"]
python_files = ["test_*.py", "*_test.py"]
testpaths = ["tests/quality_tests"]
norecursedirs = [
    "publish",
    "stubs",
    "repos",
    "typings*",
    ".svn",
    "_build",
    "tmp*",
    ".*",
    "build",
    "dist",
    "{arch}",
    "*.egg",
]
junit_family = "xunit1"

addopts = "--verbose --capture=no"
#  -m 'not snippets'
# --numprocesses=auto 
# -m MARKEXPR           Only run tests matching given mark expression. For example: -m 'mark1 and not mark2'.
# -n --numprocesses=numprocesses - 

markers = ["snippets: test snippets to check the stub quality"]


exclude = [".git", ".*", "__*", "dist", "test"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.

# Same as Black.
line-length = 140
indent-width = 4

#Stubs should be usable Python 3.9
target-version = "py39"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
exclude = [".*", "__*", "dist", "repos"]

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint]
exclude = [".*", "__*", "dist", "repos"]

extend-select = [
    # "E501", # line too long
    # "UP", # pyupgrade
]
ignore = [
    "F401", # unused import
    "F403", # import *
    "F821",
    "UP035", # pyupgrade `typing.Dict` is deprecated, use `dict` instead
]
