[tool.micropython-stubber]
# New config
"mpy-stubs-path" = "."

#-----------------
# < v1.18 config
stub-path = "./stubs"
publish-path = "./publish"
template-path = "./publish/template"
#-----------------


[tool.ruff]
# Same as Black.
line-length = 140
indent-width = 4
target-version = 'py38'

[tool.ruff.lint]
extend-select = [
    # "E501", # line too long
    "UP", # pyupgrdae
]
ignore = [
    "F401", # unused import
    "F403", # import *
    "F821",
]


exclude = [".git", ".*", "__*", "dist", "test"]


#-----------------
[tool.black]
# use same config as -stubber
line-length = 140
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
    /(
        | tests
    )/
)
'''

[tool.pytest.ini_options]
minversion = "7.0"
python_functions = ["test_", "*_test"]
python_files = ["test_*.py", "*_test.py"]
testpaths = ["tests/quality_tests"]
norecursedirs = [
    "publish",
    "stubs",
    "repos",
    "typings*",
    ".svn",
    "_build",
    "tmp*",
    ".*",
    "build",
    "dist",
    "{arch}",
    "*.egg",
]
junit_family = "xunit1"

addopts = "--verbose --capture=no"
#  -m 'not snippets'
# --numprocesses=auto 
# -m MARKEXPR           Only run tests matching given mark expression. For example: -m 'mark1 and not mark2'.
# -n --numprocesses=numprocesses - 

markers = ["snippets: test snippets to check the stub quality"]
