"""
Module: 'argparse' on micropython-v1.29.0-preview-esp32-ESP32_GENERIC
"""

# MCU: {'variant': '', 'build': 'preview.381.g50348ce0eb.dirty', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'board_id': 'ESP32_GENERIC', 'mpy': 'v6.3', 'ver': '1.29.0-preview-preview.381.g50348ce0eb.dirty', 'family': 'micropython', 'cpu': 'ESP32', 'version': '1.29.0-preview'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

def _dest_from_optnames(*args, **kwargs) -> Incomplete: ...
def namedtuple(*args, **kwargs) -> Incomplete: ...

class _Arg:
    def parse(self, *args, **kwargs) -> Incomplete: ...
    def _apply(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ArgumentParser:
    def _parse_args_impl(self, *args, **kwargs) -> Incomplete: ...
    def _parse_args(self, *args, **kwargs) -> Incomplete: ...
    def parse_known_args(self, *args, **kwargs) -> Incomplete: ...
    def add_argument(self, *args, **kwargs) -> Incomplete: ...
    def parse_args(self, *args, **kwargs) -> Incomplete: ...
    def usage(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ArgumentTypeError(Exception): ...
class _ArgError(Exception): ...
