from typing import Any

Node = Any

def dht_readinto() -> None: ...
def flash_erase() -> None: ...
def flash_read() -> None: ...
def flash_size() -> None: ...
def flash_user_start() -> None: ...
def flash_write() -> None: ...
def gpio_matrix_in() -> None: ...
def gpio_matrix_out() -> None: ...
def neopixel_write() -> None: ...
def osdebug() -> None: ...
