"""
Module: 'lsm6dsox' on micropython-v1.22.0-rp2-ARDUINO_NANO_RP2040_CONNECT
"""

# MCU: {'family': 'micropython', 'version': '1.22.0', 'build': '', 'ver': 'v1.22.0', 'port': 'rp2', 'board': 'ARDUINO_NANO_RP2040_CONNECT', 'cpu': 'RP2040', 'mpy': 'v6.2', 'arch': 'armv6m'}
# Stubber: v1.16.2
from _typeshed import Incomplete


def const(*args, **kwargs) -> Incomplete: ...


class LSM6DSOX:
    def mlc_output(self, *args, **kwargs) -> Incomplete: ...

    def load_mlc(self, *args, **kwargs) -> Incomplete: ...

    def set_embedded_functions(self, *args, **kwargs) -> Incomplete: ...

    def set_mem_bank(self, *args, **kwargs) -> Incomplete: ...

    def reset(self, *args, **kwargs) -> Incomplete: ...

    def gyro(self, *args, **kwargs) -> Incomplete: ...

    def accel(self, *args, **kwargs) -> Incomplete: ...

    def __init__(self, *argv, **kwargs) -> None: ...
