from typing import Any

class ThreadSafeFlag:
    def ioctl(self, *args, **kwargs) -> Any: ...
    def set(self, *args, **kwargs) -> Any: ...
    wait: Any
    def __init__(self, *argv, **kwargs) -> None: ...

class Event:
    def set(self, *args, **kwargs) -> Any: ...
    def is_set(self, *args, **kwargs) -> Any: ...
    def clear(self, *args, **kwargs) -> Any: ...
    wait: Any
    def __init__(self, *argv, **kwargs) -> None: ...
