"""
MicroPython's internal asyncio scheduler module.
"""

from __future__ import annotations

from typing import Any, Coroutine

from _typeshed import Incomplete
from typing_extensions import TypeVar

from .tasks import Task as Task

_T = TypeVar("_T")

class CancelledError(BaseException): ...
class TimeoutError(Exception): ...

_exc_context: Incomplete

class SingletonGenerator:
    state: Incomplete
    exc: Incomplete
    def __init__(self) -> None: ...
    def __iter__(self): ...
    def __next__(self) -> None: ...

def sleep_ms(t, sgen=...) -> Coroutine[Incomplete, Any, Any]: ...
def sleep(t) -> Coroutine[Incomplete, Any, Any]: ...

class IOQueue:
    poller: Incomplete
    map: Incomplete
    def __init__(self) -> None: ...
    def _enqueue(self, s, idx) -> None: ...
    def _dequeue(self, s) -> None: ...
    def queue_read(self, s) -> None: ...
    def queue_write(self, s) -> None: ...
    def remove(self, task) -> None: ...
    def wait_io_event(self, dt) -> None: ...

_io_queue: IOQueue
_task_queue: Incomplete

def _promote_to_task(aw): ...
def create_task(coro) -> Task: ...
def run_until_complete(main_task: Incomplete | None = None): ...
def run(coro) -> _T: ...
async def _stopper() -> None: ...

cur_task: Incomplete
_stop_task: Incomplete

class Loop:
    _exc_handler: Incomplete
    def create_task(coro) -> Task: ...
    def run_forever(self) -> None: ...
    def run_until_complete(aw) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def set_exception_handler(handler) -> None: ...
    def get_exception_handler(self) -> None: ...
    def default_exception_handler(loop, context) -> None: ...
    def call_exception_handler(context) -> None: ...

def get_event_loop(runq_len: int = 0, waitq_len: int = 0) -> Loop: ...
def current_task() -> Task: ...
def new_event_loop() -> Loop: ...
