from typing import Any

class APA102:
    ORDER: Any
    def write(self, *argv) -> Any: ...

class NeoPixel:
    ORDER: Any
    def fill(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...

def apa102_write() -> None: ...
