from typing import Any

class ADC:
    def read(self, *argv) -> Any: ...

DEEPSLEEP: int
DEEPSLEEP_RESET: int
HARD_RESET: int

class I2C:
    def init(self, *argv) -> Any: ...
    def readfrom(self, *argv) -> Any: ...
    def readfrom_into(self, *argv) -> Any: ...
    def readfrom_mem(self, *argv) -> Any: ...
    def readfrom_mem_into(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def scan(self, *argv) -> Any: ...
    def start(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...
    def writeto(self, *argv) -> Any: ...
    def writeto_mem(self, *argv) -> Any: ...

class PWM:
    def deinit(self, *argv) -> Any: ...
    def duty(self, *argv) -> Any: ...
    def freq(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...

PWRON_RESET: int

class Pin:
    IN: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    PULL_UP: int
    def init(self, *argv) -> Any: ...
    def irq(self, *argv) -> Any: ...
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

class RTC:
    ALARM0: int
    def alarm(self, *argv) -> Any: ...
    def alarm_left(self, *argv) -> Any: ...
    def datetime(self, *argv) -> Any: ...
    def irq(self, *argv) -> Any: ...
    def memory(self, *argv) -> Any: ...

SOFT_RESET: int

class SPI:
    LSB: int
    MSB: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...
    def write_readinto(self, *argv) -> Any: ...

class Signal:
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

class Timer:
    ONE_SHOT: int
    PERIODIC: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...

class UART:
    def any(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def readline(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...

class WDT:
    def deinit(self, *argv) -> Any: ...
    def feed(self, *argv) -> Any: ...

WDT_RESET: int

def deepsleep() -> None: ...
def disable_irq() -> None: ...
def enable_irq() -> None: ...
def freq() -> None: ...
def idle() -> None: ...

mem16: Any
mem32: Any
mem8: Any

def reset() -> None: ...
def reset_cause() -> None: ...
def sleep() -> None: ...
def time_pulse_us() -> None: ...
def unique_id() -> None: ...
