from typing import Any

class ADC:
    def read() -> None: ...

DEEPSLEEP: int
DEEPSLEEP_RESET: int
HARD_RESET: int

class I2C:
    def init() -> None: ...
    def readfrom() -> None: ...
    def readfrom_into() -> None: ...
    def readfrom_mem() -> None: ...
    def readfrom_mem_into() -> None: ...
    def readinto() -> None: ...
    def scan() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...
    def write() -> None: ...
    def writeto() -> None: ...
    def writeto_mem() -> None: ...

class PWM:
    def deinit() -> None: ...
    def duty() -> None: ...
    def freq() -> None: ...
    def init() -> None: ...

PWRON_RESET: int

class Pin:
    IN: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    PULL_UP: int
    def init() -> None: ...
    def irq() -> None: ...
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...

class RTC:
    ALARM0: int
    def alarm() -> None: ...
    def alarm_left() -> None: ...
    def datetime() -> None: ...
    def irq() -> None: ...
    def memory() -> None: ...

SOFT_RESET: int

class SPI:
    LSB: int
    MSB: int
    def deinit() -> None: ...
    def init() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def write() -> None: ...
    def write_readinto() -> None: ...

class Signal:
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...

class Timer:
    ONE_SHOT: int
    PERIODIC: int
    def deinit() -> None: ...
    def init() -> None: ...

class UART:
    def any() -> None: ...
    def init() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def write() -> None: ...

class WDT:
    def deinit() -> None: ...
    def feed() -> None: ...

WDT_RESET: int

def deepsleep() -> None: ...
def disable_irq() -> None: ...
def enable_irq() -> None: ...
def freq() -> None: ...
def idle() -> None: ...

mem16: Any
mem32: Any
mem8: Any

def reset() -> None: ...
def reset_cause() -> None: ...
def sleep() -> None: ...
def time_pulse_us() -> None: ...
def unique_id() -> None: ...
