from typing import Any

AF_INET: int
AF_INET6: int
IPPROTO_IP: int
IP_ADD_MEMBERSHIP: int
SOCK_DGRAM: int
SOCK_RAW: int
SOCK_STREAM: int
SOL_SOCKET: int
SO_REUSEADDR: int

def callback() -> None: ...
def getaddrinfo() -> None: ...
def print_pcbs() -> None: ...
def reset() -> None: ...

class socket:
    def accept(self, *argv) -> Any: ...
    def bind(self, *argv) -> Any: ...
    def close(self, *argv) -> Any: ...
    def connect(self, *argv) -> Any: ...
    def listen(self, *argv) -> Any: ...
    def makefile(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def readline(self, *argv) -> Any: ...
    def recv(self, *argv) -> Any: ...
    def recvfrom(self, *argv) -> Any: ...
    def send(self, *argv) -> Any: ...
    def sendall(self, *argv) -> Any: ...
    def sendto(self, *argv) -> Any: ...
    def setblocking(self, *argv) -> Any: ...
    def setsockopt(self, *argv) -> Any: ...
    def settimeout(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...
