"""
Module: 'ustruct' on micropython-v1.23.0-preview-samd-SEEED_WIO_TERMINAL
"""
# MCU: {'version': '1.23.0-preview', 'mpy': 'v6.2', 'port': 'samd', 'board': 'SEEED_WIO_TERMINAL', 'family': 'micropython', 'build': '176', 'arch': 'armv7emsp', 'ver': '1.23.0-preview-176', 'cpu': 'SAMD51P19A'}
# Stubber: v1.17.3
from __future__ import annotations
from _typeshed import Incomplete

def pack_into(*args, **kwargs) -> Incomplete: ...
def unpack(*args, **kwargs) -> Incomplete: ...
def unpack_from(*args, **kwargs) -> Incomplete: ...
def pack(*args, **kwargs) -> Incomplete: ...
def calcsize(*args, **kwargs) -> Incomplete: ...
