"""
Module: 'json' on micropython-v1.27.0-esp8266-ESP8266_GENERIC
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensa', 'port': 'esp8266', 'board': 'ESP8266_GENERIC', 'board_id': 'ESP8266_GENERIC', 'mpy': 'v6.3', 'ver': '1.27.0', 'family': 'micropython', 'cpu': 'ESP8266', 'version': '1.27.0'}
# Stubber: v1.26.4
from __future__ import annotations
from _typeshed import Incomplete

def loads(*args, **kwargs) -> Incomplete: ...
def load(*args, **kwargs) -> Incomplete: ...
def dumps(*args, **kwargs) -> Incomplete: ...
def dump(*args, **kwargs) -> Incomplete: ...
