from _typeshed import Incomplete

WS2812_PIN: Incomplete
BUTTON_PIN: Incomplete
IR_PIN: Incomplete
I2C0_SCL_PIN: Incomplete
I2C0_SDA_PIN: Incomplete
GROVE_PORT_PIN: Incomplete

class ATOM:
    _np: Incomplete
    _btn: Incomplete
    def __init__(self, np_n) -> None: ...
    def get_button_status(self): ...
    def set_button_callback(self, cb) -> None: ...
    def set_pixel_color(self, num, r, g, b) -> None: ...
    def get_pixel_color(self, num): ...
    def set_pixels_color(self, r, g, b) -> None: ...

class Lite(ATOM):
    def __init__(self) -> None: ...

class Matrix(ATOM):
    def __init__(self) -> None: ...
