"""
Module: 'math' on micropython-v1.26.0-windows-standard
"""
# MCU: {'family': 'micropython', 'version': '1.26.0', 'build': '', 'ver': '1.26.0', 'port': 'windows', 'board': 'standard', 'board_id': 'standard', 'variant': '', 'cpu': 'win32 [GCC 12.0.0] version', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.26.2
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

e: float = 2.718281828459045
pi: float = 3.141592653589793
def isnan(*args, **kwargs) -> Incomplete:
    ...

def ldexp(*args, **kwargs) -> Incomplete:
    ...

def lgamma(*args, **kwargs) -> Incomplete:
    ...

def trunc(*args, **kwargs) -> Incomplete:
    ...

def gamma(*args, **kwargs) -> Incomplete:
    ...

def frexp(*args, **kwargs) -> Incomplete:
    ...

def isinf(*args, **kwargs) -> Incomplete:
    ...

def isclose(*args, **kwargs) -> Incomplete:
    ...

def isfinite(*args, **kwargs) -> Incomplete:
    ...

def sqrt(*args, **kwargs) -> Incomplete:
    ...

def sinh(*args, **kwargs) -> Incomplete:
    ...

def log(*args, **kwargs) -> Incomplete:
    ...

def tan(*args, **kwargs) -> Incomplete:
    ...

def tanh(*args, **kwargs) -> Incomplete:
    ...

def log2(*args, **kwargs) -> Incomplete:
    ...

def log10(*args, **kwargs) -> Incomplete:
    ...

def sin(*args, **kwargs) -> Incomplete:
    ...

def modf(*args, **kwargs) -> Incomplete:
    ...

def radians(*args, **kwargs) -> Incomplete:
    ...

def atan2(*args, **kwargs) -> Incomplete:
    ...

def atan(*args, **kwargs) -> Incomplete:
    ...

def fmod(*args, **kwargs) -> Incomplete:
    ...

def atanh(*args, **kwargs) -> Incomplete:
    ...

def ceil(*args, **kwargs) -> Incomplete:
    ...

def acos(*args, **kwargs) -> Incomplete:
    ...

def pow(*args, **kwargs) -> Incomplete:
    ...

def asinh(*args, **kwargs) -> Incomplete:
    ...

def acosh(*args, **kwargs) -> Incomplete:
    ...

def asin(*args, **kwargs) -> Incomplete:
    ...

def expm1(*args, **kwargs) -> Incomplete:
    ...

def exp(*args, **kwargs) -> Incomplete:
    ...

def copysign(*args, **kwargs) -> Incomplete:
    ...

def fabs(*args, **kwargs) -> Incomplete:
    ...

def floor(*args, **kwargs) -> Incomplete:
    ...

def cosh(*args, **kwargs) -> Incomplete:
    ...

def cos(*args, **kwargs) -> Incomplete:
    ...

def erfc(*args, **kwargs) -> Incomplete:
    ...

def degrees(*args, **kwargs) -> Incomplete:
    ...

def erf(*args, **kwargs) -> Incomplete:
    ...

