
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Event:
    def clear() -> None: ...
    def is_set() -> None: ...
    def set() -> None: ...
class ThreadSafeFlag:
    def ioctl() -> None: ...
    def set() -> None: ...
