from _typeshed import Incomplete

log_level: int

def log_error(*args) -> None: ...
def log_warn(*args) -> None: ...
def log_info(*args) -> None: ...

class GattError(Exception):
    _status: Incomplete
    def __init__(self, status) -> None: ...

def ensure_active() -> None: ...
def config(*args, **kwargs): ...

_irq_handlers: Incomplete
_shutdown_handlers: Incomplete

def register_irq_handler(irq, shutdown) -> None: ...
def stop() -> None: ...
def ble_irq(event, data): ...

ble: Incomplete
