from typing import Any

def _chr_addr() -> None: ...

_font: Any
_index: Any
_mvfont: Any

def get_ch() -> None: ...
def height() -> None: ...
def hmap() -> None: ...
def max_ch() -> None: ...
def max_width() -> None: ...
def min_ch() -> None: ...
def monospaced() -> None: ...
def reverse() -> None: ...

version: str
