from typing import Any

Node = Any

class MicroWebSocket:
    def Close() -> None: ...
    def IsClosed() -> None: ...
    def SendBinary() -> None: ...
    def SendText() -> None: ...
    def _handshake() -> None: ...
    def _receiveFrame() -> None: ...
    def _sendFrame() -> None: ...
    def _tryAllocByteArray() -> None: ...
    def _tryStartThread() -> None: ...
    def _wsProcess() -> None: ...
    def threadID() -> None: ...

def b2a_base64() -> None: ...
def pack() -> None: ...

class sha1:
    def digest() -> None: ...
    def update() -> None: ...
