from typing import Any

class ArithmeticError: ...
class AssertionError: ...
class AttributeError: ...
class BaseException: ...
class EOFError: ...

Ellipsis: Any

class Exception: ...
class GeneratorExit: ...
class ImportError: ...
class IndentationError: ...
class IndexError: ...
class KeyError: ...
class KeyboardInterrupt: ...
class LookupError: ...
class MemoryError: ...
class NameError: ...
class NotImplementedError: ...
class OSError: ...
class OverflowError: ...
class RuntimeError: ...
class StopAsyncIteration: ...
class StopIteration: ...
class SyntaxError: ...
class SystemExit: ...
class TypeError: ...
class UnicodeError: ...
class ValueError: ...
class ViperTypeError: ...
class ZeroDivisionError: ...

def abs() -> None: ...
def all() -> None: ...
def any() -> None: ...
def bin() -> None: ...

class bool: ...

class bytearray:
    def append() -> None: ...
    def extend() -> None: ...

class bytes: ...
