from typing import Any

class DHT11:
    def humidity() -> None: ...
    def temperature() -> None: ...

class DHT22:
    def humidity() -> None: ...
    def temperature() -> None: ...

class DHTBase:
    def measure() -> None: ...

esp: Any
