SLEEP_LIGHT: int
SLEEP_MODEM: int
SLEEP_NONE: int

def apa102_write() -> None: ...
def check_fw() -> None: ...
def deepsleep() -> None: ...
def dht_readinto() -> None: ...
def esf_free_bufs() -> None: ...
def flash_erase() -> None: ...
def flash_id() -> None: ...
def flash_read() -> None: ...
def flash_size() -> None: ...
def flash_user_start() -> None: ...
def flash_write() -> None: ...
def free() -> None: ...
def freemem() -> None: ...
def info() -> None: ...
def malloc() -> None: ...
def meminfo() -> None: ...
def neopixel_write() -> None: ...
def osdebug() -> None: ...
def set_native_code_location() -> None: ...
def sleep_type() -> None: ...
