from typing import Any

class Color:
    def _available(self, *argv) -> Any: ...
    def _read_u16(self, *argv) -> Any: ...
    def _read_u8(self, *argv) -> Any: ...
    def _register_char(self, *argv) -> Any: ...
    def _register_short(self, *argv) -> Any: ...
    def _valid(self, *argv) -> Any: ...
    def _write_u16(self, *argv) -> Any: ...
    def _write_u8(self, *argv) -> Any: ...
    blue: Any
    def deinit(self, *argv) -> Any: ...
    def enable(self, *argv) -> Any: ...
    def getRGB(self, *argv) -> Any: ...
    green: Any
    portMethod: int
    rawData: Any
    red: Any
    def setGains(self, *argv) -> Any: ...
    def setIntegrationTime(self, *argv) -> Any: ...

INT_TIME_DELAY: Any
_CYCLES: Any
_GAINS: Any
_INTEGRATION_TIME_THRESHOLD_HIGH: float
_INTEGRATION_TIME_THRESHOLD_LOW: float

def const() -> None: ...

i2c_bus: Any
time: Any
unit: Any
ustruct: Any
