from typing import Any

ACK_FAIL: int
ACK_FULL: int
ACK_NOUSER: int
ACK_SUCCESS: int
ACK_TIMEOUT: int
ACK_USER_EXIST: int
ACK_USER_OCCUPIED: int

class Finger:
    def _monitor(self, *argv) -> Any: ...
    def _write(self, *argv) -> Any: ...
    def addUser(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def getUnknownCb(self, *argv) -> Any: ...
    def readFingerCb(self, *argv) -> Any: ...
    def readUser(self, *argv) -> Any: ...
    def removeAllUser(self, *argv) -> Any: ...
    def removeUser(self, *argv) -> Any: ...

machine: Any
timEx: Any
time: Any
unit: Any
