from typing import Any

class Ir:
    def _irq_cb(self, *argv) -> Any: ...
    def _update(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    portMethod: int
    def rxStatus(self, *argv) -> Any: ...
    def txOff(self, *argv) -> Any: ...
    def txOn(self, *argv) -> Any: ...

class PWM:
    def deinit(self, *argv) -> Any: ...
    def duty(self, *argv) -> Any: ...
    def freq(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def list(self, *argv) -> Any: ...
    def pause(self, *argv) -> Any: ...
    def resume(self, *argv) -> Any: ...

class Pin:
    IN: int
    INOUT: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    OUT_OD: int
    PULL_DOWN: int
    PULL_FLOAT: int
    PULL_HOLD: int
    PULL_UP: int
    WAKE_HIGH: int
    WAKE_LOW: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def irq(self, *argv) -> Any: ...
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

class Timer:
    ONE_SHOT: int
    PERIODIC: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

peripheral: Any
unit: Any
