from typing import Any

class Mlx90640:
    apply: Any
    def deinit(self, *argv) -> Any: ...
    def getCenterTmp(self, *argv) -> Any: ...
    def getMaxTmp(self, *argv) -> Any: ...
    def getMinTmp(self, *argv) -> Any: ...
    def getTmp(self, *argv) -> Any: ...
    def setColorMaxTmp(self, *argv) -> Any: ...
    def setColorMinTmp(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

i2c_bus: Any
mlx90640: Any
unit: Any
