from typing import Any

class Pahub:
    def _available(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def select(self, *argv) -> Any: ...
    def select_only_on(self, *argv) -> Any: ...
    def select_port(self, *argv) -> Any: ...

i2c_bus: Any
unit: Any
