from typing import Any

class Pbhub:
    def _available(self, *argv) -> Any: ...
    def analogRead(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def digitalRead(self, *argv) -> Any: ...
    def digitalWrite(self, *argv) -> Any: ...
    def setBrightness(self, *argv) -> Any: ...
    def setColor(self, *argv) -> Any: ...
    def setColorPos(self, *argv) -> Any: ...
    def setRgbNum(self, *argv) -> Any: ...

hub_addr: Any
i2c_bus: Any
unit: Any
