from typing import Any

AUTHENT1A: int
AUTHENT1B: int
ERR: int
NOTAGERR: int
OK: int
REQALL: int
REQIDL: int

class Rfid:
    def _antenna_on(self, *argv) -> Any: ...
    def _anticoll(self, *argv) -> Any: ...
    def _auth(self, *argv) -> Any: ...
    def _available(self, *argv) -> Any: ...
    def _cflags(self, *argv) -> Any: ...
    def _crc(self, *argv) -> Any: ...
    def _get_access(self, *argv) -> Any: ...
    def _read(self, *argv) -> Any: ...
    def _request(self, *argv) -> Any: ...
    def _reset(self, *argv) -> Any: ...
    def _rreg(self, *argv) -> Any: ...
    def _selectTag(self, *argv) -> Any: ...
    def _sflags(self, *argv) -> Any: ...
    def _stop_crypto1(self, *argv) -> Any: ...
    def _tocard(self, *argv) -> Any: ...
    def _wreg(self, *argv) -> Any: ...
    def _write(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def isCardOn(self, *argv) -> Any: ...
    def readBlock(self, *argv) -> Any: ...
    def readBlockStr(self, *argv) -> Any: ...
    def readUid(self, *argv) -> Any: ...
    def writeBlock(self, *argv) -> Any: ...

def const() -> None: ...

i2c_bus: Any
time: Any
unit: Any
