from typing import Any

class Rgb:
    def deinit(self, *argv) -> Any: ...
    def setBrightness(self, *argv) -> Any: ...
    def setColor(self, *argv) -> Any: ...
    def setColorAll(self, *argv) -> Any: ...
    def setColorFrom(self, *argv) -> Any: ...
    def setShowLock(self, *argv) -> Any: ...
    def show(self, *argv) -> Any: ...

_rgb_multi: Any
