from typing import Any

class Tof:
    def _available() -> None: ...
    def _register_char() -> None: ...
    def _register_short() -> None: ...
    def _update() -> None: ...
    def deinit() -> None: ...

def const() -> None: ...

i2c_bus: Any
machine: Any
timEx: Any
unit: Any
ustruct: Any
