from typing import Any

class Tof:
    def _available(self, *argv) -> Any: ...
    def _register_char(self, *argv) -> Any: ...
    def _register_short(self, *argv) -> Any: ...
    def _update(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...

def const() -> None: ...

i2c_bus: Any
machine: Any
timEx: Any
unit: Any
ustruct: Any
