from typing import Any

class Tracker:
    def _available(self, *argv) -> Any: ...
    def _register_char(self, *argv) -> Any: ...
    def _register_short(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def getAnalogValue(self, *argv) -> Any: ...
    def getDigitalValue(self, *argv) -> Any: ...
    def setAnalogValue(self, *argv) -> Any: ...

i2c_bus: Any
unit: Any
ustruct: Any
