from typing import Any

class MQTTClient:
    DEBUG: Any
    DELAY: int
    def _recv_len(self, *argv) -> Any: ...
    def _send_str(self, *argv) -> Any: ...
    def check_msg(self, *argv) -> Any: ...
    def connect(self, *argv) -> Any: ...
    def delay(self, *argv) -> Any: ...
    def disconnect(self, *argv) -> Any: ...
    def log(self, *argv) -> Any: ...
    def ping(self, *argv) -> Any: ...
    publish: Any
    reconnect: Any
    def set_callback(self, *argv) -> Any: ...
    def set_last_will(self, *argv) -> Any: ...
    def subscribe(self, *argv) -> Any: ...
    wait_msg: Any

simple: Any
utime: Any
