from typing import Any

class MQTTClient:
    def _recv_len(self, *argv) -> Any: ...
    def _send_str(self, *argv) -> Any: ...
    def check_msg(self, *argv) -> Any: ...
    def connect(self, *argv) -> Any: ...
    def disconnect(self, *argv) -> Any: ...
    def ping(self, *argv) -> Any: ...
    def publish(self, *argv) -> Any: ...
    def set_callback(self, *argv) -> Any: ...
    def set_last_will(self, *argv) -> Any: ...
    def subscribe(self, *argv) -> Any: ...
    def wait_msg(self, *argv) -> Any: ...

class MQTTException(Exception): ...

def hexlify() -> None: ...

socket: Any
struct: Any
