from typing import Any

WS2812_PIN: Any
BUTTON_PIN: Any
IR_PIN: Any
I2C0_SCL_PIN: Any
I2C0_SDA_PIN: Any
GROVE_PORT_PIN: Any

class ATOM:
    _np: Any
    _btn: Any
    def __init__(self, np_n) -> None: ...
    def get_button_status(self): ...
    def set_button_callback(self, cb) -> None: ...
    def set_pixel_color(self, num, r, g, b) -> None: ...
    def get_pixel_color(self, num): ...
    def set_pixels_color(self, r, g, b) -> None: ...

class Lite(ATOM):
    def __init__(self) -> None: ...

class Matrix(ATOM):
    def __init__(self) -> None: ...
