from typing import Any

VFS_FAT: int
VFS_LFS1: int
VFS_LFS2: int
_ELEM_TYPE_END: Any
_ELEM_TYPE_MOUNT: Any
_ELEM_TYPE_FSLOAD: Any
_ELEM_TYPE_STATUS: Any

def check_mem_contains(addr, buf): ...
def dfu_read(filename): ...

class Flash:
    _FLASH_KEY1: int
    _FLASH_KEY2: int
    addressof: Any
    _keyr: Any
    _sr: Any
    _sr_busy: Any
    _cr: Any
    _cr_lock: Any
    _cr_init_erase: Any
    _cr_start_erase: Any
    _cr_init_write: Any
    _cr_flush: Any
    _write_multiple: int
    sector0_size: Any
    def __init__(self): ...
    def wait_not_busy(self) -> None: ...
    def unlock(self) -> None: ...
    def lock(self) -> None: ...
    def erase_sector(self, sector) -> None: ...
    def write(self, addr, buf) -> None: ...

def update_mboot(filename) -> None: ...
def _create_element(kind, body): ...
def update_app_elements(
    filename, fs_base, fs_len, fs_type=..., fs_blocksize: int = ..., status_addr: Any | None = ..., addr_64bit: bool = ...
): ...
def update_mpy(*args, **kwargs) -> None: ...
