# This umodule is a MicroPython reference to machine
from machine import ADC as ADC
from machine import DEEPSLEEP as DEEPSLEEP
from machine import DEEPSLEEP_RESET as DEEPSLEEP_RESET
from machine import HARD_RESET as HARD_RESET
from machine import I2C as I2C
from machine import PWM as PWM
from machine import PWRON_RESET as PWRON_RESET
from machine import RTC as RTC
from machine import SOFT_RESET as SOFT_RESET
from machine import SPI as SPI
from machine import UART as UART
from machine import WDT as WDT
from machine import WDT_RESET as WDT_RESET
from machine import Pin as Pin
from machine import Signal as Signal
from machine import SoftI2C as SoftI2C
from machine import SoftSPI as SoftSPI
from machine import Timer as Timer
from machine import bitstream as bitstream
from machine import deepsleep as deepsleep
from machine import dht_readinto as dht_readinto
from machine import disable_irq as disable_irq
from machine import enable_irq as enable_irq
from machine import freq as freq
from machine import idle as idle
from machine import lightsleep as lightsleep
from machine import mem8 as mem8
from machine import mem16 as mem16
from machine import mem32 as mem32
from machine import reset as reset
from machine import reset_cause as reset_cause
from machine import sleep as sleep
from machine import soft_reset as soft_reset
from machine import time_pulse_us as time_pulse_us
from machine import unique_id as unique_id
