from typing import Any

DEBUG: int

class EventLoop:
    def call_at_() -> None: ...
    def call_later() -> None: ...
    def call_later_ms() -> None: ...
    def call_soon() -> None: ...
    def close() -> None: ...
    def create_task() -> None: ...
    def run_forever() -> None: ...
    def run_until_complete() -> None: ...
    def stop() -> None: ...
    def time() -> None: ...
    def wait() -> None: ...

class IORead: ...
class IOReadDone: ...
class IOWrite: ...
class IOWriteDone: ...

class PollEventLoop:
    def add_reader() -> None: ...
    def add_writer() -> None: ...
    def remove_reader() -> None: ...
    def remove_writer() -> None: ...
    def wait() -> None: ...

class SleepMs: ...
class StopLoop: ...

class StreamReader:
    aclose: Any
    read: Any
    readexactly: Any
    readline: Any

class StreamWriter:
    aclose: Any
    awrite: Any
    awriteiter: Any
    def get_extra_info() -> None: ...

class SysCall:
    def handle() -> None: ...

class SysCall1: ...

def Task() -> None: ...

_socket: Any
core: Any

def coroutine() -> None: ...
def ensure_future() -> None: ...
def get_event_loop() -> None: ...

log: Any
open_connection: Any
select: Any

def set_debug() -> None: ...

sleep: Any
sleep_ms: Any
start_server: Any
time: Any

class type_gen:
    def close() -> None: ...
    def send() -> None: ...
    def throw() -> None: ...

uasyncio: Any
uerrno: Any
utimeq: Any
