
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def crc8() -> None: ...
def readbit() -> None: ...
def readbyte() -> None: ...
def reset() -> None: ...
def writebit() -> None: ...
def writebyte() -> None: ...
