
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class BytesIO:
    def close() -> None: ...
    def flush() -> None: ...
    def getvalue() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def seek() -> None: ...
    def write() -> None: ...
class FileIO: ...
