from typing import Any

def dht_readinto(*args, **kwargs) -> Any: ...

class DHT22:
    def humidity(self, *args, **kwargs) -> Any: ...
    def temperature(self, *args, **kwargs) -> Any: ...
    def measure(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class DHT11:
    def humidity(self, *args, **kwargs) -> Any: ...
    def temperature(self, *args, **kwargs) -> Any: ...
    def measure(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class DHTBase:
    def measure(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
