from typing import Any

DIRTYPE: str

class TarFile:
    def __init__(self, *argv, **kwargs) -> None: ...
    def next(self, *args, **kwargs) -> Any: ...
    def extractfile(self, *args, **kwargs) -> Any: ...

class FileSection:
    def __init__(self, *argv, **kwargs) -> None: ...
    def read(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def skip(self, *args, **kwargs) -> Any: ...

class TarInfo:
    def __init__(self, *argv, **kwargs) -> None: ...

def roundup(*args, **kwargs) -> Any: ...

TAR_HEADER: dict
REGTYPE: str
