class SyncModem:
    def _after_init(self) -> None: ...
    def send(self, packet, tx_at_ms=None): ...
    def recv(self, timeout_ms=None, rx_length: int = 255, rx_packet=None): ...
    def _sync_wait(self, will_irq) -> None: ...
