# This umodule is a MicroPython reference to machine
from machine import ADC as ADC
from machine import DEEPSLEEP as DEEPSLEEP
from machine import DEEPSLEEP_RESET as DEEPSLEEP_RESET
from machine import EXT0_WAKE as EXT0_WAKE
from machine import EXT1_WAKE as EXT1_WAKE
from machine import HARD_RESET as HARD_RESET
from machine import I2C as I2C
from machine import I2S as I2S
from machine import PIN_WAKE as PIN_WAKE
from machine import PWM as PWM
from machine import PWRON_RESET as PWRON_RESET
from machine import RTC as RTC
from machine import SLEEP as SLEEP
from machine import SOFT_RESET as SOFT_RESET
from machine import SPI as SPI
from machine import TIMER_WAKE as TIMER_WAKE
from machine import TOUCHPAD_WAKE as TOUCHPAD_WAKE
from machine import UART as UART
from machine import ULP_WAKE as ULP_WAKE
from machine import WDT as WDT
from machine import WDT_RESET as WDT_RESET
from machine import ADCBlock as ADCBlock
from machine import Counter as Counter
from machine import Encoder as Encoder
from machine import I2CTarget as I2CTarget
from machine import Pin as Pin
from machine import SDCard as SDCard
from machine import Signal as Signal
from machine import SoftI2C as SoftI2C
from machine import SoftSPI as SoftSPI
from machine import Timer as Timer
from machine import bitstream as bitstream
from machine import const as const
from machine import deepsleep as deepsleep
from machine import dht_readinto as dht_readinto
from machine import disable_irq as disable_irq
from machine import enable_irq as enable_irq
from machine import freq as freq
from machine import idle as idle
from machine import lightsleep as lightsleep
from machine import mem8 as mem8
from machine import mem16 as mem16
from machine import mem32 as mem32
from machine import mem_backup as mem_backup
from machine import reset as reset
from machine import reset_cause as reset_cause
from machine import sleep as sleep
from machine import soft_reset as soft_reset
from machine import time_pulse_us as time_pulse_us
from machine import unique_id as unique_id
from machine import wake_pins as wake_pins
from machine import wake_reason as wake_reason
