
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def add_peer() -> None: ...
def broadcast() -> None: ...
def deinit() -> None: ...
def get_mac_addr() -> None: ...
def init() -> None: ...
def recv_cb() -> None: ...
def recv_data() -> None: ...
def send() -> None: ...
def send_cb() -> None: ...
def set_pmk() -> None: ...
