
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class ADC:
    def atten() -> None: ...
    def collect() -> None: ...
    def collected() -> None: ...
    def deinit() -> None: ...
    def progress() -> None: ...
    def read() -> None: ...
    def read_timed() -> None: ...
    def readraw() -> None: ...
    def stopcollect() -> None: ...
    def vref() -> None: ...
    def width() -> None: ...
class DAC:
    def beep() -> None: ...
    def deinit() -> None: ...
    def freq() -> None: ...
    def stopwave() -> None: ...
    def waveform() -> None: ...
    def wavplay() -> None: ...
    def write() -> None: ...
    def write_buffer() -> None: ...
    def write_timed() -> None: ...
class I2C:
    def address() -> None: ...
    def begin() -> None: ...
    def callback() -> None: ...
    def clock_timing() -> None: ...
    def data_timing() -> None: ...
    def deinit() -> None: ...
    def end() -> None: ...
    def getdata() -> None: ...
    def init() -> None: ...
    def is_ready() -> None: ...
    def read_byte() -> None: ...
    def read_bytes() -> None: ...
    def readfrom() -> None: ...
    def readfrom_into() -> None: ...
    def readfrom_mem() -> None: ...
    def readfrom_mem_into() -> None: ...
    def resetbusy() -> None: ...
    def scan() -> None: ...
    def setdata() -> None: ...
    def start() -> None: ...
    def start_timing() -> None: ...
    def stop() -> None: ...
    def stop_timing() -> None: ...
    def timeout() -> None: ...
    def write_byte() -> None: ...
    def write_bytes() -> None: ...
    def writeto() -> None: ...
    def writeto_mem() -> None: ...
class I2S:
    def adc_enable() -> None: ...
    def bits() -> None: ...
    def deinit() -> None: ...
    def init() -> None: ...
    def nchannels() -> None: ...
    def read() -> None: ...
    def sample_rate() -> None: ...
    def set_adc_pin() -> None: ...
    def set_dac_mode() -> None: ...
    def set_pin() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...
    def volume() -> None: ...
    def write() -> None: ...
class Neopixel:
    def HSBtoRGB() -> None: ...
    def HSBtoRGBint() -> None: ...
    def RGBtoHSB() -> None: ...
    def brightness() -> None: ...
    def clear() -> None: ...
    def color_order() -> None: ...
    def deinit() -> None: ...
    def get() -> None: ...
    def info() -> None: ...
    def rainbow() -> None: ...
    def set() -> None: ...
    def setHSB() -> None: ...
    def setHSBint() -> None: ...
    def setWhite() -> None: ...
    def show() -> None: ...
    def timings() -> None: ...
class PWM:
    def deinit() -> None: ...
    def duty() -> None: ...
    def freq() -> None: ...
    def init() -> None: ...
    def list() -> None: ...
    def pause() -> None: ...
    def resume() -> None: ...
class Pin:
    def deinit() -> None: ...
    def init() -> None: ...
    def irq() -> None: ...
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...
class RTC:
    def datetime() -> None: ...
    def init() -> None: ...
    def memory() -> None: ...
class Signal:
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...
class Timer:
    def deinit() -> None: ...
    def init() -> None: ...
    def value() -> None: ...
class TouchPad:
    def config() -> None: ...
    def read() -> None: ...
class UART:
    def any() -> None: ...
    def deinit() -> None: ...
    def init() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def sendbreak() -> None: ...
    def write() -> None: ...
class WDT:
    def feed() -> None: ...
def deepsleep() -> None: ...
def disable_irq() -> None: ...
def enable_irq() -> None: ...
def freq() -> None: ...
def heap_info() -> None: ...
def idle() -> None: ...
def lightsleep() -> None: ...
def nvs_erase() -> None: ...
def nvs_erase_all() -> None: ...
def nvs_getint() -> None: ...
def nvs_getstr() -> None: ...
def nvs_setint() -> None: ...
def nvs_setstr() -> None: ...
def random() -> None: ...
def reset() -> None: ...
def reset_cause() -> None: ...
def sleep() -> None: ...
def time_pulse_us() -> None: ...
def unique_id() -> None: ...
def wake_reason() -> None: ...
