"""
Module: 'argparse' on micropython-v1.28.0-unix-standard
"""

# MCU: {'family': 'micropython', 'version': '1.28.0', 'build': '', 'ver': '1.28.0', 'port': 'unix', 'board': 'standard', 'board_id': 'standard', 'variant': '', 'cpu': 'linux [GCC 12.5.0] version', 'mpy': 'v6.3', 'arch': 'x64'}
# Stubber: v1.28.3
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

def _dest_from_optnames(*args, **kwargs) -> Incomplete: ...
def namedtuple(*args, **kwargs) -> Incomplete: ...

class _Arg:
    def parse(self, *args, **kwargs) -> Incomplete: ...
    def _apply(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class _ArgError(Exception): ...
class ArgumentTypeError(Exception): ...

class ArgumentParser:
    def parse_args(self, *args, **kwargs) -> Incomplete: ...
    def usage(self, *args, **kwargs) -> Incomplete: ...
    def parse_known_args(self, *args, **kwargs) -> Incomplete: ...
    def _parse_args(self, *args, **kwargs) -> Incomplete: ...
    def add_argument(self, *args, **kwargs) -> Incomplete: ...
    def _parse_args_impl(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
