"""
Module: 'pathlib' on micropython-v1.28.0-unix-standard
"""

# MCU: {'family': 'micropython', 'version': '1.28.0', 'build': '', 'ver': '1.28.0', 'port': 'unix', 'board': 'standard', 'board_id': 'standard', 'variant': '', 'cpu': 'linux [GCC 12.5.0] version', 'mpy': 'v6.3', 'arch': 'x64'}
# Stubber: v1.28.3
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

def _clean_segment(*args, **kwargs) -> Incomplete: ...
def _mode_if_exists(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class Path:
    def with_suffix(self, *args, **kwargs) -> Incomplete: ...
    def write_text(self, *args, **kwargs) -> Incomplete: ...
    def write_bytes(self, *args, **kwargs) -> Incomplete: ...
    def is_file(self, *args, **kwargs) -> Incomplete: ...
    def is_dir(self, *args, **kwargs) -> Incomplete: ...
    def read_text(self, *args, **kwargs) -> Incomplete: ...
    def touch(self, *args, **kwargs) -> Incomplete: ...
    def glob(self, *args, **kwargs) -> Incomplete: ...
    def read_bytes(self, *args, **kwargs) -> Incomplete: ...
    def rglob(self, *args, **kwargs) -> Incomplete: ...
    def rmdir(self, *args, **kwargs) -> Incomplete: ...
    def rename(self, *args, **kwargs) -> Incomplete: ...
    def mkdir(self, *args, **kwargs) -> Incomplete: ...
    def open(self, *args, **kwargs) -> Incomplete: ...
    def resolve(self, *args, **kwargs) -> Incomplete: ...
    def exists(self, *args, **kwargs) -> Incomplete: ...
    def absolute(self, *args, **kwargs) -> Incomplete: ...
    def stat(self, *args, **kwargs) -> Incomplete: ...
    def unlink(self, *args, **kwargs) -> Incomplete: ...

    stem: Incomplete  ## <class 'property'> = <property>
    parent: Incomplete  ## <class 'property'> = <property>
    name: Incomplete  ## <class 'property'> = <property>
    suffix: Incomplete  ## <class 'property'> = <property>
    def _glob(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...
