"""
Module: 'urandom' on micropython-v1.23.0-preview-rp2-RPI_PICO
"""
# MCU: {'build': 'preview.203.gd712feb68', 'ver': '1.23.0-preview-preview.203.gd712feb68', 'version': '1.23.0-preview', 'port': 'rp2', 'board': 'RPI_PICO', 'mpy': 'v6.2', 'family': 'micropython', 'cpu': 'RP2040', 'arch': 'armv6m'}
# Stubber: v1.17.3
from __future__ import annotations
from _typeshed import Incomplete

def randrange(*args, **kwargs) -> Incomplete: ...
def random(*args, **kwargs) -> Incomplete: ...
def seed(*args, **kwargs) -> Incomplete: ...
def uniform(*args, **kwargs) -> Incomplete: ...
def choice(*args, **kwargs) -> Incomplete: ...
def randint(*args, **kwargs) -> Incomplete: ...
def getrandbits(*args, **kwargs) -> Incomplete: ...
