from typing import Any

Node = Any

class DS18X20:
    def convert_temp() -> None: ...
    def read_scratch() -> None: ...
    def read_temp() -> None: ...
    def scan() -> None: ...
    def write_scratch() -> None: ...

def const() -> None: ...
