from typing import Any

class NotFoundError(Exception): ...

def _makedirs(*args) -> Any: ...
def cleanup(*args) -> Any: ...

cleanup_files: Any
debug: Any
errno: Any

def expandhome(*args) -> Any: ...
def fatal(*args) -> Any: ...

file_buf: Any
gc: Any

def get_install_path(*args) -> Any: ...
def get_pkg_metadata(*args) -> Any: ...

gzdict_sz: int

def help(*args) -> Any: ...

index_urls: Any

def install(*args) -> Any: ...

install_path: Any

def install_pkg(*args) -> Any: ...
def install_tar(*args) -> Any: ...

json: Any

def main(*args) -> Any: ...
def op_basename(*args) -> Any: ...
def op_split(*args) -> Any: ...

os: Any

def save_file(*args) -> Any: ...

sys: Any
tarfile: Any

def url_open(*args) -> Any: ...

usocket: Any
ussl: Any
uzlib: Any
warn_ussl: Any
