from typing import Any

class M5mqtt:
    def _daemonTask(self, *argv) -> Any: ...
    def _msg_deal(self, *argv) -> Any: ...
    def _on_data(self, *argv) -> Any: ...
    def on_connect(self, *argv) -> Any: ...
    def publish(self, *argv) -> Any: ...
    def start(self, *argv) -> Any: ...
    def subscribe(self, *argv) -> Any: ...
    def unsubscribe(self, *argv) -> Any: ...

class MQTTClient:
    def _clean_sock_buffer(self, *argv) -> Any: ...
    def _recv_len(self, *argv) -> Any: ...
    def _send_str(self, *argv) -> Any: ...
    def check_msg(self, *argv) -> Any: ...
    def connect(self, *argv) -> Any: ...
    def disconnect(self, *argv) -> Any: ...
    def lock_msg_rec(self, *argv) -> Any: ...
    def ping(self, *argv) -> Any: ...
    def publish(self, *argv) -> Any: ...
    def set_block(self, *argv) -> Any: ...
    def set_callback(self, *argv) -> Any: ...
    def set_last_will(self, *argv) -> Any: ...
    def socket_connect(self, *argv) -> Any: ...
    def subscribe(self, *argv) -> Any: ...
    def topic_get(self, *argv) -> Any: ...
    def topic_msg_get(self, *argv) -> Any: ...
    def unlock_msg_rec(self, *argv) -> Any: ...
    def wait_msg(self, *argv) -> Any: ...

_thread: Any

def autoConnect() -> None: ...

lcd: Any
m5base: Any
machine: Any

def reconnect() -> None: ...

time: Any
wlan_sta: Any
