from typing import Any

class Btn:
    def attach(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def detach(self, *argv) -> Any: ...
    def multiBtnCb(self, *argv) -> Any: ...
    def restart(self, *argv) -> Any: ...
    def timerCb(self, *argv) -> Any: ...

class BtnChild:
    def deinit(self, *argv) -> Any: ...
    def isPressed(self, *argv) -> Any: ...
    def isReleased(self, *argv) -> Any: ...
    def pressFor(self, *argv) -> Any: ...
    def restart(self, *argv) -> Any: ...
    def upDate(self, *argv) -> Any: ...
    def wasDoublePress(self, *argv) -> Any: ...
    def wasPressed(self, *argv) -> Any: ...
    def wasReleased(self, *argv) -> Any: ...

class IP5306:
    def getBatteryLevel(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def isChargeFull(self, *argv) -> Any: ...
    def isCharging(self, *argv) -> Any: ...
    def setCharge(self, *argv) -> Any: ...
    def setChargeVolt(self, *argv) -> Any: ...
    def setVinMaxCurrent(self, *argv) -> Any: ...

class Rgb_multi:
    def deinit(self, *argv) -> Any: ...
    def setBrightness(self, *argv) -> Any: ...
    def setColor(self, *argv) -> Any: ...
    def setColorAll(self, *argv) -> Any: ...
    def setColorFrom(self, *argv) -> Any: ...
    def setShowLock(self, *argv) -> Any: ...
    def show(self, *argv) -> Any: ...

class Speaker:
    def _timeout_cb(self, *argv) -> Any: ...
    def checkInit(self, *argv) -> Any: ...
    def setBeat(self, *argv) -> Any: ...
    def setVolume(self, *argv) -> Any: ...
    def sing(self, *argv) -> Any: ...
    def tone(self, *argv) -> Any: ...

_sdCardState: Any
apikey: str
binascii: Any
btn: Any
btnA: Any
btnB: Any
btnC: Any

def btnText() -> None: ...
def const() -> None: ...

display: Any

def get_sd_state() -> None: ...
def hwDeinit() -> None: ...

lcd: Any
m5base: Any
machine: Any
node_id: str
os: Any
power: Any
rgb: Any

def sd_mount() -> None: ...
def sd_umount() -> None: ...

speaker: Any
timEx: Any
timeSchedule: Any
time_ex: Any
timerSch: Any
