from typing import Any

ONE_SHOT: int
PERIODIC: int

class Timer:
    ONE_SHOT: int
    PERIODIC: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def setCallback(self, *argv) -> Any: ...
    def start(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

machine: Any
time: Any

class timeSch:
    ONE_SHOT: int
    PERIODIC: int
    def checkInit(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def event(self, *argv) -> Any: ...
    def remove_all(self, *argv) -> Any: ...
    def run(self, *argv) -> Any: ...
    def setTimer(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...
    def timerCb(self, *argv) -> Any: ...
