
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Unit: ...
def const() -> None: ...
def deinit() -> None: ...
def get() -> None: ...
def portApply() -> None: ...
def portFree() -> None: ...
