from typing import Any

Node = Any

def _chr_addr() -> None: ...
def get_ch() -> None: ...
def height() -> None: ...
def hmap() -> None: ...
def max_ch() -> None: ...
def max_width() -> None: ...
def min_ch() -> None: ...
def monospaced() -> None: ...
def reverse() -> None: ...
