from typing import Any

def block_sleep(*args) -> Any: ...
def gmtime(*args) -> Any: ...
def localtime(*args) -> Any: ...
def mktime(*args) -> Any: ...
def sleep(*args) -> Any: ...
def sleep_ms(*args) -> Any: ...
def sleep_us(*args) -> Any: ...
def strftime(*args) -> Any: ...
def ticks_add(*args) -> Any: ...
def ticks_base(*args) -> Any: ...
def ticks_cpu(*args) -> Any: ...
def ticks_diff(*args) -> Any: ...
def ticks_ms(*args) -> Any: ...
def ticks_us(*args) -> Any: ...
def tickscpu_diff(*args) -> Any: ...
def time(*args) -> Any: ...
