from typing import Any

Node = Any

def block_sleep() -> None: ...
def gmtime() -> None: ...
def localtime() -> None: ...
def mktime() -> None: ...
def sleep() -> None: ...
def sleep_ms() -> None: ...
def sleep_us() -> None: ...
def strftime() -> None: ...
def ticks_add() -> None: ...
def ticks_base() -> None: ...
def ticks_cpu() -> None: ...
def ticks_diff() -> None: ...
def ticks_ms() -> None: ...
def ticks_us() -> None: ...
def tickscpu_diff() -> None: ...
def time() -> None: ...
