from typing import Any

class Writer:
    def _newline(self, *args) -> Any: ...
    def _printchar(self, *args) -> Any: ...
    def _printchar_bitwise(self, *args) -> Any: ...
    col_clip: Any
    def printstring(self, *args) -> Any: ...
    row_clip: Any
    def set_clip(self, *args) -> Any: ...
    def set_textpos(self, *args) -> Any: ...
    text_col: int
    text_row: int

framebuf: Any
