"""
Module: 'time' on micropython-v1.24.0-preview-esp32-ESP32_GENERIC_C3
"""

# MCU: {'version': '1.24.0-preview', 'mpy': 'v6.3', 'port': 'esp32', 'board': 'ESP32_GENERIC_C3', 'family': 'micropython', 'build': 'preview.66.gf60c71d13', 'arch': '', 'ver': '1.24.0-preview-preview.66.gf60c71d13', 'cpu': 'ESP32C3'}
# Stubber: v1.20.0
from __future__ import annotations
from _typeshed import Incomplete

def ticks_diff(*args, **kwargs) -> Incomplete: ...
def ticks_add(*args, **kwargs) -> Incomplete: ...
def ticks_cpu(*args, **kwargs) -> Incomplete: ...
def time(*args, **kwargs) -> Incomplete: ...
def ticks_ms(*args, **kwargs) -> Incomplete: ...
def ticks_us(*args, **kwargs) -> Incomplete: ...
def time_ns(*args, **kwargs) -> Incomplete: ...
def localtime(*args, **kwargs) -> Incomplete: ...
def sleep_us(*args, **kwargs) -> Incomplete: ...
def gmtime(*args, **kwargs) -> Incomplete: ...
def sleep_ms(*args, **kwargs) -> Incomplete: ...
def mktime(*args, **kwargs) -> Incomplete: ...
def sleep(*args, **kwargs) -> Incomplete: ...
