from typing import Any

def debug(*args) -> Any: ...
def getLogger(*args) -> Any: ...
def info(*args) -> Any: ...
def basicConfig(*args) -> Any: ...

INFO: int
CRITICAL: int
ERROR: int
WARNING: int
DEBUG: int
NOTSET: int

class Logger:
    def __init__(self, *args) -> None: ...
    def debug(self, *args) -> Any: ...
    def log(self, *args) -> Any: ...
    def exception(self, *args) -> Any: ...
    def info(self, *args) -> Any: ...
    def error(self, *args) -> Any: ...
    def warning(self, *args) -> Any: ...
    level: int
    def setLevel(self, *args) -> Any: ...
    def isEnabledFor(self, *args) -> Any: ...
    def critical(self, *args) -> Any: ...
