from typing import Any

def pininfo(*args, **kwargs) -> Any: ...

class Flash:
    def ioctl(self, *args, **kwargs) -> Any: ...
    def writeblocks(self, *args, **kwargs) -> Any: ...
    def readblocks(self, *args, **kwargs) -> Any: ...
    def flash_init(self, *args, **kwargs) -> Any: ...
    def flash_version(self, *args, **kwargs) -> Any: ...
    def flash_size(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
