"""
Module: 'os.path' on micropython-v1.24.1-webassembly
"""

# MCU: {'family': 'micropython', 'version': '1.24.1', 'build': '', 'ver': '1.24.1', 'port': 'webassembly', 'board': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.24.0
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

sep: str = "/"

def isdir(*args, **kwargs) -> Incomplete: ...
def exists(*args, **kwargs) -> Incomplete: ...
def expanduser(*args, **kwargs) -> Incomplete: ...
def normcase(*args, **kwargs) -> Incomplete: ...
def isfile(*args, **kwargs) -> Incomplete: ...
def lexists(*args, **kwargs) -> Incomplete: ...
def normpath(*args, **kwargs) -> Incomplete: ...
def split(*args, **kwargs) -> Incomplete: ...
def dirname(*args, **kwargs) -> Incomplete: ...
def join(*args, **kwargs) -> Incomplete: ...
def basename(*args, **kwargs) -> Incomplete: ...
def abspath(*args, **kwargs) -> Incomplete: ...
