from collections.abc import Generator
from typing import Any

type_gen: Any
DEBUG: int
log: Any

def set_debug(val) -> None: ...

class CancelledError(Exception): ...
class TimeoutError(CancelledError): ...

class EventLoop:
    runq: Any
    waitq: Any
    cur_task: Any
    def __init__(self, runq_len: int = ..., waitq_len: int = ...) -> None: ...
    def time(self): ...
    def create_task(self, coro) -> None: ...
    def call_soon(self, callback, *args) -> None: ...
    def call_later(self, delay, callback, *args) -> None: ...
    def call_later_ms(self, delay, callback, *args): ...
    def call_at_(self, time, callback, args=...) -> None: ...
    def wait(self, delay) -> None: ...
    def run_forever(self): ...
    def run_until_complete(self, coro) -> Generator[None, None, None]: ...
    def stop(self) -> Generator[Any, None, Any]: ...
    def close(self) -> None: ...

class SysCall:
    args: Any
    def __init__(self, *args) -> None: ...
    def handle(self) -> None: ...

class SysCall1(SysCall):
    arg: Any
    def __init__(self, arg) -> None: ...

class StopLoop(SysCall1): ...
class IORead(SysCall1): ...
class IOWrite(SysCall1): ...
class IOReadDone(SysCall1): ...
class IOWriteDone(SysCall1): ...

_event_loop: Any
_event_loop_class = EventLoop

def get_event_loop(runq_len: int = ..., waitq_len: int = ...): ...
def sleep(secs) -> Generator[Any, None, None]: ...

class SleepMs(SysCall1):
    v: Any
    arg: Any
    def __init__(self) -> None: ...
    def __call__(self, arg): ...
    def __iter__(self): ...
    def __next__(self): ...

_stop_iter: Any
sleep_ms: Any

def cancel(coro) -> None: ...

class TimeoutObj:
    coro: Any
    def __init__(self, coro) -> None: ...

def wait_for_ms(coro, timeout): ...
def wait_for(coro, timeout): ...
def coroutine(f): ...
def ensure_future(coro, loop=...): ...
def Task(coro, loop=...) -> None: ...
