from . import core as core
from _typeshed import Incomplete
from collections.abc import Generator

class Event:
    state: bool
    waiting: Incomplete
    def __init__(self) -> None: ...
    def is_set(self): ...
    def set(self) -> None: ...
    def clear(self) -> None: ...
    async def wait(self) -> Generator[None, None, Incomplete]: ...
