"""
Module: 'ubinascii' on micropython-v1.24.1-esp32-ESP32_GENERIC
"""

# MCU: {'family': 'micropython', 'version': '1.24.1', 'build': '', 'ver': '1.24.1', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'cpu': 'ESP32', 'mpy': 'v6.3', 'arch': 'xtensawin'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def crc32(*args, **kwargs) -> Incomplete: ...
def hexlify(*args, **kwargs) -> Incomplete: ...
def unhexlify(*args, **kwargs) -> Incomplete: ...
def b2a_base64(*args, **kwargs) -> Incomplete: ...
def a2b_base64(*args, **kwargs) -> Incomplete: ...
