from typing import Any

CRITICAL: int
ERROR: int
WARNING: int
INFO: int
DEBUG: int
NOTSET: int
_level_dict: Any
_stream: Any

class Logger:
    level: Any
    name: Any
    def __init__(self, name) -> None: ...
    def _level_str(self, level): ...
    def setLevel(self, level) -> None: ...
    def isEnabledFor(self, level): ...
    def log(self, level, msg, *args) -> None: ...
    def debug(self, msg, *args) -> None: ...
    def info(self, msg, *args) -> None: ...
    def warning(self, msg, *args) -> None: ...
    def error(self, msg, *args) -> None: ...
    def critical(self, msg, *args) -> None: ...
    def exc(self, e, msg, *args) -> None: ...
    def exception(self, msg, *args) -> None: ...
_level = INFO
_loggers: Any

def getLogger(name): ...
def info(msg, *args) -> None: ...
def debug(msg, *args) -> None: ...
def basicConfig(level=..., filename: Any | None = ..., stream: Any | None = ..., format: Any | None = ...) -> None: ...
