from _typeshed import Incomplete

_CMD_TIMEOUT: Incomplete
_R1_IDLE_STATE: Incomplete
_R1_ILLEGAL_COMMAND: Incomplete
_TOKEN_CMD25: Incomplete
_TOKEN_STOP_TRAN: Incomplete
_TOKEN_DATA: Incomplete

class SDCard:
    spi: Incomplete
    cs: Incomplete
    cmdbuf: Incomplete
    dummybuf: Incomplete
    tokenbuf: Incomplete
    dummybuf_memoryview: Incomplete
    def __init__(self, spi, cs, baudrate: int = ...) -> None: ...
    def init_spi(self, baudrate) -> None: ...
    sectors: Incomplete
    def init_card(self, baudrate) -> None: ...
    cdv: int
    def init_card_v1(self) -> None: ...
    def init_card_v2(self) -> None: ...
    def cmd(self, cmd, arg, crc, final: int = ..., release: bool = ..., skip1: bool = ...): ...
    def readinto(self, buf) -> None: ...
    def write(self, token, buf) -> None: ...
    def write_token(self, token) -> None: ...
    def readblocks(self, block_num, buf) -> None: ...
    def writeblocks(self, block_num, buf) -> None: ...
    def ioctl(self, op, arg): ...
