
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Bmm150:
    def available() -> None: ...
    def readData() -> None: ...
    def readID() -> None: ...
    def setPowerControlBit() -> None: ...
    def setSleepMode() -> None: ...
    def set_normal_mode() -> None: ...
    def set_op_mode() -> None: ...
    def set_sleep_mode() -> None: ...
def const() -> None: ...
