class Chunk:
    def close() -> None: ...
    def getname() -> None: ...
    def getsize() -> None: ...
    def isatty() -> None: ...
    def read() -> None: ...
    def seek() -> None: ...
    def skip() -> None: ...
    def tell() -> None: ...
