
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class MState:
    def end() -> None: ...
    def loop() -> None: ...
    def start() -> None: ...
class MStateManager:
    def change() -> None: ...
    def nextState() -> None: ...
    def register() -> None: ...
    def run() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...
    def unregister() -> None: ...
