from _typeshed import Incomplete

class NeoPixel:
    ORDER: Incomplete
    pin: Incomplete
    n: Incomplete
    bpp: Incomplete
    buf: Incomplete
    def __init__(self, pin, n, bpp: int = ...) -> None: ...
    def __setitem__(self, index, val) -> None: ...
    def __getitem__(self, index): ...
    def fill(self, color) -> None: ...
    def write(self) -> None: ...
