from typing import Any

class LockType:
    def acquire(self, *args) -> Any: ...
    def locked(self, *args) -> Any: ...
    def release(self, *args) -> Any: ...

def allocate_lock(*args) -> Any: ...
def exit(*args) -> Any: ...
def get_ident(*args) -> Any: ...
def stack_size(*args) -> Any: ...
def start_new_thread(*args) -> Any: ...
