
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class DHT11:
    def humidity() -> None: ...
    def measure() -> None: ...
    def temperature() -> None: ...
class DHT22:
    def humidity() -> None: ...
    def measure() -> None: ...
    def temperature() -> None: ...
class DHTBase:
    def measure() -> None: ...
def dht_readinto() -> None: ...
