from typing import Any

def const(*args) -> Any: ...

class DS18X20:
    def __init__(self, *args) -> None: ...
    def scan(self, *args) -> Any: ...
    def convert_temp(self, *args) -> Any: ...
    def read_scratch(self, *args) -> Any: ...
    def write_scratch(self, *args) -> Any: ...
    def read_temp(self, *args) -> Any: ...
