
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def choice() -> None: ...
def getrandbits() -> None: ...
def randint() -> None: ...
def random() -> None: ...
def randrange() -> None: ...
def seed() -> None: ...
def uniform() -> None: ...
