
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class sha1:
    def digest() -> None: ...
    def update() -> None: ...
class sha256:
    def digest() -> None: ...
    def update() -> None: ...
