
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class FileSection:
    def read() -> None: ...
    def readinto() -> None: ...
    def skip() -> None: ...
class TarFile:
    def extractfile() -> None: ...
    def next() -> None: ...
class TarInfo: ...
def roundup() -> None: ...
