from _espnow import *
from _typeshed import Incomplete

class ESPNow(ESPNowBase):
    _data: Incomplete
    _none_tuple: Incomplete
    _poll: Incomplete
    def __init__(self) -> None: ...
    def irecv(self, timeout_ms: Incomplete | None = ...): ...
    def recv(self, timeout_ms: Incomplete | None = ...): ...
    def __iter__(self): ...
    def __next__(self): ...
    def any(self): ...
