from typing import Any

class Align:
    BOTTOM: int
    BOTTOM_LEFT: int
    BOTTOM_RIGHT: int
    CENTER: int
    LEFT: int
    RIGHT: int
    TOP: int
    TOP_LEFT: int
    TOP_RIGHT: int

class Display:
    _font_height: int
    def _next_line(self, *argv) -> Any: ...
    def _reset_text_history(self, *argv) -> Any: ...
    _valid_devices: Any
    def clear(self, *argv) -> Any: ...
    def image(self, *argv) -> Any: ...
    def text(self, *argv) -> Any: ...

class Ev3devDisplay:
    def image(self, *argv) -> Any: ...
    def reset_screen(self, *argv) -> Any: ...
    def scroll(self, *argv) -> Any: ...
    def text_grid(self, *argv) -> Any: ...
    def text_pixels(self, *argv) -> Any: ...

class ImageFile: ...

path: Any
