from typing import Any

class Display:
    _font_height: int
    def _next_line() -> None: ...
    def _reset_text_history() -> None: ...
    _valid_devices: Any
    def clear() -> None: ...
    def image() -> None: ...
    def text() -> None: ...

class Speaker:
    _valid_devices: Any
    def beep() -> None: ...
    def beeps() -> None: ...
    def file() -> None: ...
    def speech() -> None: ...
    def tune() -> None: ...

battery: Any

def buttons() -> None: ...

display: Any

def exit() -> None: ...
def light() -> None: ...

sound: Any
stderr: Any
