from typing import Any

class Ev3devSpeaker:
    def _beep(self, *argv) -> Any: ...
    def _play_tone(self, *argv) -> Any: ...
    def _stop(self, *argv) -> Any: ...
    def play_file(self, *argv) -> Any: ...
    def play_note(self, *argv) -> Any: ...
    def play_tone(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...

class SoundFile:
    def _cancel_token(self, *argv) -> Any: ...
    _read: Any
    def close(self, *argv) -> Any: ...

class Speaker:
    _valid_devices: Any
    def beep(self, *argv) -> Any: ...
    def beeps(self, *argv) -> Any: ...
    def file(self, *argv) -> Any: ...
    def speech(self, *argv) -> Any: ...
    def tune(self, *argv) -> Any: ...

path: Any

def wait() -> None: ...
