"""
Module: 'aioble.security' on micropython-v1.28.0-rp2-ARDUINO_NANO_RP2040_CONNECT
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.28.0', 'arch': 'armv6m', 'version': '1.28.0', 'port': 'rp2', 'board': 'ARDUINO_NANO_RP2040_CONNECT', 'family': 'micropython', 'board_id': 'ARDUINO_NANO_RP2040_CONNECT', 'variant': '', 'cpu': 'RP2040'}
# Stubber: v1.28.1
from __future__ import annotations
from typing import Final, Generator
from _typeshed import Incomplete

_modified: bool = False
_DEFAULT_PATH: Final[str] = "ble_secrets.json"
_secrets: dict = {}

def _security_irq(*args, **kwargs) -> Incomplete: ...
def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def _security_shutdown(*args, **kwargs) -> Incomplete: ...
def log_warn(*args, **kwargs) -> Incomplete: ...
def log_info(*args, **kwargs) -> Incomplete: ...
def load_secrets(*args, **kwargs) -> Incomplete: ...
def schedule(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...
def _save_secrets(*args, **kwargs) -> Incomplete: ...

_path: Incomplete  ## <class 'NoneType'> = None

def pair(*args, **kwargs) -> Generator:  ## = <generator>
    ...

class DeviceConnection:
    _connected: dict = {}
    def is_connected(self, *args, **kwargs) -> Incomplete: ...
    def _run_task(self, *args, **kwargs) -> Incomplete: ...
    def services(self, *args, **kwargs) -> Incomplete: ...
    def timeout(self, *args, **kwargs) -> Incomplete: ...
    def l2cap_connect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def l2cap_accept(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def pair(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def service(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def disconnect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def device_task(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def disconnected(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def exchange_mtu(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

ble: Incomplete  ## <class 'BLE'> = <BLE>
