""" """

from __future__ import annotations
from _typeshed import Incomplete
from typing import Callable, List
from typing_extensions import TypeVar, TypeAlias, Awaitable

class bool:
    def __init__(self) -> None: ...

class bytearray:
    """
    |see_cpython| `python:bytearray`.
    """
    def __init__(self) -> None: ...

class bytes:
    """
    |see_cpython| `python:bytes`.
    """
    def __init__(self) -> None: ...
    def decode(self, encoding="utf-8", errors="strict") -> Incomplete:
        """
        Decode the bytes object to a string using the specified *encoding*.

        MicroPython supports the following encodings:

        - ``'utf-8'`` or ``'utf8'`` - UTF-8 encoding (default)
        - ``'ascii'`` - ASCII encoding (subset of UTF-8)

        The *errors* parameter controls how decoding errors are handled:

        - ``'strict'`` - Raise a ``UnicodeError`` on invalid UTF-8 (default)
        - ``'ignore'`` - Skip invalid bytes (requires ``MICROPY_PY_BUILTINS_BYTES_DECODE_ERRORS``)
        - ``'replace'`` - Replace invalid bytes with U+FFFD '�' (requires ``MICROPY_PY_BUILTINS_BYTES_DECODE_ERRORS``)

        .. note::
            Error handler support depends on build configuration. On constrained
            systems, only ``'strict'`` mode may be available.

        Example::

            >>> b'\xc2\xa9 2024'.decode('utf-8')  # © symbol
            '© 2024'
            >>> b'hello\xffworld'.decode('utf-8', 'ignore')  # Skip invalid bytes
            'helloworld'

        Raises ``LookupError`` if the encoding is not supported, or
        ``UnicodeError`` if the data contains invalid UTF-8 and ``errors='strict'``.
        """
        ...

class complex:
    def __init__(self) -> None: ...

class dict:
    def __init__(self) -> None: ...

class float:
    def __init__(self) -> None: ...

class frozenset:
    def __init__(self) -> None: ...

class int:
    def __init__(self) -> None: ...
    @classmethod
    def from_bytes(cls, bytes, byteorder) -> Incomplete:
        """
        In MicroPython, `byteorder` parameter must be positional (this is
        compatible with CPython).
        """
        ...
    def to_bytes(self, size, byteorder, /, *, signed=False) -> Incomplete:
        """
        In MicroPython, `byteorder` parameter must be positional (this is
        compatible with CPython).
        """
        ...

class list:
    def __init__(self) -> None: ...

class memoryview:
    """
    |see_cpython| `python:memoryview`.
    """
    def __init__(self) -> None: ...

class object:
    def __init__(self) -> None: ...

class set:
    def __init__(self) -> None: ...

class slice:
    """
    The *slice* builtin is the type that slice objects have.
    """
    def __init__(self) -> None: ...

class str:
    def __init__(self) -> None: ...
    def encode(self, encoding="utf-8") -> Incomplete:
        """
        Encode the string to bytes using the specified *encoding*.

        MicroPython supports the following encodings:

        - ``'utf-8'`` or ``'utf8'`` - UTF-8 encoding (default)
        - ``'ascii'`` - ASCII encoding (subset of UTF-8)

        Example::

            >>> '© 2024'.encode('utf-8')  # Copyright symbol
            b'\xc2\xa9 2024'

        Raises ``LookupError`` if the encoding is not supported.
        """
        ...
    def center(self, width) -> int:
        """
        Return a centered string of length *width*. Padding is done using spaces.

        When Unicode support is enabled (``MICROPY_PY_BUILTINS_STR_UNICODE``), this
        method counts Unicode characters rather than bytes, ensuring proper alignment
        for multi-byte UTF-8 characters.

        Example::

            >>> 'café'.center(10)  # é is 2 bytes in UTF-8
            '   café   '
        """
        ...

class tuple:
    def __init__(self) -> None: ...

class AssertionError(Exception): ...
class AttributeError(Exception): ...
class ImportError(Exception): ...
class IndexError(Exception): ...
class KeyboardInterrupt(Exception): ...
class KeyError(Exception): ...
class MemoryError(Exception): ...
class NameError(Exception): ...
class NotImplementedError(Exception): ...
class OSError(Exception): ...
class RuntimeError(Exception): ...
class StopIteration(Exception): ...
class SyntaxError(Exception): ...
class SystemExit(Exception): ...
class TypeError(Exception): ...
class ValueError(Exception): ...
class ZeroDivisionError(Exception): ...

def abs() -> Incomplete: ...
def all() -> Incomplete: ...
def any() -> Incomplete: ...
def bin() -> Incomplete: ...
def callable() -> TypeIs[Callable[..., object]]: ...
def chr() -> Incomplete: ...
def compile() -> Incomplete: ...
def delattr(obj, name) -> Incomplete:
    """
    The argument *name* should be a string, and this function deletes the named
    attribute from the object given by *obj*.
    """
    ...

def dir() -> List[str]: ...
def divmod() -> Incomplete: ...
def enumerate() -> Incomplete: ...
def eval() -> Incomplete: ...
def exec() -> Incomplete: ...
def filter() -> Incomplete: ...
def getattr() -> Incomplete: ...
def globals() -> Incomplete: ...
def hasattr() -> bool: ...
def hash() -> Incomplete: ...
def hex() -> Incomplete: ...
def id() -> Incomplete: ...
def input() -> Incomplete: ...
def isinstance() -> Incomplete: ...
def issubclass() -> Incomplete: ...
def iter() -> Incomplete: ...
def len() -> Incomplete: ...
def locals() -> Incomplete: ...
def map() -> Incomplete: ...
def max() -> Incomplete: ...
def min() -> Incomplete: ...
def next() -> Incomplete: ...
def oct() -> Incomplete: ...
def open() -> Incomplete: ...
def ord() -> Incomplete: ...
def pow() -> Incomplete: ...
def print() -> Incomplete: ...
def property() -> Incomplete: ...
def range() -> Incomplete: ...
def repr() -> Incomplete: ...
def reversed() -> Incomplete: ...
def round() -> Incomplete: ...
def setattr() -> Incomplete: ...
def sorted() -> Incomplete: ...
def sum() -> Incomplete: ...
def super() -> Incomplete: ...
def type() -> Incomplete: ...
def zip() -> Incomplete: ...
