"""
Module: 'argparse' on micropython-v1.26.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.26.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.26.0'}
# Stubber: v1.26.0
from __future__ import annotations
from _typeshed import Incomplete

def _dest_from_optnames(*args, **kwargs) -> Incomplete: ...
def namedtuple(*args, **kwargs) -> Incomplete: ...

class _Arg:
    def parse(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ArgumentParser:
    def _parse_args_impl(self, *args, **kwargs) -> Incomplete: ...
    def _parse_args(self, *args, **kwargs) -> Incomplete: ...
    def parse_known_args(self, *args, **kwargs) -> Incomplete: ...
    def add_argument(self, *args, **kwargs) -> Incomplete: ...
    def parse_args(self, *args, **kwargs) -> Incomplete: ...
    def usage(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class _ArgError(Exception): ...
