from typing import Any

KEY_LEN: int
MAX_DATA_LEN: int
MAX_ENCRYPT_PEER_NUM: int
MAX_TOTAL_PEER_NUM: int
ADDR_LEN: int

class ESPNow:
    def peer_count(self, *args, **kwargs) -> Any: ...
    def recv(self, *args, **kwargs) -> Any: ...
    def mod_peer(self, *args, **kwargs) -> Any: ...
    def get_peers(self, *args, **kwargs) -> Any: ...
    def stats(self, *args, **kwargs) -> Any: ...
    def recvinto(self, *args, **kwargs) -> Any: ...
    def set_pmk(self, *args, **kwargs) -> Any: ...
    def irecv(self, *args, **kwargs) -> Any: ...
    def get_peer(self, *args, **kwargs) -> Any: ...
    def active(self, *args, **kwargs) -> Any: ...
    def send(self, *args, **kwargs) -> Any: ...
    def any(self, *args, **kwargs) -> Any: ...
    def del_peer(self, *args, **kwargs) -> Any: ...
    def add_peer(self, *args, **kwargs) -> Any: ...
    def config(self, *args, **kwargs) -> Any: ...
    irq: Any
    def __init__(self, *argv, **kwargs) -> None: ...

class ESPNowBase:
    def irq(self, *args, **kwargs) -> Any: ...
    def mod_peer(self, *args, **kwargs) -> Any: ...
    def get_peers(self, *args, **kwargs) -> Any: ...
    def stats(self, *args, **kwargs) -> Any: ...
    def set_pmk(self, *args, **kwargs) -> Any: ...
    def peer_count(self, *args, **kwargs) -> Any: ...
    def recvinto(self, *args, **kwargs) -> Any: ...
    def send(self, *args, **kwargs) -> Any: ...
    def active(self, *args, **kwargs) -> Any: ...
    def any(self, *args, **kwargs) -> Any: ...
    def get_peer(self, *args, **kwargs) -> Any: ...
    def del_peer(self, *args, **kwargs) -> Any: ...
    def add_peer(self, *args, **kwargs) -> Any: ...
    def config(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
