from typing import Any

class DS18X20:
    def convert_temp(self, *args) -> Any: ...
    def read_scratch(self, *args) -> Any: ...
    def read_temp(self, *args) -> Any: ...
    def scan(self, *args) -> Any: ...
    def write_scratch(self, *args) -> Any: ...

def const(*args) -> Any: ...
