from typing import Any

SET_CHARGE_PUMP: int
SET_COL_ADDR: int
SET_COM_OUT_DIR: int
SET_COM_PIN_CFG: int
SET_CONTRAST: int
SET_DISP: int
SET_DISP_CLK_DIV: int
SET_DISP_OFFSET: int
SET_DISP_START_LINE: int
SET_ENTIRE_ON: int
SET_MEM_ADDR: int
SET_MUX_RATIO: int
SET_NORM_INV: int
SET_PAGE_ADDR: int
SET_PRECHARGE: int
SET_SEG_REMAP: int
SET_VCOM_DESEL: int

class SSD1306:
    def blit(self, *args) -> Any: ...
    def contrast(self, *args) -> Any: ...
    def fill(self, *args) -> Any: ...
    def fill_rect(self, *args) -> Any: ...
    def hline(self, *args) -> Any: ...
    def init_display(self, *args) -> Any: ...
    def invert(self, *args) -> Any: ...
    def line(self, *args) -> Any: ...
    def pixel(self, *args) -> Any: ...
    def poweroff(self, *args) -> Any: ...
    def poweron(self, *args) -> Any: ...
    def rect(self, *args) -> Any: ...
    def scroll(self, *args) -> Any: ...
    def show(self, *args) -> Any: ...
    def text(self, *args) -> Any: ...
    def vline(self, *args) -> Any: ...

class SSD1306_I2C:
    def blit(self, *args) -> Any: ...
