"""
Module: 'asyncio.stream' on micropython-v1.28.0-rp2-RPI_PICO2_W
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.28.0', 'arch': 'armv7emsp', 'version': '1.28.0', 'port': 'rp2', 'board': 'RPI_PICO2_W', 'family': 'micropython', 'board_id': 'RPI_PICO2_W', 'variant': '', 'cpu': 'RP2350'}
# Stubber: v1.28.0
from __future__ import annotations
from typing import Generator
from _typeshed import Incomplete

def stream_awrite(*args, **kwargs) -> Generator:  ## = <generator>
    ...
def open_connection(*args, **kwargs) -> Generator:  ## = <generator>
    ...
def start_server(*args, **kwargs) -> Generator:  ## = <generator>
    ...

class StreamWriter:
    def write(self, *args, **kwargs) -> Incomplete: ...
    def get_extra_info(self, *args, **kwargs) -> Incomplete: ...
    def close(self, *args, **kwargs) -> Incomplete: ...
    def awritestr(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def wait_closed(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def drain(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readexactly(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readinto(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def read(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def awrite(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readline(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def aclose(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Server:
    def close(self, *args, **kwargs) -> Incomplete: ...
    def wait_closed(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def _serve(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Stream:
    def write(self, *args, **kwargs) -> Incomplete: ...
    def get_extra_info(self, *args, **kwargs) -> Incomplete: ...
    def close(self, *args, **kwargs) -> Incomplete: ...
    def awritestr(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def wait_closed(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def drain(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readexactly(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readinto(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def read(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def awrite(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readline(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def aclose(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

class StreamReader:
    def write(self, *args, **kwargs) -> Incomplete: ...
    def get_extra_info(self, *args, **kwargs) -> Incomplete: ...
    def close(self, *args, **kwargs) -> Incomplete: ...
    def awritestr(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def wait_closed(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def drain(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readexactly(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readinto(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def read(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def awrite(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def readline(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def aclose(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...
