from ssd1306 import SSD1306_I2C
from typing import Any

class OLED(SSD1306_I2C):
    _reset: Any
    def __init__(self, i2c, reset) -> None: ...
    def reset(self, reinit: bool = ...) -> None: ...
    def test(self) -> None: ...
    def display_wifi(self) -> None: ...
