"""
Module: 'gc' on micropython-v1.29.0-preview-esp32-ESP32_GENERIC_C6
"""

# MCU: {'variant': '', 'build': 'preview.657.gf013bb5195', 'arch': 'rv32imc', 'port': 'esp32', 'board': 'ESP32_GENERIC_C6', 'board_id': 'ESP32_GENERIC_C6', 'mpy': 'v6.3', 'ver': '1.29.0-preview-preview.657.gf013bb5195', 'family': 'micropython', 'cpu': 'ESP32-C6', 'version': '1.29.0-preview'}
# Stubber: v1.28.3
from __future__ import annotations

from _typeshed import Incomplete

def mem_alloc(*args, **kwargs) -> Incomplete: ...
def isenabled(*args, **kwargs) -> Incomplete: ...
def mem_free(*args, **kwargs) -> Incomplete: ...
def threshold(*args, **kwargs) -> Incomplete: ...
def collect(*args, **kwargs) -> Incomplete: ...
def enable(*args, **kwargs) -> Incomplete: ...
def disable(*args, **kwargs) -> Incomplete: ...
