from typing import Any

Node = Any

class ULP:
    def load_binary() -> None: ...
    def run() -> None: ...
    def set_wakeup_period() -> None: ...

def hall_sensor() -> None: ...
def raw_temperature() -> None: ...
def wake_on_ext0() -> None: ...
def wake_on_ext1() -> None: ...
def wake_on_touch() -> None: ...
