from typing import Any

class ULP:
    RESERVE_MEM: int
    def load_binary(self, *args) -> Any: ...
    def run(self, *args) -> Any: ...
    def set_wakeup_period(self, *args) -> Any: ...

WAKEUP_ALL_LOW: bool
WAKEUP_ANY_HIGH: bool

def hall_sensor(*args) -> Any: ...
def raw_temperature(*args) -> Any: ...
def wake_on_ext0(*args) -> Any: ...
def wake_on_ext1(*args) -> Any: ...
def wake_on_touch(*args) -> Any: ...
