from typing import Any

def acos(*args) -> Any: ...
def acosh(*args) -> Any: ...
def asin(*args) -> Any: ...
def asinh(*args) -> Any: ...
def atan(*args) -> Any: ...
def atan2(*args) -> Any: ...
def atanh(*args) -> Any: ...
def ceil(*args) -> Any: ...
def copysign(*args) -> Any: ...
def cos(*args) -> Any: ...
def cosh(*args) -> Any: ...
def degrees(*args) -> Any: ...

e: float

def erf(*args) -> Any: ...
def erfc(*args) -> Any: ...
def exp(*args) -> Any: ...
def expm1(*args) -> Any: ...
def fabs(*args) -> Any: ...
def floor(*args) -> Any: ...
def fmod(*args) -> Any: ...
def frexp(*args) -> Any: ...
def gamma(*args) -> Any: ...
def isfinite(*args) -> Any: ...
def isinf(*args) -> Any: ...
def isnan(*args) -> Any: ...
def ldexp(*args) -> Any: ...
def lgamma(*args) -> Any: ...
def log(*args) -> Any: ...
def log10(*args) -> Any: ...
def log2(*args) -> Any: ...
def modf(*args) -> Any: ...

pi: float

def pow(*args) -> Any: ...
def radians(*args) -> Any: ...
def sin(*args) -> Any: ...
def sinh(*args) -> Any: ...
def sqrt(*args) -> Any: ...
def tan(*args) -> Any: ...
def tanh(*args) -> Any: ...
def trunc(*args) -> Any: ...
