from typing import Any

class sha1:
    def digest(self, *args) -> Any: ...
    def update(self, *args) -> Any: ...

class sha256:
    def digest(self, *args) -> Any: ...
    def update(self, *args) -> Any: ...
