"""
Module: 'gc' on micropython-v1.26.0-rp2-PIMORONI_PICOLIPO-FLASH_16M
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.26.0', 'arch': 'armv6m', 'version': '1.26.0', 'port': 'rp2', 'board': 'PIMORONI_PICOLIPO', 'family': 'micropython', 'board_id': 'PIMORONI_PICOLIPO-FLASH_16M', 'variant': 'FLASH_16M', 'cpu': 'RP2040'}
# Stubber: v1.25.1
from __future__ import annotations
from _typeshed import Incomplete

def mem_alloc(*args, **kwargs) -> Incomplete: ...
def isenabled(*args, **kwargs) -> Incomplete: ...
def mem_free(*args, **kwargs) -> Incomplete: ...
def threshold(*args, **kwargs) -> Incomplete: ...
def collect(*args, **kwargs) -> Incomplete: ...
def enable(*args, **kwargs) -> Incomplete: ...
def disable(*args, **kwargs) -> Incomplete: ...
