"""
Module: 'ubinascii' on micropython-v1.26.0-rp2-PIMORONI_PICOLIPO-FLASH_16M
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.26.0', 'arch': 'armv6m', 'version': '1.26.0', 'port': 'rp2', 'board': 'PIMORONI_PICOLIPO', 'family': 'micropython', 'board_id': 'PIMORONI_PICOLIPO-FLASH_16M', 'variant': 'FLASH_16M', 'cpu': 'RP2040'}
# Stubber: v1.25.1
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

def crc32(*args, **kwargs) -> Incomplete: ...
def hexlify(*args, **kwargs) -> Incomplete: ...
def unhexlify(*args, **kwargs) -> Incomplete: ...
def b2a_base64(*args, **kwargs) -> Incomplete: ...
def a2b_base64(*args, **kwargs) -> Incomplete: ...
