"""
Module: 'struct' on micropython-v1.24.1-rp2-RPI_PICO2
"""

# MCU: {'family': 'micropython', 'version': '1.24.1', 'build': '', 'ver': '1.24.1', 'port': 'rp2', 'board': 'RPI_PICO2', 'cpu': 'RP2350', 'mpy': 'v6.3', 'arch': 'armv7emsp'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def pack_into(*args, **kwargs) -> Incomplete: ...
def unpack(*args, **kwargs) -> Incomplete: ...
def unpack_from(*args, **kwargs) -> Incomplete: ...
def pack(*args, **kwargs) -> Incomplete: ...
def calcsize(*args, **kwargs) -> Incomplete: ...
