from typing import Any

AP_IF: int
STA_IF: int

class WLAN:
    def __init__(self, *argv, **kwargs) -> None: ...
    OPEN: int
    WEP: int
    WPA_PSK: int
    def active(self, *args, **kwargs) -> Any: ...
    def config(self, *args, **kwargs) -> Any: ...
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def ifconfig(self, *args, **kwargs) -> Any: ...
    def isconnected(self, *args, **kwargs) -> Any: ...
    def scan(self, *args, **kwargs) -> Any: ...
    def status(self, *args, **kwargs) -> Any: ...

def route(*args, **kwargs) -> Any: ...
