from typing import Any

Node = Any

class FrameBuffer:
    def blit() -> None: ...
    def fill() -> None: ...
    def fill_rect() -> None: ...
    def hline() -> None: ...
    def line() -> None: ...
    def pixel() -> None: ...
    def rect() -> None: ...
    def scroll() -> None: ...
    def text() -> None: ...
    def vline() -> None: ...

def FrameBuffer1() -> None: ...
