from typing import Any

Node = Any

def atcmd() -> None: ...
def checkSMS() -> None: ...
def connect() -> None: ...
def debug() -> None: ...
def deleteSMS() -> None: ...
def disconnect() -> None: ...
def readSMS() -> None: ...
def sendSMS() -> None: ...
def sms_cb() -> None: ...
def start() -> None: ...
def status() -> None: ...
def stop() -> None: ...
