from typing import Any

Node = Any

class MicroWebTemplate:
    def Execute() -> None: ...
    def Validate() -> None: ...
    def _parseBloc() -> None: ...
    def _parseCode() -> None: ...
    def _processInstructionELIF() -> None: ...
    def _processInstructionELSE() -> None: ...
    def _processInstructionEND() -> None: ...
    def _processInstructionFOR() -> None: ...
    def _processInstructionIF() -> None: ...
    def _processInstructionINCLUDE() -> None: ...
    def _processInstructionPYTHON() -> None: ...
    def _processToken() -> None: ...
