from typing import Any

Node = Any

class AK8963:
    def _register_char() -> None: ...
    def _register_short() -> None: ...
    def _register_three_shorts() -> None: ...

class MPU6500:
    def _accel_fs() -> None: ...
    def _gyro_fs() -> None: ...
    def _register_char() -> None: ...
    def _register_short() -> None: ...
    def _register_three_shorts() -> None: ...

class MPU9250: ...

def const() -> None: ...
