AP_IF: int
AUTH_OPEN: int
AUTH_WEP: int
AUTH_WPA2_PSK: int
AUTH_WPA_PSK: int
AUTH_WPA_WPA2_PSK: int
MODE_11B: int
MODE_11G: int
MODE_11N: int
STA_IF: int

def WLAN() -> None: ...

class ftp:
    def pause() -> None: ...
    def resume() -> None: ...
    def stack() -> None: ...
    def start() -> None: ...
    def status() -> None: ...
    def stop() -> None: ...

class mDNS:
    def addService() -> None: ...
    def queryHost() -> None: ...
    def queryService() -> None: ...
    def removeService() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...

class mqtt:
    def config() -> None: ...
    def free() -> None: ...
    def publish() -> None: ...
    def start() -> None: ...
    def status() -> None: ...
    def stop() -> None: ...
    def subscribe() -> None: ...
    def unsubscribe() -> None: ...

def phy_mode() -> None: ...

class telnet:
    def pause() -> None: ...
    def resume() -> None: ...
    def stack() -> None: ...
    def start() -> None: ...
    def status() -> None: ...
    def stop() -> None: ...
