from typing import Any

Node = Any

def WLAN() -> None: ...

class ftp:
    def pause() -> None: ...
    def resume() -> None: ...
    def stack() -> None: ...
    def start() -> None: ...
    def status() -> None: ...
    def stop() -> None: ...

class mDNS:
    def addService() -> None: ...
    def queryHost() -> None: ...
    def queryService() -> None: ...
    def removeService() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...

class mqtt:
    def config() -> None: ...
    def free() -> None: ...
    def publish() -> None: ...
    def start() -> None: ...
    def status() -> None: ...
    def stop() -> None: ...
    def subscribe() -> None: ...
    def unsubscribe() -> None: ...

def phy_mode() -> None: ...

class telnet:
    def pause() -> None: ...
    def resume() -> None: ...
    def stack() -> None: ...
    def start() -> None: ...
    def status() -> None: ...
    def stop() -> None: ...
