
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def exec() -> None: ...
def get() -> None: ...
def list() -> None: ...
def llist() -> None: ...
def mkdir() -> None: ...
def options() -> None: ...
def put() -> None: ...
