from typing import Any

class Calibrate:
    def calibError() -> None: ...
    def calibrate() -> None: ...
    def drawCrossHair() -> None: ...
    def readCoordinates() -> None: ...
    def tpcalib() -> None: ...

display: Any
machine: Any
math: Any
utime: Any
