from typing import Any

Node = Any

class NotFoundError: ...

def _makedirs() -> None: ...
def cleanup() -> None: ...
def fatal() -> None: ...
def get_install_path() -> None: ...
def get_pkg_metadata() -> None: ...
def help() -> None: ...
def install() -> None: ...
def install_pkg() -> None: ...
def install_tar() -> None: ...
def main() -> None: ...
def op_basename() -> None: ...
def op_split() -> None: ...
def save_file() -> None: ...
def url_open() -> None: ...
