from typing import Any

class Partition:
    def find(self, *args) -> Any: ...
    BOOT: int
    RUNNING: int
    TYPE_APP: int
    TYPE_DATA: int
    def get_next_update(self, *args) -> Any: ...
    def info(self, *args) -> Any: ...
    def ioctl(self, *args) -> Any: ...
    def readblocks(self, *args) -> Any: ...
    def set_boot(self, *args) -> Any: ...
    def writeblocks(self, *args) -> Any: ...

class RMT:
    def clock_div(self, *args) -> Any: ...
    def deinit(self, *args) -> Any: ...
    def loop(self, *args) -> Any: ...
    def source_freq(self, *args) -> Any: ...
    def wait_done(self, *args) -> Any: ...
    def write_pulses(self, *args) -> Any: ...

class ULP:
    RESERVE_MEM: int
    def load_binary(self, *args) -> Any: ...
    def run(self, *args) -> Any: ...
    def set_wakeup_period(self, *args) -> Any: ...

WAKEUP_ALL_LOW: bool
WAKEUP_ANY_HIGH: bool

def hall_sensor(*args) -> Any: ...
def raw_temperature(*args) -> Any: ...
def wake_on_ext0(*args) -> Any: ...
def wake_on_ext1(*args) -> Any: ...
def wake_on_touch(*args) -> Any: ...
