from typing import Any

def localtime(*args) -> Any: ...
def mktime(*args) -> Any: ...
def sleep(*args) -> Any: ...
def sleep_ms(*args) -> Any: ...
def sleep_us(*args) -> Any: ...
def ticks_add(*args) -> Any: ...
def ticks_cpu(*args) -> Any: ...
def ticks_diff(*args) -> Any: ...
def ticks_ms(*args) -> Any: ...
def ticks_us(*args) -> Any: ...
def time(*args) -> Any: ...
