import ulab
from typing import Optional, Tuple

def fft(r: ulab.array, c: Optional[ulab.array] = ...) -> Tuple[ulab.array, ulab.array]: ...
def ifft(r: ulab.array, c: Optional[ulab.array] = ...) -> Tuple[ulab.array, ulab.array]: ...
def spectrogram(r: ulab.array) -> ulab.array: ...
