import ulab
from typing import Tuple, Union

def cholesky(A: ulab.array) -> ulab.array: ...
def det(m: ulab.array) -> float: ...
def dot(m1: ulab.array, m2: ulab.array) -> Union[ulab.array, float]: ...
def eig(m: ulab.array) -> Tuple[ulab.array, ulab.array]: ...
def inv(m: ulab.array) -> ulab.array: ...
def norm(x: ulab.array) -> float: ...
def trace(m: ulab.array) -> float: ...
