
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def height() -> None: ...
def max_width() -> None: ...
def hmap() -> None: ...
def reverse() -> None: ...
def monospaced() -> None: ...
def min_ch() -> None: ...
def max_ch() -> None: ...
def _chr_addr(ordch: Any) -> Any: ...
    #   0: return int.from_bytes(_index[offset:offset+])
    # ? 0: return int.from_bytes(_index[offset:offset+])
def get_ch(ch: Any) -> Tuple[Any, , Any]: ...
