
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Editor:
    def __init__(self, tab_size: Any, undo_limit: Any) -> None: ...
    def wr(self, s: str) -> None: ...
    def rd_any(self) -> None: ...
    def rd(self) -> Optional[Any]: ...
        #   0: return sys.stdin.read()
        # ? 0: return sys.stdin.read()
        #   1: return
        #   1: return
    def goto(self, row: Any, col: Any) -> None: ...
    def clear_to_eol(self) -> None: ...
    def cursor(self, onoff: Any) -> None: ...
    def hilite(self, mode: Any) -> None: ...
    def mouse_reporting(self, onoff: Any) -> None: ...
    def scroll_region(self, stop: Any) -> None: ...
    def scroll_up(self, scrolling: Any) -> None: ...
    def scroll_down(self, scrolling: Any) -> None: ...
    def get_screen_size(self) -> Any: ...
        #   0: return int(i) for i in pos.lstrip().split()
        # ? 0: return int for int in pos.lstrip().split()
    def redraw(self, flag: Any) -> None: ...
    def get_input(self) -> Union[Tuple[, Any, Any, Any], Tuple[, Any], Tuple[, ], Tuple[Any, ]]: ...
    def display_window(self) -> None: ...
    def spaces(self, line: Any, pos: Any=) -> int: ...
    def line_range(self) -> Tuple[Any, Any]: ...
    def line_edit(self, prompt: Any, default: Any) -> Optional[Any]: ...
        #   0: return res
        # ? 0: return res
        #   1: return
        #   1: return
    def find_in_file(self, pattern: Any, col: Any, end: Any) -> Optional[int]: ...
    def undo_add(self, lnum: Any, text: Any, key: Any, span: Any=) -> None: ...
    def delete_lines(self, yank: Any) -> None: ...
    def handle_edit_keys(self, key: Any, char: smallint) -> None: ...
    def edit_loop(self) -> Any: ...
        #   0: return key
        # ? 0: return key
        #   1: return key
        # ? 1: return key
    def packtabs(self, s: str) -> Any: ...
        #   0: return sb.getvalue()
        # ? 0: return sb.getvalue()
    def get_file(self, fname: Any) -> None: ...
    def put_file(self, fname: Any) -> None: ...
def expandtabs(s: str) -> Union[Any, str]: ...
    #   0: return sb.getvalue()
    # ? 0: return sb.getvalue()
    #   1: return s
    #   1: return str
def pye(*content) -> Any: ...
