
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Writer(object):
    def set_textpos(cls: Any, row: Any, col: Any) -> None: ...
    def set_clip(cls: Any, row_clip: Any, col_clip: Any) -> None: ...
    def __init__(self, device: Any, font: Any, verbose: Any=) -> None: ...
    def _newline(self) -> None: ...
    def printstring(self, string: Any) -> None: ...
    def _printchar(self, char: smallint) -> None: ...
    def _printchar_bitwise(self, char: smallint) -> None: ...
