from typing import Any

def dht_readinto(*args) -> Any: ...

class DHTBase:
    def __init__(self, *args) -> None: ...
    def measure(self, *args) -> Any: ...

class DHT11:
    def __init__(self, *args) -> None: ...
    def measure(self, *args) -> Any: ...
    def humidity(self, *args) -> Any: ...
    def temperature(self, *args) -> Any: ...

class DHT22:
    def __init__(self, *args) -> None: ...
    def measure(self, *args) -> Any: ...
    def humidity(self, *args) -> Any: ...
    def temperature(self, *args) -> Any: ...
