from typing import Any

class Partition:
    def find(self, *args) -> Any: ...
    BOOT: int
    RUNNING: int
    TYPE_APP: int
    TYPE_DATA: int
    def get_next_update(self, *args) -> Any: ...
    def info(self, *args) -> Any: ...
    def ioctl(self, *args) -> Any: ...
    @classmethod
    def mark_app_valid_cancel_rollback(cls, *args) -> Any: ...
    def readblocks(self, *args) -> Any: ...
    def set_boot(self, *args) -> Any: ...
    def writeblocks(self, *args) -> Any: ...

bdev: Any
