
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class MQTTClient:
    def _recv_len() -> None: ...
    def _send_str() -> None: ...
    def check_msg() -> None: ...
    def connect() -> None: ...
    def delay() -> None: ...
    def disconnect() -> None: ...
    def log() -> None: ...
    def ping() -> None: ...
    def set_callback() -> None: ...
    def set_last_will() -> None: ...
    def subscribe() -> None: ...
