"""
Module: 'asyncio.__init__' on micropython-v1.28.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.28.0'}
# Stubber: v1.28.0
from __future__ import annotations
from _typeshed import Incomplete

_attrs: dict = {}

def create_task(x0) -> Incomplete: ...
def current_task() -> Incomplete: ...
def ticks_diff(x0, x1) -> Incomplete: ...
def ticks_add(x0, x1) -> Incomplete: ...
def get_event_loop(x0, x1) -> Incomplete: ...
def ticks() -> Incomplete: ...
def run_until_complete(x0) -> Incomplete: ...
def new_event_loop() -> Incomplete: ...
def wait_for_ms(x0, x1) -> Incomplete: ...
def sleep(x0) -> Incomplete: ...
def run(x0) -> Incomplete: ...
def sleep_ms(x0, x1) -> Incomplete: ...

cur_task: Incomplete  ## <class 'NoneType'> = None

class TaskQueue:
    def push(self, *args, **kwargs) -> Incomplete: ...
    def peek(self, *args, **kwargs) -> Incomplete: ...
    def remove(self, *args, **kwargs) -> Incomplete: ...
    def pop(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

async def gather(x0) -> Incomplete: ...

class CancelledError(Exception): ...

async def wait_for(x0, x1, x2) -> Incomplete: ...
async def open_connection(x0, x1, x2, x3) -> Incomplete: ...
async def start_server(x0, x1, x2, x3, x4) -> Incomplete: ...

class Task:
    def __init__(self, *argv, **kwargs) -> None: ...

class Lock:
    def locked(self) -> Incomplete: ...
    def release(self) -> Incomplete: ...
    async def acquire(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Loop:
    def get_exception_handler(self) -> Incomplete: ...
    def default_exception_handler(self, x1) -> Incomplete: ...
    def set_exception_handler(self) -> Incomplete: ...
    def run_forever(self) -> Incomplete: ...
    def run_until_complete(self) -> Incomplete: ...
    def stop(self) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    def create_task(self) -> Incomplete: ...
    def call_exception_handler(self) -> Incomplete: ...

    _exc_handler: Incomplete  ## <class 'NoneType'> = None
    def __init__(self, *argv, **kwargs) -> None: ...

class IOQueue:
    def queue_read(self, x1) -> Incomplete: ...
    def wait_io_event(self, x1) -> Incomplete: ...
    def queue_write(self, x1) -> Incomplete: ...
    def remove(self, x1) -> Incomplete: ...
    def _enqueue(self, x1, x2) -> Incomplete: ...
    def _dequeue(self, x1) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Event:
    def set(self) -> Incomplete: ...
    def is_set(self) -> Incomplete: ...
    def clear(self) -> Incomplete: ...
    async def wait(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ThreadSafeFlag:
    def set(self) -> Incomplete: ...
    def ioctl(self, x1, x2) -> Incomplete: ...
    def clear(self) -> Incomplete: ...
    async def wait(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class TimeoutError(Exception): ...

class SingletonGenerator:
    def __init__(self, *argv, **kwargs) -> None: ...

class StreamWriter:
    def write(self, x1) -> Incomplete: ...
    def get_extra_info(self, x1) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    async def awritestr(self, x1, x2, x3) -> Incomplete: ...
    async def wait_closed(self) -> Incomplete: ...
    async def drain(self) -> Incomplete: ...
    async def readexactly(self, x1) -> Incomplete: ...
    async def readinto(self, x1) -> Incomplete: ...
    async def read(self, x1) -> Incomplete: ...
    async def awrite(self, x1, x2, x3) -> Incomplete: ...
    async def readline(self) -> Incomplete: ...
    async def aclose(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class StreamReader:
    def write(self, x1) -> Incomplete: ...
    def get_extra_info(self, x1) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    async def awritestr(self, x1, x2, x3) -> Incomplete: ...
    async def wait_closed(self) -> Incomplete: ...
    async def drain(self) -> Incomplete: ...
    async def readexactly(self, x1) -> Incomplete: ...
    async def readinto(self, x1) -> Incomplete: ...
    async def read(self, x1) -> Incomplete: ...
    async def awrite(self, x1, x2, x3) -> Incomplete: ...
    async def readline(self) -> Incomplete: ...
    async def aclose(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
