"""
Module: 'asyncio.funcs' on micropython-v1.28.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.28.0'}
# Stubber: v1.28.0
from __future__ import annotations
from _typeshed import Incomplete

def wait_for_ms(x0, x1) -> Incomplete: ...
async def gather(x0) -> Incomplete: ...
async def wait_for(x0, x1, x2) -> Incomplete: ...

class _Remove:
    def remove(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

async def _run(x0, x1) -> Incomplete: ...
