
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def set_pixel_power(state: Any) -> None: ...
def get_battery_voltage() -> Any: ...
    #   0: return round(measuredvbat)
    # ? 0: return round(measuredvbat)
def get_vbus_present() -> bool: ...
def rgb_color_wheel(wheel_pos: Any) -> Union[Tuple[, Any, Any], Tuple[Any, , Any], Tuple[Any, Any, ]]: ...
def go_deepsleep(t: Any) -> None: ...
