
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class SSD1306:
    def blit() -> None: ...
    def contrast() -> None: ...
    def fill() -> None: ...
    def fill_rect() -> None: ...
    def hline() -> None: ...
    def init_display() -> None: ...
    def invert() -> None: ...
    def line() -> None: ...
    def pixel() -> None: ...
    def poweroff() -> None: ...
    def poweron() -> None: ...
    def rect() -> None: ...
    def scroll() -> None: ...
    def show() -> None: ...
    def text() -> None: ...
    def vline() -> None: ...
class SSD1306_I2C:
    def blit() -> None: ...
