
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def callback() -> None: ...
def getaddrinfo() -> None: ...
def print_pcbs() -> None: ...
def reset() -> None: ...
class socket:
    def accept() -> None: ...
    def bind() -> None: ...
    def close() -> None: ...
    def connect() -> None: ...
