from typing import Any, Tuple

e: float
pi: float

def cos(z) -> float: ...
def exp(z) -> float: ...
def log(z) -> float: ...
def log10(z) -> float: ...
def phase(z) -> float: ...
def polar(z) -> Tuple: ...
def rect(r, phi) -> float: ...
def sin(z) -> float: ...
def sqrt(z) -> Any: ...
