from typing import Any, Optional

class aes:
    def __init__(self, key, mode, IV: Optional[Any]) -> None: ...
    def encrypt(self, in_buf, out_buf: Optional[Any]) -> Any: ...
    def decrypt(self, in_buf, out_buf: Optional[Any]) -> Any: ...
