from typing import Any, Optional

def enable() -> None: ...
def disable() -> None: ...
def collect() -> None: ...
def mem_alloc() -> int: ...
def mem_free() -> int: ...
def threshold(amount: Optional[Any]) -> Any: ...
