from typing import Tuple

class NeoPixel:
    def __init__(self, pin, n, *, bpp: int = ..., timing: int = ...) -> None: ...
    def fill(self, pixel) -> None: ...
    def __len__(self) -> int: ...
    def __setitem__(self, index, val) -> None: ...
    def __getitem__(self, index) -> Tuple: ...
    def write(self) -> None: ...
