from typing import Any, Optional

class random:
    def __init__(self) -> None: ...

def getrandbits(n) -> int: ...
def randint(a, b) -> int: ...
def randrange(start, stop, step: Optional[Any]) -> int: ...
def uniform(a, b) -> int: ...
def seed(n: Any | None = ...) -> None: ...
def choice(sequence) -> Any: ...
