"""
Module: 'ujson' on micropython-v1.24.1-esp32-ESP32_GENERIC
"""

# MCU: {'family': 'micropython', 'version': '1.24.1', 'build': '', 'ver': '1.24.1', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'cpu': 'ESP32', 'mpy': 'v6.3', 'arch': 'xtensawin'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def loads(*args, **kwargs) -> Incomplete: ...
def load(*args, **kwargs) -> Incomplete: ...
def dumps(*args, **kwargs) -> Incomplete: ...
def dump(*args, **kwargs) -> Incomplete: ...
