
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class ATOM:
    def __init__(self, np_n: Any) -> None: ...
    def get_button_status(self) -> Any: ...
        #   0: return self._btn.value()
        # ? 0: return self._btn.value()
    def set_button_callback(self, cb: Any) -> None: ...
    def set_pixel_color(self, num: Any, r: Any, g: Any, b: Any) -> None: ...
    def get_pixel_color(self, num: Any) -> Any: ...
        #   0: return self._np[num]
        # ? 0: return self._np[num]
    def set_pixels_color(self, r: Any, g: Any, b: Any) -> None: ...
class Lite(ATOM):
    def __init__(self) -> None: ...
class Matrix(ATOM):
    def __init__(self) -> None: ...
