"""
Module: 'aioble.peripheral' on micropython-v1.28.0-rp2-RPI_PICO_W
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.28.0', 'arch': 'armv6m', 'version': '1.28.0', 'port': 'rp2', 'board': 'RPI_PICO_W', 'family': 'micropython', 'board_id': 'RPI_PICO_W', 'variant': '', 'cpu': 'RP2040'}
# Stubber: v1.28.0
from __future__ import annotations
from typing import Generator
from _typeshed import Incomplete

def _peripheral_shutdown(*args, **kwargs) -> Incomplete: ...
def ensure_active(*args, **kwargs) -> Incomplete: ...
def _peripheral_irq(*args, **kwargs) -> Incomplete: ...
def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def log_warn(*args, **kwargs) -> Incomplete: ...
def log_error(*args, **kwargs) -> Incomplete: ...
def log_info(*args, **kwargs) -> Incomplete: ...
def _append(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class Device:
    def addr_hex(self, *args, **kwargs) -> Incomplete: ...
    def connect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

_incoming_connection: Incomplete  ## <class 'NoneType'> = None
_connect_event: Incomplete  ## <class 'NoneType'> = None

class DeviceConnection:
    _connected: dict = {}
    def is_connected(self, *args, **kwargs) -> Incomplete: ...
    def _run_task(self, *args, **kwargs) -> Incomplete: ...
    def services(self, *args, **kwargs) -> Incomplete: ...
    def timeout(self, *args, **kwargs) -> Incomplete: ...
    def device_task(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def l2cap_connect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def pair(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def service(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def l2cap_accept(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def disconnected(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def exchange_mtu(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def disconnect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

class DeviceTimeout:
    def _timeout_sleep(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

ble: Incomplete  ## <class 'BLE'> = <BLE>

def advertise(*args, **kwargs) -> Generator:  ## = <generator>
    ...
