from _typeshed import Incomplete as Incomplete

def crc32(*args, **kwargs) -> Incomplete: ...
def hexlify(*args, **kwargs) -> Incomplete: ...
def unhexlify(*args, **kwargs) -> Incomplete: ...
def b2a_base64(*args, **kwargs) -> Incomplete: ...
def a2b_base64(*args, **kwargs) -> Incomplete: ...
