"""
Module: 'time' on micropython-v1.23.0-preview-samd-SEEED_WIO_TERMINAL
"""
# MCU: {'version': '1.23.0-preview', 'mpy': 'v6.2', 'port': 'samd', 'board': 'SEEED_WIO_TERMINAL', 'family': 'micropython', 'build': '205', 'arch': 'armv7emsp', 'ver': '1.23.0-preview-205', 'cpu': 'SAMD51P19A'}
# Stubber: v1.17.3
from __future__ import annotations
from _typeshed import Incomplete

def ticks_diff(*args, **kwargs) -> Incomplete: ...
def ticks_add(*args, **kwargs) -> Incomplete: ...
def ticks_cpu(*args, **kwargs) -> Incomplete: ...
def time(*args, **kwargs) -> Incomplete: ...
def ticks_ms(*args, **kwargs) -> Incomplete: ...
def ticks_us(*args, **kwargs) -> Incomplete: ...
def time_ns(*args, **kwargs) -> Incomplete: ...
def localtime(*args, **kwargs) -> Incomplete: ...
def sleep_us(*args, **kwargs) -> Incomplete: ...
def gmtime(*args, **kwargs) -> Incomplete: ...
def sleep_ms(*args, **kwargs) -> Incomplete: ...
def mktime(*args, **kwargs) -> Incomplete: ...
def sleep(*args, **kwargs) -> Incomplete: ...
