# This umodule is a MicroPython reference to socket
from socket import AF_INET as AF_INET
from socket import AF_INET6 as AF_INET6
from socket import AF_UNIX as AF_UNIX
from socket import IP_ADD_MEMBERSHIP as IP_ADD_MEMBERSHIP
from socket import IP_DROP_MEMBERSHIP as IP_DROP_MEMBERSHIP
from socket import MSG_DONTROUTE as MSG_DONTROUTE
from socket import MSG_DONTWAIT as MSG_DONTWAIT
from socket import MSG_PEEK as MSG_PEEK
from socket import SO_BROADCAST as SO_BROADCAST
from socket import SO_ERROR as SO_ERROR
from socket import SO_KEEPALIVE as SO_KEEPALIVE
from socket import SO_LINGER as SO_LINGER
from socket import SO_REUSEADDR as SO_REUSEADDR
from socket import SOCK_DGRAM as SOCK_DGRAM
from socket import SOCK_RAW as SOCK_RAW
from socket import SOCK_STREAM as SOCK_STREAM
from socket import SOL_SOCKET as SOL_SOCKET
from socket import getaddrinfo as getaddrinfo
from socket import inet_ntop as inet_ntop
from socket import inet_pton as inet_pton
from socket import sockaddr as sockaddr
from socket import socket as socket
