
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Response:
    def __init__(self, f: Any) -> None: ...
    def close(self) -> None: ...
    def content(self) -> Any: ...
        #   0: return self._cached
        # ? 0: return self._cached
    def text(self) -> str(self.content, self.encoding): ...
    def json(self) -> Any: ...
        #   0: return ujson.loads(self.content)
        # ? 0: return ujson.loads(self.content)
def request(method: Any, url: Any, data: Any=, json: Any=, headers: Any={}, stream: Any=) -> Any: ...
    #   0: return resp
    # ? 0: return resp
def head(url: Any, **kw) -> Any: ...
    #   0: return request(url,None=kw)
    # ? 0: return request(url, None=kw)
def get(url: Any, **kw) -> Any: ...
    #   0: return request(url,None=kw)
    # ? 0: return request(url, None=kw)
def post(url: Any, **kw) -> Any: ...
    #   0: return request(url,None=kw)
    # ? 0: return request(url, None=kw)
def put(url: Any, **kw) -> Any: ...
    #   0: return request(url,None=kw)
    # ? 0: return request(url, None=kw)
def patch(url: Any, **kw) -> Any: ...
    #   0: return request(url,None=kw)
    # ? 0: return request(url, None=kw)
def delete(url: Any, **kw) -> Any: ...
    #   0: return request(url,None=kw)
    # ? 0: return request(url, None=kw)
