
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Dac:
    def _available() -> None: ...
    def deinit() -> None: ...
    def setVoltage() -> None: ...
    def writeData() -> None: ...
def const() -> None: ...
