
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Pahub:
    def _available() -> None: ...
    def deinit() -> None: ...
    def select() -> None: ...
    def select_only_on() -> None: ...
    def select_port() -> None: ...
