
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class PWM:
    def deinit() -> None: ...
    def duty() -> None: ...
    def freq() -> None: ...
    def init() -> None: ...
    def list() -> None: ...
    def pause() -> None: ...
    def resume() -> None: ...
class Servo:
    def deinit() -> None: ...
    def write_angle() -> None: ...
    def write_us() -> None: ...
