"""
Module: 'binascii' on micropython-v1.22.1-rp2-RPI_PICO
"""
# MCU: {'family': 'micropython', 'version': '1.22.1', 'build': '', 'ver': '1.22.1', 'port': 'rp2', 'board': 'RPI_PICO', 'cpu': 'RP2040', 'mpy': 'v6.2', 'arch': 'armv6m'}
# Stubber: v1.17.1
from __future__ import annotations
from _typeshed import Incomplete

def crc32(*args, **kwargs) -> Incomplete: ...
def hexlify(*args, **kwargs) -> Incomplete: ...
def unhexlify(*args, **kwargs) -> Incomplete: ...
def b2a_base64(*args, **kwargs) -> Incomplete: ...
def a2b_base64(*args, **kwargs) -> Incomplete: ...
