"""
Module: 'umqtt.robust' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from typing import Final
from _typeshed import Incomplete

class MQTTClient:
    DELAY: Final[int] = 2
    DEBUG: Final[bool] = False
    def delay(self, x1) -> Incomplete: ...
    def unsubscribe(self, x1) -> Incomplete: ...
    def set_last_will(self, x1, x2, x3, x4) -> Incomplete: ...
    def ping(self) -> Incomplete: ...
    def subscribe(self, x1, x2) -> Incomplete: ...
    def set_callback(self, x1) -> Incomplete: ...
    def disconnect(self) -> Incomplete: ...
    def connect(self, x1, x2) -> Incomplete: ...
    def _send_str(self, x1) -> Incomplete: ...
    def log(self, x1, x2) -> Incomplete: ...
    def _recv_len(self) -> Incomplete: ...
    def wait_msg(self) -> Incomplete: ...
    def check_msg(self, x1) -> Incomplete: ...
    def reconnect(self) -> Incomplete: ...
    def publish(self, x1, x2, x3, x4) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
