from typing import Any

LOG_DEBUG: int
LOG_ERROR: int
LOG_INFO: int
LOG_NONE: int
LOG_VERBOSE: int
LOG_WARNING: int

def dht_readinto(*args) -> Any: ...
def flash_erase(*args) -> Any: ...
def flash_read(*args) -> Any: ...
def flash_size(*args) -> Any: ...
def flash_user_start(*args) -> Any: ...
def flash_write(*args) -> Any: ...
def gpio_matrix_in(*args) -> Any: ...
def gpio_matrix_out(*args) -> Any: ...
def osdebug(*args) -> Any: ...
