"""
Module: 'ubluepy' on micropython-v1.29.0-nrf-SEEED_XIAO_NRF52
"""

# MCU: {'variant': '', 'build': '', 'arch': 'armv7emsp', 'port': 'nrf', 'board': 'SEEED_XIAO_NRF52', 'board_id': 'SEEED_XIAO_NRF52', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'NRF52840', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from typing import Any, AsyncGenerator, Final, Generator

from _typeshed import Incomplete

class constants:
    EVT_GAP_DISCONNECTED: Final[int] = 17
    UUID_CCCD: Final[int] = 10498
    EVT_GATTS_WRITE: Final[int] = 80
    ADDR_TYPE_PUBLIC: Final[int] = 0
    EVT_GAP_CONNECTED: Final[int] = 16
    ADDR_TYPE_RANDOM_STATIC: Final[int] = 1

    class ad_types:
        AD_TYPE_URI: Final[int] = 36
        AD_TYPE_SERVICE_DATA_128BIT_UUID: Final[int] = 33
        AD_TYPE_SERVICE_DATA_32BIT_UUID: Final[int] = 32
        AD_TYPE_SHORT_LOCAL_NAME: Final[int] = 8
        AD_TYPE_SERVICE_DATA: Final[int] = 22
        AD_TYPE_RANDOM_TARGET_ADDRESS: Final[int] = 24
        AD_TYPE_SECURITY_MANAGER_OOB_FLAGS: Final[int] = 17
        AD_TYPE_SECURITY_MANAGER_TK_VALUE: Final[int] = 16
        AD_TYPE_SIMPLE_PAIRING_HASH_C: Final[int] = 14
        AD_TYPE_SOLICITED_SERVICE_UUIDS_128BIT: Final[int] = 21
        AD_TYPE_SOLICITED_SERVICE_UUIDS_16BIT: Final[int] = 20
        AD_TYPE_TX_POWER_LEVEL: Final[int] = 10
        AD_TYPE_SLAVE_CONNECTION_INTERVAL_RANGE: Final[int] = 18
        AD_TYPE_SIMPLE_PAIRING_HASH_C256: Final[int] = 29
        AD_TYPE_SIMPLE_PAIRING_RANDOMIZER_R: Final[int] = 15
        AD_TYPE_SIMPLE_PAIRING_RANDOMIZER_R256: Final[int] = 30
        AD_TYPE_PUBLIC_TARGET_ADDRESS: Final[int] = 23
        AD_TYPE_32BIT_SERVICE_UUID_COMPLETE: Final[int] = 5
        AD_TYPE_32BIT_SERVICE_UUID_MORE_AVAILABLE: Final[int] = 4
        AD_TYPE_3D_INFORMATION_DATA: Final[int] = 61
        AD_TYPE_16BIT_SERVICE_UUID_MORE_AVAILABLE: Final[int] = 2
        AD_TYPE_128BIT_SERVICE_UUID_COMPLETE: Final[int] = 7
        AD_TYPE_128BIT_SERVICE_UUID_MORE_AVAILABLE: Final[int] = 6
        AD_TYPE_16BIT_SERVICE_UUID_COMPLETE: Final[int] = 3
        AD_TYPE_ADVERTISING_INTERVAL: Final[int] = 26
        AD_TYPE_LE_BLUETOOTH_DEVICE_ADDRESS: Final[int] = 27
        AD_TYPE_LE_ROLE: Final[int] = 28
        AD_TYPE_MANUFACTURER_SPECIFIC_DATA: Final[int] = 255
        AD_TYPE_FLAGS: Final[int] = 1
        AD_TYPE_APPEARANCE: Final[int] = 25
        AD_TYPE_CLASS_OF_DEVICE: Final[int] = 13
        AD_TYPE_COMPLETE_LOCAL_NAME: Final[int] = 9
        def __init__(self, *argv, **kwargs) -> None: ...

    def __init__(self, *argv, **kwargs) -> None: ...

class Scanner:
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Service:
    SECONDARY: Final[int] = 2
    PRIMARY: Final[int] = 1
    def uuid(self, *args, **kwargs) -> Incomplete: ...
    def getCharacteristics(self, *args, **kwargs) -> Incomplete: ...
    def getCharacteristic(self, *args, **kwargs) -> Incomplete: ...
    def addCharacteristic(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class UUID:
    def binVal(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ScanEntry:
    def rssi(self, *args, **kwargs) -> Incomplete: ...
    def getScanData(self, *args, **kwargs) -> Incomplete: ...
    def addr_type(self, *args, **kwargs) -> Incomplete: ...
    def addr(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Characteristic:
    PROP_BROADCAST: Final[int] = 1
    PROP_INDICATE: Final[int] = 32
    PROP_NOTIFY: Final[int] = 16
    PROP_READ: Final[int] = 2
    PROP_WRITE: Final[int] = 8
    PROP_WRITE_WO_RESP: Final[int] = 4
    PROP_AUTH_SIGNED_WR: Final[int] = 64
    ATTR_CCCD: Final[int] = 1
    def properties(self, *args, **kwargs) -> Incomplete: ...
    def uuid(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class DefaultDelegate:
    def handleNotification(self, *args, **kwargs) -> Incomplete: ...
    def handleConnection(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Peripheral:
    def disconnect(self, *args, **kwargs) -> Incomplete: ...
    def getServices(self, *args, **kwargs) -> Incomplete: ...
    def setConnectionHandler(self, *args, **kwargs) -> Incomplete: ...
    def setNotificationHandler(self, *args, **kwargs) -> Incomplete: ...
    def withDelegate(self, *args, **kwargs) -> Incomplete: ...
    def connect(self, *args, **kwargs) -> Incomplete: ...
    def addService(self, *args, **kwargs) -> Incomplete: ...
    def advertise(self, *args, **kwargs) -> Incomplete: ...
    def advertise_stop(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
