# Micropython v1.29.0-preview frozen stubs
def attrgetter(attr): ...
def lt(a, b): ...
def le(a, b): ...
def gt(a, b): ...
def ge(a, b): ...
def eq(a, b): ...
def ne(a, b): ...
def mod(a, b): ...
def truediv(a, b): ...
def floordiv(a, b): ...
