"""
Module: 'utime' on micropython-v1.26.0-rp2-RPI_PICO
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.26.0', 'arch': 'armv6m', 'version': '1.26.0', 'port': 'rp2', 'board': 'RPI_PICO', 'family': 'micropython', 'board_id': 'RPI_PICO', 'variant': '', 'cpu': 'RP2040'}
# Stubber: v1.26.0
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

def ticks_diff(*args, **kwargs) -> Incomplete: ...
def ticks_add(*args, **kwargs) -> Incomplete: ...
def ticks_cpu(*args, **kwargs) -> Incomplete: ...
def time(*args, **kwargs) -> Incomplete: ...
def ticks_ms(*args, **kwargs) -> Incomplete: ...
def ticks_us(*args, **kwargs) -> Incomplete: ...
def time_ns(*args, **kwargs) -> Incomplete: ...
def localtime(*args, **kwargs) -> Incomplete: ...
def sleep_us(*args, **kwargs) -> Incomplete: ...
def gmtime(*args, **kwargs) -> Incomplete: ...
def sleep_ms(*args, **kwargs) -> Incomplete: ...
def mktime(*args, **kwargs) -> Incomplete: ...
def sleep(*args, **kwargs) -> Incomplete: ...
