"""
Module: 'gc' on micropython-v1.29.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'ESP32-S2', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from _typeshed import Incomplete

def mem_alloc() -> Incomplete: ...
def isenabled() -> Incomplete: ...
def mem_free() -> Incomplete: ...
def threshold(*args, **kwargs) -> Incomplete: ...
def collect() -> Incomplete: ...
def enable() -> Incomplete: ...
def disable() -> Incomplete: ...
