# Micropython v1.26.1 frozen stubs
from _typeshed import Incomplete

_TAR_HEADER: Incomplete
_NUL: Incomplete
_BLOCKSIZE: int
_RECORDSIZE: Incomplete

def _open_write(self, name, mode, fileobj) -> None: ...
def _close_write(self) -> None: ...
def addfile(self, tarinfo, fileobj=None) -> None: ...
def add(self, name, recursive: bool = True) -> None: ...
