from typing import Any

Node = Any

class TFT:
    def arc() -> None: ...
    def attrib7seg() -> None: ...
    def backlight() -> None: ...
    def circle() -> None: ...
    def clear() -> None: ...
    def clearwin() -> None: ...
    def compileFont() -> None: ...
    def deinit() -> None: ...
    def ellipse() -> None: ...
    def font() -> None: ...
    def fontSize() -> None: ...
    def getCalib() -> None: ...
    def getTouchType() -> None: ...
    def get_bg() -> None: ...
    def get_fg() -> None: ...
    def gettouch() -> None: ...
    def hsb2rgb() -> None: ...
    def image() -> None: ...
    def init() -> None: ...
    def line() -> None: ...
    def lineByAngle() -> None: ...
    def orient() -> None: ...
    def pixel() -> None: ...
    def polygon() -> None: ...
    def readPixel() -> None: ...
    def rect() -> None: ...
    def resetwin() -> None: ...
    def restorewin() -> None: ...
    def roundrect() -> None: ...
    def savewin() -> None: ...
    def screensize() -> None: ...
    def setCalib() -> None: ...
    def set_bg() -> None: ...
    def set_fg() -> None: ...
    def setwin() -> None: ...
    def text() -> None: ...
    def textClear() -> None: ...
    def textWidth() -> None: ...
    def tft_deselect() -> None: ...
    def tft_readcmd() -> None: ...
    def tft_select() -> None: ...
    def tft_setspeed() -> None: ...
    def tft_writecmd() -> None: ...
    def tft_writecmddata() -> None: ...
    def triangle() -> None: ...
    def winsize() -> None: ...
