from typing import Any

Node = Any

def exec() -> None: ...
def get() -> None: ...
def list() -> None: ...
def llist() -> None: ...
def mkdir() -> None: ...
def options() -> None: ...
def put() -> None: ...
