from _typeshed import Incomplete as Incomplete

def time_pulse_us(*args, **kwargs) -> Incomplete: ...

mem32: Incomplete
mem8: Incomplete

class PinBase:
    def __init__(self, *argv, **kwargs) -> None: ...

mem16: Incomplete

class Signal:
    def off(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
