from _typeshed import Incomplete as Incomplete

def decompress(*args, **kwargs) -> Incomplete: ...

class DecompIO:
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def readline(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
