from _typeshed import Incomplete as Incomplete

class aes:
    def encrypt(self, *args, **kwargs) -> Incomplete: ...
    def decrypt(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
