# Micropython v1.29.0-preview frozen stubs
import types
from _typeshed import Incomplete

class BodyStream:
    _sock: Incomplete
    _remaining: Incomplete
    def __init__(self, sock, remaining) -> None: ...
    def read(self, n: int = -1): ...
    def readinto(self, buf): ...
    def close(self) -> None: ...

class Response:
    raw: Incomplete
    encoding: str
    _cached: Incomplete
    def __init__(self, f) -> None: ...
    def close(self) -> None: ...
    @property
    def content(self): ...
    @property
    def text(self): ...
    def json(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...

def request(method, url, data=None, json=None, headers=None, stream=None, auth=None, timeout=None, parse_headers: bool = True): ...
def head(url, **kw): ...
def get(url, **kw): ...
def post(url, **kw): ...
def put(url, **kw): ...
def patch(url, **kw): ...
def delete(url, **kw): ...
