
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class APA102:
    def fill() -> None: ...
    def write() -> None: ...
class NeoPixel:
    def fill() -> None: ...
    def write() -> None: ...
def apa102_write() -> None: ...
