"""
Module: 'unittest.__init__' on micropython-v1.29.0-webassembly-pyscript
"""

# MCU: {'family': 'micropython', 'version': '1.29.0', 'build': '', 'ver': '1.29.0', 'port': 'webassembly', 'board': 'pyscript', 'board_id': 'pyscript', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.29.0
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

# inspect: arity=3
def _run_suite(*args, **kwargs) -> Incomplete: ...

# inspect: arity=2
def skipUnless(*args, **kwargs) -> Incomplete: ...

# inspect: arity=4
def _handle_test_exception(*args, **kwargs) -> Incomplete: ...

# inspect: arity=2
def skipIf(*args, **kwargs) -> Incomplete: ...

# inspect: arity=1
def expectedFailure(*args, **kwargs) -> Incomplete: ...

# inspect: arity=1
def skip(*args, **kwargs) -> Incomplete: ...

# inspect: arity=2
def main(*args, **kwargs) -> Incomplete: ...

class SkipTest:
    def __init__(self, *argv, **kwargs) -> None: ...

class AssertRaisesContext:
    def __init__(self, *argv, **kwargs) -> None: ...

class SubtestContext:
    def __init__(self, *argv, **kwargs) -> None: ...

class TestResult:
    # inspect: arity=1
    def printErrors(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=1
    def wasSuccessful(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def printErrorList(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class TestCase:
    # inspect: arity=4
    def assertNotEqual(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=3
    def assertRaises(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=3
    def assertIsNotNone(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=6
    def assertNotAlmostEqual(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertLessEqual(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def fail(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def skipTest(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=3
    def assertTrue(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=1
    def doCleanups(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def assertWarns(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def subTest(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertEqual(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=3
    def assertFalse(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertIsNot(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=6
    def assertAlmostEqual(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def addCleanup(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertIsInstance(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=3
    def assertIsNone(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertGreaterEqual(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertIs(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=4
    def assertIn(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class TextTestRunner:
    # inspect: arity=2
    def run(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class TestRunner:
    # inspect: arity=2
    def run(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class TestSuite:
    # inspect: arity=2
    def addTest(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def run(self, *args, **kwargs) -> Incomplete: ...

    # inspect: arity=2
    def _load_module(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
