"""
Module: 'mip.__init__' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

allowed_mip_url_prefixes: tuple = ()

def _ensure_path_exists(x0) -> Incomplete: ...
def _install_json(x0, x1, x2, x3, x4) -> Incomplete: ...
def _install_package(x0, x1, x2, x3, x4) -> Incomplete: ...
def _rewrite_url(x0, x1) -> Incomplete: ...
def const(x0) -> Incomplete: ...
def _download_file(x0, x1) -> Incomplete: ...
def install(x0, x1, x2, x3, x4) -> Incomplete: ...
def _check_exists(x0, x1) -> Incomplete: ...
def _chunk(x0, x1) -> Incomplete: ...
