from typing import Any

class M5mqtt:
    def _daemonTask() -> None: ...
    def _msg_deal() -> None: ...
    def _on_data() -> None: ...
    def on_connect() -> None: ...
    def publish() -> None: ...
    def start() -> None: ...
    def subscribe() -> None: ...
    def unsubscribe() -> None: ...

class MQTTClient:
    def _clean_sock_buffer() -> None: ...
    def _recv_len() -> None: ...
    def _send_str() -> None: ...
    def check_msg() -> None: ...
    def connect() -> None: ...
    def disconnect() -> None: ...
    def lock_msg_rec() -> None: ...
    def ping() -> None: ...
    def publish() -> None: ...
    def set_block() -> None: ...
    def set_callback() -> None: ...
    def set_last_will() -> None: ...
    def socket_connect() -> None: ...
    def subscribe() -> None: ...
    def topic_get() -> None: ...
    def topic_msg_get() -> None: ...
    def unlock_msg_rec() -> None: ...
    def wait_msg() -> None: ...

_thread: Any

def autoConnect() -> None: ...

lcd: Any
m5base: Any
machine: Any

def reconnect() -> None: ...

time: Any
wlan_sta: Any
