
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Btn:
    def attach() -> None: ...
    def deinit() -> None: ...
    def detach() -> None: ...
    def multiBtnCb() -> None: ...
    def restart() -> None: ...
    def timerCb() -> None: ...
class BtnChild:
    def deinit() -> None: ...
    def isPressed() -> None: ...
    def isReleased() -> None: ...
    def pressFor() -> None: ...
    def restart() -> None: ...
    def upDate() -> None: ...
    def wasDoublePress() -> None: ...
    def wasPressed() -> None: ...
    def wasReleased() -> None: ...
class IP5306:
    def getBatteryLevel() -> None: ...
    def init() -> None: ...
    def isChargeFull() -> None: ...
    def isCharging() -> None: ...
    def setCharge() -> None: ...
    def setChargeVolt() -> None: ...
    def setVinMaxCurrent() -> None: ...
class M5UCloud:
    def _error() -> None: ...
    def deinit() -> None: ...
    def exec_deal() -> None: ...
    def on_data() -> None: ...
    def run() -> None: ...
class Rgb_multi:
    def deinit() -> None: ...
    def setBrightness() -> None: ...
    def setColor() -> None: ...
    def setColorAll() -> None: ...
    def setColorFrom() -> None: ...
    def setShowLock() -> None: ...
    def show() -> None: ...
class Speaker:
    def _timeout_cb() -> None: ...
    def checkInit() -> None: ...
    def setBeat() -> None: ...
    def setVolume() -> None: ...
    def sing() -> None: ...
    def tone() -> None: ...
def btnText() -> None: ...
def cfgRead() -> None: ...
def cfgWrite() -> None: ...
def const() -> None: ...
def core_start() -> None: ...
def flowDeinit() -> None: ...
class flowExit: ...
def getP2PData() -> None: ...
def get_sd_state() -> None: ...
def hwDeinit() -> None: ...
def loopExit() -> None: ...
def loopSetIdle() -> None: ...
def loopState() -> None: ...
def modeSet() -> None: ...
def remoteInit() -> None: ...
def resetDefault() -> None: ...
def sd_mount() -> None: ...
def sd_umount() -> None: ...
def sendP2PData() -> None: ...
def setP2PData() -> None: ...
def start() -> None: ...
def startBeep() -> None: ...
def wait() -> None: ...
def wait_ms() -> None: ...
