
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Timer:
    def deinit() -> None: ...
    def init() -> None: ...
    def setCallback() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...
    def update() -> None: ...
class timeSch:
    def checkInit() -> None: ...
    def deinit() -> None: ...
    def event() -> None: ...
    def remove_all() -> None: ...
    def run() -> None: ...
    def setTimer() -> None: ...
    def stop() -> None: ...
    def timerCb() -> None: ...
