"""
Module: 'gc' on micropython-v1.23.0-preview-esp32-ESP32_GENERIC
"""
# MCU: {'version': '1.23.0-preview', 'mpy': 'v6.2', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'family': 'micropython', 'build': 'preview.176.g90e517862', 'arch': 'xtensawin', 'ver': '1.23.0-preview-preview.176.g90e517862', 'cpu': 'ESP32'}
# Stubber: v1.17.3
from __future__ import annotations
from _typeshed import Incomplete

def mem_alloc(*args, **kwargs) -> Incomplete: ...
def isenabled(*args, **kwargs) -> Incomplete: ...
def mem_free(*args, **kwargs) -> Incomplete: ...
def threshold(*args, **kwargs) -> Incomplete: ...
def collect(*args, **kwargs) -> Incomplete: ...
def enable(*args, **kwargs) -> Incomplete: ...
def disable(*args, **kwargs) -> Incomplete: ...
