from typing import Any

CLIENT_ID: Any

class MQTTClient:
    def _recv_len(self, *argv) -> Any: ...
    def _send_str(self, *argv) -> Any: ...
    def check_msg(self, *argv) -> Any: ...
    def connect(self, *argv) -> Any: ...
    def disconnect(self, *argv) -> Any: ...
    def ping(self, *argv) -> Any: ...
    def publish(self, *argv) -> Any: ...
    def set_callback(self, *argv) -> Any: ...
    def set_last_will(self, *argv) -> Any: ...
    def subscribe(self, *argv) -> Any: ...
    def wait_msg(self, *argv) -> Any: ...

class Pin:
    IN: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    PULL_UP: int
    def init(self, *argv) -> Any: ...
    def irq(self, *argv) -> Any: ...
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

SERVER: str
TOPIC: Any
button: Any
machine: Any

def main() -> None: ...

time: Any
ubinascii: Any
