from typing import Any

class FrameBuffer:
    def blit(self, *argv) -> Any: ...
    def fill(self, *argv) -> Any: ...
    def fill_rect(self, *argv) -> Any: ...
    def hline(self, *argv) -> Any: ...
    def line(self, *argv) -> Any: ...
    def pixel(self, *argv) -> Any: ...
    def rect(self, *argv) -> Any: ...
    def scroll(self, *argv) -> Any: ...
    def text(self, *argv) -> Any: ...
    def vline(self, *argv) -> Any: ...

def FrameBuffer1() -> None: ...

GS2_HMSB: int
GS4_HMSB: int
GS8: int
MONO_HLSB: int
MONO_HMSB: int
MONO_VLSB: int
MVLSB: int
RGB565: int
