from typing import Any

class OrderedDict:
    def clear(self, *argv) -> Any: ...
    def copy(self, *argv) -> Any: ...
    def fromkeys(self, *argv) -> Any: ...
    def get(self, *argv) -> Any: ...
    def items(self, *argv) -> Any: ...
    def keys(self, *argv) -> Any: ...
    def pop(self, *argv) -> Any: ...
