from typing import Any

class BytesIO:
    def close(self, *argv) -> Any: ...
    def flush(self, *argv) -> Any: ...
    def getvalue(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def readline(self, *argv) -> Any: ...
    def seek(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...

class FileIO: ...
