from typing import Any

class APA102:
    ORDER: Any
    def fill(self, *args) -> Any: ...
    def write(self, *args) -> Any: ...

class NeoPixel:
    ORDER: Any
    def fill(self, *args) -> Any: ...
    def write(self, *args) -> Any: ...

def apa102_write(*args) -> Any: ...
