"""
Module: 'aioble.central' on micropython-v1.28.0-rp2-RPI_PICO_W
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.28.0', 'arch': 'armv6m', 'version': '1.28.0', 'port': 'rp2', 'board': 'RPI_PICO_W', 'family': 'micropython', 'board_id': 'RPI_PICO_W', 'variant': '', 'cpu': 'RP2040'}
# Stubber: v1.28.0
from __future__ import annotations
from typing import Generator
from _typeshed import Incomplete

def _central_shutdown(*args, **kwargs) -> Incomplete: ...
def ensure_active(*args, **kwargs) -> Incomplete: ...
def _central_irq(*args, **kwargs) -> Incomplete: ...
def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def log_warn(*args, **kwargs) -> Incomplete: ...
def log_error(*args, **kwargs) -> Incomplete: ...
def log_info(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

ble: Incomplete  ## <class 'BLE'> = <BLE>

class DeviceTimeout:
    def _timeout_sleep(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

class scan:
    def cancel(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

_active_scanner: Incomplete  ## <class 'NoneType'> = None

def _cancel_pending(*args, **kwargs) -> Generator:  ## = <generator>
    ...

class ScanResult:
    def _update(self, *args, **kwargs) -> Incomplete: ...
    def name(self, *args, **kwargs) -> Incomplete: ...
    def manufacturer(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def services(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def _decode_field(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

_connecting: set  ## = set()

def _connect(*args, **kwargs) -> Generator:  ## = <generator>
    ...

class DeviceConnection:
    _connected: dict = {}
    def is_connected(self, *args, **kwargs) -> Incomplete: ...
    def _run_task(self, *args, **kwargs) -> Incomplete: ...
    def services(self, *args, **kwargs) -> Incomplete: ...
    def timeout(self, *args, **kwargs) -> Incomplete: ...
    def device_task(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def l2cap_connect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def pair(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def service(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def l2cap_accept(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def disconnected(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def exchange_mtu(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def disconnect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Device:
    def addr_hex(self, *args, **kwargs) -> Incomplete: ...
    def connect(self, *args, **kwargs) -> Generator:  ## = <generator>
        ...
    def __init__(self, *argv, **kwargs) -> None: ...
