from _typeshed import Incomplete

START_HEADER_SIZE: int
LED_START: int
RGB: Incomplete
RBG: Incomplete
GRB: Incomplete
GBR: Incomplete
BRG: Incomplete
BGR: Incomplete

class DotStar:
    _spi: Incomplete
    _n: Incomplete
    end_header_size: Incomplete
    _buf: Incomplete
    end_header_index: Incomplete
    pixel_order: Incomplete
    _brightness: float
    auto_write: bool
    def __init__(self, spi, n, *, brightness: float = ..., auto_write: bool = ..., pixel_order=...) -> None: ...
    def deinit(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exception_type, exception_value, traceback) -> None: ...
    def __repr__(self): ...
    def _set_item(self, index, value) -> None: ...
    def __setitem__(self, index, val) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    @property
    def brightness(self): ...
    @brightness.setter
    def brightness(self, brightness) -> None: ...
    def fill(self, color) -> None: ...
    def show(self) -> None: ...
