from _typeshed import Incomplete as Incomplete
from typing import Any, List, Optional, Tuple, Union

STA_IF: int
AP_IF: int

def hostname(*args, **kwargs) -> Incomplete: ...
def route(*args, **kwargs) -> Incomplete: ...
def country(*args, **kwargs) -> Incomplete: ...
