from _typeshed import Incomplete

_LPS22_CTRL_REG1: Incomplete
_LPS22_CTRL_REG2: Incomplete
_LPS22_STATUS: Incomplete
_LPS22_TEMP_OUT_L: Incomplete
_LPS22_PRESS_OUT_XL: Incomplete
_LPS22_PRESS_OUT_L: Incomplete

class LPS22H:
    i2c: Incomplete
    addr: Incomplete
    oneshot: Incomplete
    buf: Incomplete
    def __init__(self, i2c, address: int = ..., oneshot: bool = ...) -> None: ...
    def _int16(self, d): ...
    def _write_reg(self, reg, dat) -> None: ...
    def _read_reg(self, reg, width: int = ...): ...
    def _tigger_oneshot(self, b) -> None: ...
    def set_oneshot_mode(self, oneshot) -> None: ...
    def pressure(self): ...
    def temperature(self): ...
    def altitude(self): ...
