from typing import Any

class NeoPixel:
    def __init__(self, *args) -> None: ...
    def fill(self, *args) -> Any: ...
    def write(self, *args) -> Any: ...
    ORDER: tuple

class APA106:
    def __init__(self, *args) -> None: ...
    def fill(self, *args) -> Any: ...
    def write(self, *args) -> Any: ...
    ORDER: tuple
