from typing import Any

class ULP:
    def __init__(self, *argv, **kwargs) -> None: ...
    RESERVE_MEM: int
    def load_binary(self, *args, **kwargs) -> Any: ...
    def run(self, *args, **kwargs) -> Any: ...
    def set_wakeup_period(self, *args, **kwargs) -> Any: ...

WAKEUP_ALL_LOW: bool
WAKEUP_ANY_HIGH: bool

def hall_sensor(*args, **kwargs) -> Any: ...
def raw_temperature(*args, **kwargs) -> Any: ...
def wake_on_ext0(*args, **kwargs) -> Any: ...
def wake_on_ext1(*args, **kwargs) -> Any: ...
def wake_on_touch(*args, **kwargs) -> Any: ...
