from typing import Any

Node = Any

class VfsFat:
    def chdir() -> None: ...
    def getcwd() -> None: ...
    def ilistdir() -> None: ...
    def mkdir() -> None: ...
    def mkfs() -> None: ...
    def mount() -> None: ...
    def open() -> None: ...
    def remove() -> None: ...
    def rename() -> None: ...
    def rmdir() -> None: ...
    def stat() -> None: ...
    def statvfs() -> None: ...
    def umount() -> None: ...

def chdir() -> None: ...
def dupterm() -> None: ...
def dupterm_notify() -> None: ...
def getcwd() -> None: ...
def ilistdir() -> None: ...
def listdir() -> None: ...
def mkdir() -> None: ...
def mount() -> None: ...
def remove() -> None: ...
def rename() -> None: ...
def rmdir() -> None: ...
def stat() -> None: ...
def statvfs() -> None: ...
def umount() -> None: ...
def uname() -> None: ...
def urandom() -> None: ...
