from typing import Any

class utimeq:
    def __init__(self, *argv, **kwargs) -> None: ...
    def peektime(self, *args, **kwargs) -> Any: ...
    def pop(self, *args, **kwargs) -> Any: ...
    def push(self, *args, **kwargs) -> Any: ...
