from typing import Any

def cos(*args) -> Any: ...

e: float

def exp(*args) -> Any: ...
def log(*args) -> Any: ...
def log10(*args) -> Any: ...
def phase(*args) -> Any: ...

pi: float

def polar(*args) -> Any: ...
def rect(*args) -> Any: ...
def sin(*args) -> Any: ...
def sqrt(*args) -> Any: ...
