from _typeshed import Incomplete

_PAGE_SIZE: Incomplete
_CMD_RDSR: Incomplete
_CMD_WREN: Incomplete
_CMD_WRITE_32: Incomplete
_CMD_READ_32: Incomplete
_CMD_SEC_ERASE_32: Incomplete
_CMD_C4READ_32: Incomplete

class SPIFlash:
    spi: Incomplete
    cs: Incomplete
    def __init__(self, spi, cs) -> None: ...
    def _wait_wel1(self) -> None: ...
    def _wait_wip0(self) -> None: ...
    def _flash_modify(self, cmd, addr, buf) -> None: ...
    def erase_block(self, addr) -> None: ...
    def readinto(self, addr, buf) -> None: ...
    def write(self, addr, buf) -> None: ...
