
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def _transform() -> None: ...
def a2b_base64() -> None: ...
def a2b_hex() -> None: ...
def b2a_base64() -> None: ...
def b2a_hex() -> None: ...
def crc32() -> None: ...
def hexlify() -> None: ...
def unhexlify() -> None: ...
