class MutableMapping: ...

class OrderedDict:
    def clear() -> None: ...
    def copy() -> None: ...
    def fromkeys() -> None: ...
    def get() -> None: ...
    def items() -> None: ...
    def keys() -> None: ...
    def pop() -> None: ...
    def popitem() -> None: ...
    def setdefault() -> None: ...
    def update() -> None: ...
    def values() -> None: ...

class defaultdict: ...

class deque:
    def append() -> None: ...
    def appendleft() -> None: ...
    def extend() -> None: ...
    def pop() -> None: ...
    def popleft() -> None: ...
    def popright() -> None: ...

def namedtuple() -> None: ...
