
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def init() -> None: ...
def new() -> None: ...
class sha1:
    def digest() -> None: ...
    def update() -> None: ...
class sha224:
    def copy() -> None: ...
    def digest() -> None: ...
    def hexdigest() -> None: ...
    def update() -> None: ...
class sha256:
    def digest() -> None: ...
    def update() -> None: ...
class sha384:
    def copy() -> None: ...
    def digest() -> None: ...
    def hexdigest() -> None: ...
    def update() -> None: ...
class sha512:
    def copy() -> None: ...
    def digest() -> None: ...
    def hexdigest() -> None: ...
    def update() -> None: ...
