from typing import Any

def _heapify_max() -> None: ...
def _heappushpop_max() -> None: ...
def _nlargest() -> None: ...
def _nsmallest() -> None: ...
def _siftdown() -> None: ...
def _siftdown_max() -> None: ...
def _siftup() -> None: ...
def _siftup_max() -> None: ...
def heapify() -> None: ...
def heappop() -> None: ...
def heappush() -> None: ...
def heappushpop() -> None: ...
def heapreplace() -> None: ...

merge: Any

def nlargest() -> None: ...
def nsmallest() -> None: ...
