
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Pin:
    def deinit() -> None: ...
    def value() -> None: ...
class PinBase: ...
class Signal:
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...
class Timer:
    def callback() -> None: ...
    def handler() -> None: ...
def new() -> None: ...
def signal() -> None: ...
def time_pulse_us() -> None: ...
def timer_create() -> None: ...
def timer_settime() -> None: ...
def unique_id() -> None: ...
