
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class mmap:
    def close() -> None: ...
    def read() -> None: ...
    def seek() -> None: ...
    def write() -> None: ...
