
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def getrandbits() -> None: ...
def randint() -> None: ...
def randrange() -> None: ...
def seed() -> None: ...
def shuffle() -> None: ...
