from typing import Any

A: int
ASCII: int
DOTALL: int
I: int
IGNORECASE: int
M: int
MULTILINE: int

class PCREMatch:
    def end() -> None: ...
    def group() -> None: ...
    def groups() -> None: ...
    def span() -> None: ...
    def start() -> None: ...

class PCREPattern:
    def findall() -> None: ...
    def match() -> None: ...
    def search() -> None: ...
    def split() -> None: ...
    def sub() -> None: ...

PCRE_ANCHORED: int
PCRE_INFO_CAPTURECOUNT: int
S: int
U: int
UNICODE: int
VERBOSE: int
X: int
array: Any

def compile() -> None: ...
def escape() -> None: ...

ffilib: Any

def findall() -> None: ...
def match() -> None: ...

pcre: Any
pcre_compile: Any
pcre_exec: Any
pcre_fullinfo: Any

def search() -> None: ...
def split() -> None: ...
def sub() -> None: ...

sys: Any
