
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class PCREMatch:
    def end() -> None: ...
    def group() -> None: ...
    def groups() -> None: ...
    def span() -> None: ...
    def start() -> None: ...
class PCREPattern:
    def findall() -> None: ...
    def match() -> None: ...
    def search() -> None: ...
    def split() -> None: ...
    def sub() -> None: ...
def compile() -> None: ...
def escape() -> None: ...
def findall() -> None: ...
def match() -> None: ...
def search() -> None: ...
def split() -> None: ...
def sub() -> None: ...
