
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def _c_tm_to_tuple() -> None: ...
    def count() -> None: ...
    def index() -> None: ...
def _tuple_to_c_tm() -> None: ...
def clock() -> None: ...
def gmtime() -> None: ...
def localtime() -> None: ...
def mktime() -> None: ...
def namedtuple() -> None: ...
def perf_counter() -> None: ...
def process_time() -> None: ...
def sleep() -> None: ...
def sleep_ms() -> None: ...
def sleep_us() -> None: ...
def strftime() -> None: ...
def struct_time() -> None: ...
def ticks_add() -> None: ...
def ticks_cpu() -> None: ...
def ticks_diff() -> None: ...
def ticks_ms() -> None: ...
def ticks_us() -> None: ...
def time() -> None: ...
