from typing import Any

def _c_tm_to_tuple() -> None: ...

class _struct_time:
    def count() -> None: ...
    def index() -> None: ...

def _tuple_to_c_tm() -> None: ...

array: Any

def clock() -> None: ...

daylight: int
ffi: Any
ffilib: Any

def gmtime() -> None: ...

gmtime_: Any
libc: Any

def localtime() -> None: ...

localtime_: Any

def mktime() -> None: ...

mktime_: Any

def namedtuple() -> None: ...
def perf_counter() -> None: ...
def process_time() -> None: ...
def sleep() -> None: ...
def sleep_ms() -> None: ...
def sleep_us() -> None: ...
def strftime() -> None: ...

strftime_: Any

def struct_time() -> None: ...
def ticks_add() -> None: ...
def ticks_cpu() -> None: ...
def ticks_diff() -> None: ...
def ticks_ms() -> None: ...
def ticks_us() -> None: ...
def time() -> None: ...

timezone: int
uctypes: Any
ustruct: Any
