
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class StopWatch:
    def pause() -> None: ...
    def reset() -> None: ...
    def resume() -> None: ...
    def time() -> None: ...
def wait() -> None: ...
