
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class PinBase: ...
class Signal:
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...
def time_pulse_us() -> None: ...
