from typing import Any

class Bmm150:
    def available(self, *argv) -> Any: ...
    def readData(self, *argv) -> Any: ...
    def readID(self, *argv) -> Any: ...
    def setPowerControlBit(self, *argv) -> Any: ...
    def setSleepMode(self, *argv) -> Any: ...
    def set_normal_mode(self, *argv) -> Any: ...
    def set_op_mode(self, *argv) -> Any: ...
    def set_sleep_mode(self, *argv) -> Any: ...

def const() -> None: ...

i2c_bus: Any
time: Any
