from typing import Any

class Chunk:
    def close(self, *argv) -> Any: ...
    def getname(self, *argv) -> Any: ...
    def getsize(self, *argv) -> Any: ...
    def isatty(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def seek(self, *argv) -> Any: ...
    def skip(self, *argv) -> Any: ...
    def tell(self, *argv) -> Any: ...
