from typing import Any

class ADC:
    ATTN_0DB: int
    ATTN_11DB: int
    ATTN_2_5DB: int
    ATTN_6DB: int
    HALL: int
    WIDTH_10BIT: int
    WIDTH_11BIT: int
    WIDTH_12BIT: int
    WIDTH_9BIT: int
    def atten() -> None: ...
    def collect() -> None: ...
    def collected() -> None: ...
    def deinit() -> None: ...
    def progress() -> None: ...
    def read() -> None: ...
    def read_timed() -> None: ...
    def readraw() -> None: ...
    def stopcollect() -> None: ...
    def vref() -> None: ...
    def width() -> None: ...

class PWM:
    def deinit() -> None: ...
    def duty() -> None: ...
    def freq() -> None: ...
    def init() -> None: ...
    def list() -> None: ...
    def pause() -> None: ...
    def resume() -> None: ...

class Pin:
    IN: int
    INOUT: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    OUT_OD: int
    PULL_DOWN: int
    PULL_FLOAT: int
    PULL_HOLD: int
    PULL_UP: int
    WAKE_HIGH: int
    WAKE_LOW: int
    def deinit() -> None: ...
    def init() -> None: ...
    def irq() -> None: ...
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...

_adc_map: Any

def _deinitIO() -> None: ...

_io_map: Any
_pwm_map: Any

def analogRead() -> None: ...
def analogWrite() -> None: ...
def digitalRead() -> None: ...
def digitalWrite() -> None: ...
def map_value() -> None: ...
def toggleIO() -> None: ...
