from typing import Any

class IMU:
    def _accel_fs(self, *argv) -> Any: ...
    def _gyro_fs(self, *argv) -> Any: ...
    def _register_char(self, *argv) -> Any: ...
    def _register_short(self, *argv) -> Any: ...
    def _register_three_shorts(self, *argv) -> Any: ...
    acceleration: Any
    gyro: Any
    def setGyroOffsets(self, *argv) -> Any: ...
    whoami: Any
    ypr: Any

MPU6050_ADDR: int
SH200Q_ADDR: int
i2c_bus: Any
imu_i2c: Any
mpu6050: Any
