from typing import Any

Node = Any

class Event:
    def clear() -> None: ...
    def is_set() -> None: ...
    def set() -> None: ...

class ThreadSafeFlag:
    def ioctl() -> None: ...
    def set() -> None: ...
