from typing import Any

def pow(*args) -> Any: ...
def acos(*args) -> Any: ...
def asin(*args) -> Any: ...
def atan(*args) -> Any: ...
def atan2(*args) -> Any: ...
def ceil(*args) -> Any: ...
def copysign(*args) -> Any: ...
def cos(*args) -> Any: ...
def degrees(*args) -> Any: ...

e: float

def exp(*args) -> Any: ...
def fabs(*args) -> Any: ...
def floor(*args) -> Any: ...
def fmod(*args) -> Any: ...
def frexp(*args) -> Any: ...
def isfinite(*args) -> Any: ...
def isinf(*args) -> Any: ...
def isnan(*args) -> Any: ...
def ldexp(*args) -> Any: ...
def log(*args) -> Any: ...
def modf(*args) -> Any: ...

pi: float

def radians(*args) -> Any: ...
def sin(*args) -> Any: ...
def sqrt(*args) -> Any: ...
def tan(*args) -> Any: ...
def trunc(*args) -> Any: ...
