
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class SSD1306(framebuf.FrameBuffer):
    def __init__(self, width: Any, height: Any, external_vcc: Any) -> None: ...
    def init_display(self) -> None: ...
    def poweroff(self) -> None: ...
    def poweron(self) -> None: ...
    def contrast(self, contrast: Any) -> None: ...
    def invert(self, invert: Any) -> None: ...
    def show(self) -> None: ...
class SSD1306_I2C(SSD1306):
    def __init__(self, width: Any, height: Any, i2c: Any, addr: Any=, external_vcc: Any=) -> None: ...
    def write_cmd(self, cmd: Any) -> None: ...
    def write_data(self, buf: Any) -> None: ...
class SSD1306_SPI(SSD1306):
    def __init__(self, width: Any, height: Any, spi: Any, dc: Any, res: Any, cs: Any, external_vcc: Any=) -> None: ...
    def write_cmd(self, cmd: Any) -> None: ...
    def write_data(self, buf: Any) -> None: ...
