"""
Module: 'uasyncio.stream' on micropython-v1.28.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.28.0'}
# Stubber: v1.28.0
from __future__ import annotations
from _typeshed import Incomplete

async def stream_awrite(x0, x1, x2, x3) -> Incomplete: ...
async def open_connection(x0, x1, x2, x3) -> Incomplete: ...
async def start_server(x0, x1, x2, x3, x4) -> Incomplete: ...

class StreamWriter:
    def write(self, x1) -> Incomplete: ...
    def get_extra_info(self, x1) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    async def awritestr(self, x1, x2, x3) -> Incomplete: ...
    async def wait_closed(self) -> Incomplete: ...
    async def drain(self) -> Incomplete: ...
    async def readexactly(self, x1) -> Incomplete: ...
    async def readinto(self, x1) -> Incomplete: ...
    async def read(self, x1) -> Incomplete: ...
    async def awrite(self, x1, x2, x3) -> Incomplete: ...
    async def readline(self) -> Incomplete: ...
    async def aclose(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Server:
    def close(self) -> Incomplete: ...
    async def wait_closed(self) -> Incomplete: ...
    async def _serve(self, x1, x2, x3) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Stream:
    def write(self, x1) -> Incomplete: ...
    def get_extra_info(self, x1) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    async def awritestr(self, x1, x2, x3) -> Incomplete: ...
    async def wait_closed(self) -> Incomplete: ...
    async def drain(self) -> Incomplete: ...
    async def readexactly(self, x1) -> Incomplete: ...
    async def readinto(self, x1) -> Incomplete: ...
    async def read(self, x1) -> Incomplete: ...
    async def awrite(self, x1, x2, x3) -> Incomplete: ...
    async def readline(self) -> Incomplete: ...
    async def aclose(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class StreamReader:
    def write(self, x1) -> Incomplete: ...
    def get_extra_info(self, x1) -> Incomplete: ...
    def close(self) -> Incomplete: ...
    async def awritestr(self, x1, x2, x3) -> Incomplete: ...
    async def wait_closed(self) -> Incomplete: ...
    async def drain(self) -> Incomplete: ...
    async def readexactly(self, x1) -> Incomplete: ...
    async def readinto(self, x1) -> Incomplete: ...
    async def read(self, x1) -> Incomplete: ...
    async def awrite(self, x1, x2, x3) -> Incomplete: ...
    async def readline(self) -> Incomplete: ...
    async def aclose(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
