"""
Module: 'esp32' on micropython-v1.26.0-esp32-ESP32_GENERIC_S3
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'board_id': 'ESP32_GENERIC_S3', 'mpy': 'v6.3', 'ver': '1.26.0', 'family': 'micropython', 'cpu': 'ESP32S3', 'version': '1.26.0'}
# Stubber: v1.26.0
from __future__ import annotations
from typing import Final
from _typeshed import Incomplete

WAKEUP_ALL_LOW: Final[bool] = False
WAKEUP_ANY_HIGH: Final[bool] = True
HEAP_EXEC: Final[int] = 1
HEAP_DATA: Final[int] = 4

def wake_on_ulp(*args, **kwargs) -> Incomplete: ...
def idf_heap_info(*args, **kwargs) -> Incomplete: ...
def mcu_temperature(*args, **kwargs) -> Incomplete: ...
def wake_on_touch(*args, **kwargs) -> Incomplete: ...
def wake_on_ext1(*args, **kwargs) -> Incomplete: ...
def wake_on_ext0(*args, **kwargs) -> Incomplete: ...
def gpio_deep_sleep_hold(*args, **kwargs) -> Incomplete: ...

class PCNT:
    IRQ_MIN: Final[int] = 16
    INCREMENT: Final[int] = 1
    IRQ_MAX: Final[int] = 32
    IRQ_ZERO: Final[int] = 64
    IRQ_THRESHOLD0: Final[int] = 8
    IRQ_THRESHOLD1: Final[int] = 4
    NORMAL: Final[int] = 0
    IGNORE: Final[int] = 0
    REVERSE: Final[int] = 1
    DECREMENT: Final[int] = 2
    HOLD: Final[int] = 2
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class NVS:
    def get_i32(self, *args, **kwargs) -> Incomplete: ...
    def set_i32(self, *args, **kwargs) -> Incomplete: ...
    def set_blob(self, *args, **kwargs) -> Incomplete: ...
    def commit(self, *args, **kwargs) -> Incomplete: ...
    def get_blob(self, *args, **kwargs) -> Incomplete: ...
    def erase_key(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ULP:
    RESERVE_MEM: Final[int] = 2040
    def run(self, *args, **kwargs) -> Incomplete: ...
    def set_wakeup_period(self, *args, **kwargs) -> Incomplete: ...
    def load_binary(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Partition:
    RUNNING: Final[int] = 1
    TYPE_APP: Final[int] = 0
    TYPE_DATA: Final[int] = 1
    BOOT: Final[int] = 0
    def readblocks(self, *args, **kwargs) -> Incomplete: ...
    def ioctl(self, *args, **kwargs) -> Incomplete: ...
    def set_boot(self, *args, **kwargs) -> Incomplete: ...
    def writeblocks(self, *args, **kwargs) -> Incomplete: ...
    def info(self, *args, **kwargs) -> Incomplete: ...
    def find(self, *args, **kwargs) -> Incomplete: ...
    def get_next_update(self, *args, **kwargs) -> Incomplete: ...
    @classmethod
    def mark_app_valid_cancel_rollback(cls, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class RMT:
    PULSE_MAX: Final[int] = 32767
    def source_freq(self, *args, **kwargs) -> Incomplete: ...
    def loop(self, *args, **kwargs) -> Incomplete: ...
    def wait_done(self, *args, **kwargs) -> Incomplete: ...
    def write_pulses(self, *args, **kwargs) -> Incomplete: ...
    def bitstream_channel(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def clock_div(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
