"""
Module: 'esp' on micropython-v1.24.0-preview-esp8266-ESP8266_GENERIC
"""

# MCU: {'version': '1.24.0-preview', 'mpy': 'v6.3', 'port': 'esp8266', 'board': 'ESP8266_GENERIC', 'family': 'micropython', 'build': 'preview.62.g908ab1cec', 'arch': 'xtensa', 'ver': '1.24.0-preview-preview.62.g908ab1cec', 'cpu': 'ESP8266'}
# Stubber: v1.20.0
from __future__ import annotations
from _typeshed import Incomplete

SLEEP_MODEM: int = 2
SLEEP_NONE: int = 0
SLEEP_LIGHT: int = 1

def flash_user_start(*args, **kwargs) -> Incomplete: ...
def freemem(*args, **kwargs) -> Incomplete: ...
def free(*args, **kwargs) -> Incomplete: ...
def flash_write(*args, **kwargs) -> Incomplete: ...
def malloc(*args, **kwargs) -> Incomplete: ...
def set_native_code_location(*args, **kwargs) -> Incomplete: ...
def osdebug(*args, **kwargs) -> Incomplete: ...
def meminfo(*args, **kwargs) -> Incomplete: ...
def sleep_type(*args, **kwargs) -> Incomplete: ...
def flash_size(*args, **kwargs) -> Incomplete: ...
def deepsleep(*args, **kwargs) -> Incomplete: ...
def check_fw(*args, **kwargs) -> Incomplete: ...
def apa102_write(*args, **kwargs) -> Incomplete: ...
def esf_free_bufs(*args, **kwargs) -> Incomplete: ...
def flash_read(*args, **kwargs) -> Incomplete: ...
def flash_id(*args, **kwargs) -> Incomplete: ...
def flash_erase(*args, **kwargs) -> Incomplete: ...
