RC: str
CONFIG: str

def input_choice(prompt, choices): ...
def getpass(prompt): ...
def input_pass(): ...
def exists(fname): ...
def copy_stream(s_in, s_out) -> None: ...
def get_daemon_status(): ...
def add_daemon() -> None: ...
def change_daemon(action) -> None: ...
def main() -> None: ...
