"""
Module: 'fnmatch' on micropython-v1.25.0-preview-webassembly
"""

# MCU: {'family': 'micropython', 'version': '1.25.0-preview', 'build': '301', 'ver': '1.25.0-preview-301', 'port': 'webassembly', 'board': '', 'board_id': '', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.26.2
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

def translate(*args, **kwargs) -> Incomplete: ...
def fnmatchcase(*args, **kwargs) -> Incomplete: ...
def normcase(*args, **kwargs) -> Incomplete: ...
def re_escape(*args, **kwargs) -> Incomplete: ...
def fnmatch(*args, **kwargs) -> Incomplete: ...
def filter(*args, **kwargs) -> Incomplete: ...
def _compile_pattern(*args, **kwargs) -> Incomplete: ...
