"""
Module: 'hmac' on micropython-v1.25.0-preview-webassembly
"""

# MCU: {'family': 'micropython', 'version': '1.25.0-preview', 'build': '301', 'ver': '1.25.0-preview-301', 'port': 'webassembly', 'board': '', 'board_id': '', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.26.2
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

def new(*args, **kwargs) -> Incomplete: ...

class HMAC:
    def digest(self, *args, **kwargs) -> Incomplete: ...
    def _current(self, *args, **kwargs) -> Incomplete: ...
    def hexdigest(self, *args, **kwargs) -> Incomplete: ...
    def copy(self, *args, **kwargs) -> Incomplete: ...
    def update(self, *args, **kwargs) -> Incomplete: ...

    name: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...
