"""
Module: 'operator' on micropython-v1.25.0-preview-webassembly
"""

# MCU: {'family': 'micropython', 'version': '1.25.0-preview', 'build': '301', 'ver': '1.25.0-preview-301', 'port': 'webassembly', 'board': '', 'board_id': '', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.26.2
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

def lt(*args, **kwargs) -> Incomplete: ...
def le(*args, **kwargs) -> Incomplete: ...
def truediv(*args, **kwargs) -> Incomplete: ...
def mod(*args, **kwargs) -> Incomplete: ...
def ne(*args, **kwargs) -> Incomplete: ...
def eq(*args, **kwargs) -> Incomplete: ...
def attrgetter(*args, **kwargs) -> Incomplete: ...
def gt(*args, **kwargs) -> Incomplete: ...
def floordiv(*args, **kwargs) -> Incomplete: ...
def ge(*args, **kwargs) -> Incomplete: ...
