"""
Module: 'random' on micropython-v1.24.0-samd-SEEED_WIO_TERMINAL
"""

# MCU: {'version': '1.24.0', 'mpy': 'v6.3', 'port': 'samd', 'board': 'SEEED_WIO_TERMINAL', 'family': 'micropython', 'build': '', 'arch': 'armv7emsp', 'ver': '1.24.0', 'cpu': 'SAMD51P19A'}
# Stubber: v1.23.0
from __future__ import annotations
from _typeshed import Incomplete

def randrange(*args, **kwargs) -> Incomplete: ...
def random(*args, **kwargs) -> Incomplete: ...
def seed(*args, **kwargs) -> Incomplete: ...
def uniform(*args, **kwargs) -> Incomplete: ...
def choice(*args, **kwargs) -> Incomplete: ...
def randint(*args, **kwargs) -> Incomplete: ...
def getrandbits(*args, **kwargs) -> Incomplete: ...
