"""
ESP-NOW asyncio support.

MicroPython module: https://docs.micropython.org/en/latest/library/espnow.html#aioespnow

---
Module: 'aioespnow' on micropython-v1.29.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'ESP32-S2', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from typing import TypeAlias, overload

from _mpy_shed import mp_available
from _typeshed import Incomplete
from espnow import ESPNow

_MACAddress: TypeAlias = bytes

class AIOESPNow(ESPNow):
    """
    Async wrapper around `espnow.ESPNow`.

    This class extends `ESPNow` with async methods and async iteration support.
    """

    _data: list = []
    _none_tuple: tuple = ()
    def peer_count(self) -> Incomplete: ...
    def recv(self, x1) -> Incomplete: ...
    def mod_peer(self, *args, **kwargs) -> Incomplete: ...
    def irecv(self, x1) -> Incomplete: ...
    def stats(self) -> Incomplete: ...
    def recvinto(self, *args, **kwargs) -> Incomplete: ...
    def set_pmk(self, x1) -> Incomplete: ...
    def any(self) -> Incomplete: ...
    def add_peer(self, *args, **kwargs) -> Incomplete: ...
    def active(self, *args, **kwargs) -> Incomplete: ...
    def send(self, *args, **kwargs) -> Incomplete: ...
    def config(self, *args, **kwargs) -> Incomplete: ...
    def get_peers(self) -> Incomplete: ...
    def get_peer(self, x1) -> Incomplete: ...
    def del_peer(self, x1) -> Incomplete: ...
    def irq(self, x1) -> Incomplete: ...
    @overload
    async def asend(self, mac: _MACAddress, msg: str | bytes, sync: bool | None = True) -> bool: ...
    @overload
    async def asend(self, msg: str | bytes) -> bool: ...
    async def arecv(self) -> tuple[_MACAddress | None, bytes | None]:
        """
        Asyncio support for `ESPNow.recv()`.
        """
        ...
    async def airecv(self) -> tuple[_MACAddress | bytearray | None, bytearray | None]:
        """
        Asyncio support for `ESPNow.irecv()`.
        """
        ...
    def __init__(self, *argv, **kwargs) -> None: ...
    @mp_available()
    def __aiter__(self) -> AIOESPNow: ...
    @mp_available()
    async def __anext__(self) -> tuple[_MACAddress | bytearray | None, bytearray | None]: ...
