from typing import Any

class LockType:
    def acquire(self, *argv) -> Any: ...
    def locked(self, *argv) -> Any: ...
    def release(self, *argv) -> Any: ...

def allocate_lock() -> None: ...
def exit() -> None: ...
def get_ident() -> None: ...
def stack_size() -> None: ...
def start_new_thread() -> None: ...
