from typing import Any

class TFT:
    BLACK: int
    BLUE: int
    BMP: int
    BOTTOM: int
    CENTER: int
    COLOR_BITS16: int
    COLOR_BITS24: int
    CYAN: int
    DARKCYAN: int
    DARKGREEN: int
    DARKGREY: int
    FONT_7seg: int
    FONT_Comic: int
    FONT_Default: int
    FONT_DefaultSmall: int
    FONT_DejaVu18: int
    FONT_DejaVu24: int
    FONT_DejaVu40: int
    FONT_DejaVu56: int
    FONT_DejaVu72: int
    FONT_Minya: int
    FONT_Small: int
    FONT_Tooney: int
    FONT_Ubuntu: int
    GREEN: int
    GREENYELLOW: int
    HSPI: int
    JPG: int
    LANDSCAPE: int
    LANDSCAPE_FLIP: int
    LASTX: int
    LASTY: int
    LIGHTGREY: int
    M5STACK: int
    MAGENTA: int
    MAROON: int
    NAVY: int
    OLIVE: int
    ORANGE: int
    PINK: int
    PORTRAIT: int
    PORTRAIT_FLIP: int
    PURPLE: int
    RED: int
    RIGHT: int
    VSPI: int
    WHITE: int
    YELLOW: int
    def arc(self, *argv) -> Any: ...
    def attrib7seg(self, *argv) -> Any: ...
    def backlight(self, *argv) -> Any: ...
    def circle(self, *argv) -> Any: ...
    def clear(self, *argv) -> Any: ...
    def clearwin(self, *argv) -> Any: ...
    def compileFont(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def drawCircle(self, *argv) -> Any: ...
    def drawLine(self, *argv) -> Any: ...
    def drawPixel(self, *argv) -> Any: ...
    def drawRect(self, *argv) -> Any: ...
    def drawRoundRect(self, *argv) -> Any: ...
    def drawTriangle(self, *argv) -> Any: ...
    def ellipse(self, *argv) -> Any: ...
    def fill(self, *argv) -> Any: ...
    def fillCircle(self, *argv) -> Any: ...
    def fillRect(self, *argv) -> Any: ...
    def fillRoundRect(self, *argv) -> Any: ...
    def fillScreen(self, *argv) -> Any: ...
    def fillTriangle(self, *argv) -> Any: ...
    def font(self, *argv) -> Any: ...
    def fontSize(self, *argv) -> Any: ...
    def getCursor(self, *argv) -> Any: ...
    def get_bg(self, *argv) -> Any: ...
    def get_fg(self, *argv) -> Any: ...
    def hsb2rgb(self, *argv) -> Any: ...
    def image(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def line(self, *argv) -> Any: ...
    def lineByAngle(self, *argv) -> Any: ...
    def orient(self, *argv) -> Any: ...
    def pixel(self, *argv) -> Any: ...
    def polygon(self, *argv) -> Any: ...
    def print(self, *argv) -> Any: ...
    def println(self, *argv) -> Any: ...
    def qrcode(self, *argv) -> Any: ...
    def rect(self, *argv) -> Any: ...
    def resetwin(self, *argv) -> Any: ...
    def restorewin(self, *argv) -> Any: ...
    def roundrect(self, *argv) -> Any: ...
    def savewin(self, *argv) -> Any: ...
    def screensize(self, *argv) -> Any: ...
    def setBrightness(self, *argv) -> Any: ...
    def setColor(self, *argv) -> Any: ...
    def setCursor(self, *argv) -> Any: ...
    def setRotation(self, *argv) -> Any: ...
    def setTextColor(self, *argv) -> Any: ...
    def set_bg(self, *argv) -> Any: ...
    def set_fg(self, *argv) -> Any: ...
    def setwin(self, *argv) -> Any: ...
    def text(self, *argv) -> Any: ...
    def textClear(self, *argv) -> Any: ...
    def textWidth(self, *argv) -> Any: ...
    def text_x(self, *argv) -> Any: ...
    def text_y(self, *argv) -> Any: ...
    def tft_deselect(self, *argv) -> Any: ...
    def tft_readcmd(self, *argv) -> Any: ...
    def tft_select(self, *argv) -> Any: ...
    def tft_setspeed(self, *argv) -> Any: ...
    def tft_writecmd(self, *argv) -> Any: ...
    def tft_writecmddata(self, *argv) -> Any: ...
    def triangle(self, *argv) -> Any: ...
    def winsize(self, *argv) -> Any: ...
