from typing import Any

class ULP:
    RESERVE_MEM: int
    def load_binary(self, *argv) -> Any: ...
    def run(self, *argv) -> Any: ...
    def set_wakeup_period(self, *argv) -> Any: ...

WAKEUP_ALL_LOW: Any
WAKEUP_ANY_HIGH: Any

def hall_sensor() -> None: ...
def raw_temperature() -> None: ...
def wake_on_ext0() -> None: ...
def wake_on_ext1() -> None: ...
def wake_on_touch() -> None: ...
