from typing import Any

class ADC:
    ATTN_0DB: int
    ATTN_11DB: int
    ATTN_2_5DB: int
    ATTN_6DB: int
    HALL: int
    WIDTH_10BIT: int
    WIDTH_11BIT: int
    WIDTH_12BIT: int
    WIDTH_9BIT: int
    def atten(self, *argv) -> Any: ...
    def collect(self, *argv) -> Any: ...
    def collected(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def progress(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def read_timed(self, *argv) -> Any: ...
    def readraw(self, *argv) -> Any: ...
    def stopcollect(self, *argv) -> Any: ...
    def vref(self, *argv) -> Any: ...
    def width(self, *argv) -> Any: ...

class DAC:
    CIRCULAR: int
    NOISE: int
    NORMAL: int
    RAMP: int
    SAWTOOTH: int
    SINE: int
    TRIANGLE: int
    def beep(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def freq(self, *argv) -> Any: ...
    def stopwave(self, *argv) -> Any: ...
    def waveform(self, *argv) -> Any: ...
    def wavplay(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...
    def write_buffer(self, *argv) -> Any: ...
    def write_timed(self, *argv) -> Any: ...

DEEPSLEEP: int
DEEPSLEEP_RESET: int
EXT0_WAKE: int
EXT1_WAKE: int
HARD_RESET: int

class I2C:
    CBTYPE_ADDR: int
    CBTYPE_NONE: int
    CBTYPE_RXDATA: int
    CBTYPE_TXDATA: int
    MASTER: int
    READ: int
    SLAVE: int
    WRITE: int
    def address(self, *argv) -> Any: ...
    def begin(self, *argv) -> Any: ...
    def callback(self, *argv) -> Any: ...
    def clock_timing(self, *argv) -> Any: ...
    def data_timing(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def end(self, *argv) -> Any: ...
    def getdata(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def is_ready(self, *argv) -> Any: ...
    def read_byte(self, *argv) -> Any: ...
    def read_bytes(self, *argv) -> Any: ...
    def readfrom(self, *argv) -> Any: ...
    def readfrom_into(self, *argv) -> Any: ...
    def readfrom_mem(self, *argv) -> Any: ...
    def readfrom_mem_into(self, *argv) -> Any: ...
    def resetbusy(self, *argv) -> Any: ...
    def scan(self, *argv) -> Any: ...
    def setdata(self, *argv) -> Any: ...
    def start(self, *argv) -> Any: ...
    def start_timing(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...
    def stop_timing(self, *argv) -> Any: ...
    def timeout(self, *argv) -> Any: ...
    def write_byte(self, *argv) -> Any: ...
    def write_bytes(self, *argv) -> Any: ...
    def writeto(self, *argv) -> Any: ...
    def writeto_mem(self, *argv) -> Any: ...

class I2S:
    CHANNEL_ALL_LEFT: int
    CHANNEL_ALL_RIGHT: int
    CHANNEL_ONLY_LEFT: int
    CHANNEL_ONLY_RIGHT: int
    CHANNEL_RIGHT_LEFT: int
    DAC_BOTH_EN: int
    DAC_DISABLE: int
    DAC_LEFT_EN: int
    DAC_RIGHT_EN: int
    FORMAT_I2S: int
    FORMAT_I2S_LSB: int
    FORMAT_I2S_MSB: int
    FORMAT_PCM: int
    FORMAT_PCM_LONG: int
    FORMAT_PCM_SHORT: int
    I2S_NUM_0: int
    I2S_NUM_1: int
    MODE_ADC_BUILT_IN: int
    MODE_DAC_BUILT_IN: int
    MODE_MASTER: int
    MODE_PDM: int
    MODE_RX: int
    MODE_SLAVE: int
    MODE_TX: int
    def adc_enable(self, *argv) -> Any: ...
    def bits(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def nchannels(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def sample_rate(self, *argv) -> Any: ...
    def set_adc_pin(self, *argv) -> Any: ...
    def set_dac_mode(self, *argv) -> Any: ...
    def set_pin(self, *argv) -> Any: ...
    def start(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...
    def volume(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...

class Neopixel:
    BLACK: int
    BLUE: int
    CYAN: int
    GRAY: int
    GREEN: int
    def HSBtoRGB(self, *argv) -> Any: ...
    def HSBtoRGBint(self, *argv) -> Any: ...
    LIME: int
    MAGENTA: int
    MAROON: int
    NAVY: int
    OLIVE: int
    PURPLE: int
    RED: int
    def RGBtoHSB(self, *argv) -> Any: ...
    SILVER: int
    TEAL: int
    TYPE_RGB: int
    TYPE_RGBW: int
    WHITE: int
    YELLOW: int
    def brightness(self, *argv) -> Any: ...
    def clear(self, *argv) -> Any: ...
    def color_order(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def get(self, *argv) -> Any: ...
    def info(self, *argv) -> Any: ...
    def rainbow(self, *argv) -> Any: ...
    def set(self, *argv) -> Any: ...
    def setHSB(self, *argv) -> Any: ...
    def setHSBint(self, *argv) -> Any: ...
    def setWhite(self, *argv) -> Any: ...
    def show(self, *argv) -> Any: ...
    def timings(self, *argv) -> Any: ...

PIN_WAKE: int

class PWM:
    def deinit(self, *argv) -> Any: ...
    def duty(self, *argv) -> Any: ...
    def freq(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def list(self, *argv) -> Any: ...
    def pause(self, *argv) -> Any: ...
    def resume(self, *argv) -> Any: ...

PWRON_RESET: int

class Pin:
    IN: int
    INOUT: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    OUT_OD: int
    PULL_DOWN: int
    PULL_FLOAT: int
    PULL_HOLD: int
    PULL_UP: int
    WAKE_HIGH: int
    WAKE_LOW: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def irq(self, *argv) -> Any: ...
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

class RTC:
    def datetime(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def memory(self, *argv) -> Any: ...

SLEEP: int
SOFT_RESET: int

class Signal:
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

TIMER_WAKE: int
TOUCHPAD_WAKE: int

class Timer:
    ONE_SHOT: int
    PERIODIC: int
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

class TouchPad:
    def config(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...

class UART:
    def any(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def init(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def readline(self, *argv) -> Any: ...
    def sendbreak(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...

ULP_WAKE: int

class WDT:
    def feed(self, *argv) -> Any: ...

WDT_RESET: int

def deepsleep() -> None: ...
def disable_irq() -> None: ...
def enable_irq() -> None: ...
def freq() -> None: ...
def heap_info() -> None: ...
def idle() -> None: ...
def lightsleep() -> None: ...

mem16: Any
mem32: Any
mem8: Any

def nvs_erase() -> None: ...
def nvs_erase_all() -> None: ...
def nvs_getint() -> None: ...
def nvs_getstr() -> None: ...
def nvs_setint() -> None: ...
def nvs_setstr() -> None: ...
def random() -> None: ...
def reset() -> None: ...
def reset_cause() -> None: ...
def sleep() -> None: ...
def time_pulse_us() -> None: ...
def unique_id() -> None: ...
def wake_reason() -> None: ...
