from typing import Any

class MicroWebSocket:
    def Close() -> None: ...
    def IsClosed() -> None: ...
    def SendBinary() -> None: ...
    def SendText() -> None: ...
    def _handshake() -> None: ...
    _handshakeSign: str
    _msgTypeBin: int
    _msgTypeText: int
    _opBinFrame: int
    _opCloseFrame: int
    _opContFrame: int
    _opPingFrame: int
    _opPongFrame: int
    _opTextFrame: int
    def _receiveFrame() -> None: ...
    def _sendFrame() -> None: ...
    def _tryAllocByteArray() -> None: ...
    def _tryStartThread() -> None: ...
    def _wsProcess() -> None: ...
    def threadID() -> None: ...

_thread: Any

def b2a_base64() -> None: ...

gc: Any

def pack() -> None: ...

class sha1:
    def digest() -> None: ...
    def update() -> None: ...

time: Any
