from typing import Any

class MicroWebSocket:
    def Close() -> None: ...
    def IsClosed() -> None: ...
    def SendBinary() -> None: ...
    def SendText() -> None: ...
    def _handshake() -> None: ...
    _handshakeSign: str
    _msgTypeBin: int
    _msgTypeText: int
    _opBinFrame: int
    _opCloseFrame: int
    _opContFrame: int
    _opPingFrame: int
    _opPongFrame: int
    _opTextFrame: int
    def _receiveFrame() -> None: ...
    def _sendFrame() -> None: ...
    def _tryAllocByteArray() -> None: ...
    def _tryStartThread() -> None: ...
    def _wsProcess() -> None: ...
    def threadID() -> None: ...

class MicroWebSrv:
    def GetMimeTypeFromFilename() -> None: ...
    def GetRouteHandler() -> None: ...
    def HTMLEscape() -> None: ...
    def IsStarted() -> None: ...
    def SetNotFoundPageUrl() -> None: ...
    def Start() -> None: ...
    def State() -> None: ...
    def Stop() -> None: ...
    _client: Any
    _docoratedRouteHandlers: Any
    def _fileExists() -> None: ...
    _html_escape_chars: Any
    _indexPages: Any
    def _isPyHTMLFile() -> None: ...
    _mimeTypes: Any
    def _physPathFromURLPath() -> None: ...
    _pyhtmlPagesExt: str
    _response: Any
    def _serverProcess() -> None: ...
    def _tryAllocByteArray() -> None: ...
    def _tryStartThread() -> None: ...
    def _unquote() -> None: ...
    def _unquote_plus() -> None: ...
    def route() -> None: ...
    def threadID() -> None: ...

class MicroWebSrvRoute: ...

class MicroWebTemplate:
    def Execute() -> None: ...
    INSTRUCTION_ELIF: str
    INSTRUCTION_ELSE: str
    INSTRUCTION_END: str
    INSTRUCTION_FOR: str
    INSTRUCTION_IF: str
    INSTRUCTION_INCLUDE: str
    INSTRUCTION_PYTHON: str
    TOKEN_CLOSE: str
    TOKEN_CLOSE_LEN: int
    TOKEN_OPEN: str
    TOKEN_OPEN_LEN: int
    def Validate() -> None: ...
    def _parseBloc() -> None: ...
    def _parseCode() -> None: ...
    def _processInstructionELIF() -> None: ...
    def _processInstructionELSE() -> None: ...
    def _processInstructionEND() -> None: ...
    def _processInstructionFOR() -> None: ...
    def _processInstructionIF() -> None: ...
    def _processInstructionINCLUDE() -> None: ...
    def _processInstructionPYTHON() -> None: ...
    def _processToken() -> None: ...

_thread: Any

def dumps() -> None: ...

gc: Any

def loads() -> None: ...

network: Any
re: Any
socket: Any

def stat() -> None: ...

time: Any
