SDMODE_1LINE: int
SDMODE_4LINE: int
SDMODE_SPI: int

def chdir() -> None: ...
def dupterm() -> None: ...
def dupterm_notify() -> None: ...
def getcwd() -> None: ...
def getdrive() -> None: ...
def ilistdir() -> None: ...
def listdir() -> None: ...
def mkdir() -> None: ...
def mountsd() -> None: ...
def remove() -> None: ...
def rename() -> None: ...
def rmdir() -> None: ...
def sdconfig() -> None: ...
def stat() -> None: ...
def statvfs() -> None: ...
def umountsd() -> None: ...
def uname() -> None: ...
def urandom() -> None: ...
