from typing import Any

DIRTYPE: str

class FileSection:
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def skip(self, *argv) -> Any: ...

REGTYPE: str
TAR_HEADER: Any

class TarFile:
    def extractfile(self, *argv) -> Any: ...
    def next(self, *argv) -> Any: ...

class TarInfo: ...

def roundup() -> None: ...

uctypes: Any
