from typing import Any

DIRTYPE: str

class FileSection:
    def read() -> None: ...
    def readinto() -> None: ...
    def skip() -> None: ...

REGTYPE: str
TAR_HEADER: Any

class TarFile:
    def extractfile() -> None: ...
    def next() -> None: ...

class TarInfo: ...

def roundup() -> None: ...

uctypes: Any
