"""
Module: 'mip.__init__' on micropython-v1.24.1-rp2-ARDUINO_NANO_RP2040_CONNECT
"""

# MCU: {'family': 'micropython', 'version': '1.24.1', 'build': '', 'ver': '1.24.1', 'port': 'rp2', 'board': 'ARDUINO_NANO_RP2040_CONNECT', 'cpu': 'RP2040', 'mpy': 'v6.3', 'arch': 'armv6m'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

_CHUNK_SIZE: int = 128

def _ensure_path_exists(*args, **kwargs) -> Incomplete: ...
def _download_file(*args, **kwargs) -> Incomplete: ...
def _install_json(*args, **kwargs) -> Incomplete: ...
def _install_package(*args, **kwargs) -> Incomplete: ...
def _rewrite_url(*args, **kwargs) -> Incomplete: ...
def _chunk(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...
def install(*args, **kwargs) -> Incomplete: ...
def _check_exists(*args, **kwargs) -> Incomplete: ...
