from _typeshed import Incomplete as Incomplete

def const(*args, **kwargs) -> Incomplete: ...

class LSM6DSOX:
    def mlc_output(self, *args, **kwargs) -> Incomplete: ...
    def load_mlc(self, *args, **kwargs) -> Incomplete: ...
    def set_embedded_functions(self, *args, **kwargs) -> Incomplete: ...
    def set_mem_bank(self, *args, **kwargs) -> Incomplete: ...
    def reset(self, *args, **kwargs) -> Incomplete: ...
    def gyro(self, *args, **kwargs) -> Incomplete: ...
    def accel(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
