from typing import Any

class MQTTClient:
    def _recv_len() -> None: ...
    def _send_str() -> None: ...
    def check_msg() -> None: ...
    def connect() -> None: ...
    def disconnect() -> None: ...
    def ping() -> None: ...
    def publish() -> None: ...
    def set_callback() -> None: ...
    def set_last_will() -> None: ...
    def subscribe() -> None: ...
    def wait_msg() -> None: ...

class MQTTException: ...

def hexlify() -> None: ...

socket: Any
struct: Any
