"""
Pyscript 2025.2.3 type-stub.
see: https://docs.pyscript.net/2025.2.3/api/
"""

mounted = ...

async def mount(path, mode=..., root=..., id=...) -> None: ...
async def sync(path) -> None: ...
async def unmount(path) -> None: ...
