from typing import Any

class Lock:
    def __init__(self, *argv) -> None: ...
    def __init__(self, *args) -> None: ...
    def release(self, *args) -> Any: ...
    def locked(self, *args) -> Any: ...
    acquire: Any
