"""
Module: 'datetime' on micropython-v1.28.0-unix-standard
"""

# MCU: {'family': 'micropython', 'version': '1.28.0', 'build': '', 'ver': '1.28.0', 'port': 'unix', 'board': 'standard', 'board_id': 'standard', 'variant': '', 'cpu': 'linux [GCC 12.5.0] version', 'mpy': 'v6.3', 'arch': 'x64'}
# Stubber: v1.28.3
from __future__ import annotations
from typing import Any, Final, Generator, AsyncGenerator
from _typeshed import Incomplete

MINYEAR: Final[int] = 1
MAXYEAR: Final[int] = 9999

def _date(*args, **kwargs) -> Incomplete: ...
def _iso2t(*args, **kwargs) -> Incomplete: ...
def _time(*args, **kwargs) -> Incomplete: ...
def _iso2d(*args, **kwargs) -> Incomplete: ...
def _d2iso(*args, **kwargs) -> Incomplete: ...
def _t2iso(*args, **kwargs) -> Incomplete: ...
def _dim(*args, **kwargs) -> Incomplete: ...
def _o2ymd(*args, **kwargs) -> Incomplete: ...
def _leap(*args, **kwargs) -> Incomplete: ...
def _dbm(*args, **kwargs) -> Incomplete: ...

class date:
    def isoformat(self, *args, **kwargs) -> Incomplete: ...
    def toordinal(self, *args, **kwargs) -> Incomplete: ...
    def timetuple(self, *args, **kwargs) -> Incomplete: ...
    def weekday(self, *args, **kwargs) -> Incomplete: ...
    def isoweekday(self, *args, **kwargs) -> Incomplete: ...
    def tuple(self, *args, **kwargs) -> Incomplete: ...
    def replace(self, *args, **kwargs) -> Incomplete: ...

    min: Incomplete  ## <class 'date'> = datetime.date(0, 0, 1)
    @classmethod
    def fromordinal(cls, *args, **kwargs) -> Incomplete: ...
    @classmethod
    def fromisoformat(cls, *args, **kwargs) -> Incomplete: ...

    max: Incomplete  ## <class 'date'> = datetime.date(0, 0, 3652059)
    year: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def today(cls, *args, **kwargs) -> Incomplete: ...

    resolution: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=86400000000)
    @classmethod
    def fromtimestamp(cls, *args, **kwargs) -> Incomplete: ...

    month: Incomplete  ## <class 'property'> = <property>
    day: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...

class time:
    def isoformat(self, *args, **kwargs) -> Incomplete: ...
    def tzname(self, *args, **kwargs) -> Incomplete: ...
    def utcoffset(self, *args, **kwargs) -> Incomplete: ...
    def dst(self, *args, **kwargs) -> Incomplete: ...
    def _sub(self, *args, **kwargs) -> Incomplete: ...
    def replace(self, *args, **kwargs) -> Incomplete: ...
    def tuple(self, *args, **kwargs) -> Incomplete: ...

    hour: Incomplete  ## <class 'property'> = <property>
    min: Incomplete  ## <class 'time'> = datetime.time(microsecond=0, tzinfo=None, fold=0)
    microsecond: Incomplete  ## <class 'property'> = <property>
    minute: Incomplete  ## <class 'property'> = <property>
    second: Incomplete  ## <class 'property'> = <property>
    tzinfo: Incomplete  ## <class 'property'> = <property>
    resolution: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=1)
    fold: Incomplete  ## <class 'property'> = <property>
    max: Incomplete  ## <class 'time'> = datetime.time(microsecond=86399999999, tzinfo=None, fold=0)
    @classmethod
    def fromisoformat(cls, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class tzinfo:
    def utcoffset(self, *args, **kwargs) -> Incomplete: ...
    def dst(self, *args, **kwargs) -> Incomplete: ...
    def fromutc(self, *args, **kwargs) -> Incomplete: ...
    def tzname(self, *args, **kwargs) -> Incomplete: ...
    def isoformat(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class timezone:
    def utcoffset(self, *args, **kwargs) -> Incomplete: ...
    def dst(self, *args, **kwargs) -> Incomplete: ...
    def fromutc(self, *args, **kwargs) -> Incomplete: ...
    def tzname(self, *args, **kwargs) -> Incomplete: ...
    def isoformat(self, *args, **kwargs) -> Incomplete: ...

    utc: Incomplete  ## <class 'timezone'> = datetime.timezone(datetime.timedelta(microseconds=0), None)
    def __init__(self, *argv, **kwargs) -> None: ...

class datetime:
    def weekday(self, *args, **kwargs) -> Incomplete: ...
    def isoweekday(self, *args, **kwargs) -> Incomplete: ...
    def timestamp(self, *args, **kwargs) -> Incomplete: ...
    def timetuple(self, *args, **kwargs) -> Incomplete: ...
    def toordinal(self, *args, **kwargs) -> Incomplete: ...
    def astimezone(self, *args, **kwargs) -> Incomplete: ...
    def _mktime(self, *args, **kwargs) -> Incomplete: ...
    def _sub(self, *args, **kwargs) -> Incomplete: ...
    def timetz(self, *args, **kwargs) -> Incomplete: ...
    def _cmp(self, *args, **kwargs) -> Incomplete: ...
    def utcoffset(self, *args, **kwargs) -> Incomplete: ...
    def isoformat(self, *args, **kwargs) -> Incomplete: ...
    def date(self, *args, **kwargs) -> Incomplete: ...
    def dst(self, *args, **kwargs) -> Incomplete: ...
    def time(self, *args, **kwargs) -> Incomplete: ...
    def tzname(self, *args, **kwargs) -> Incomplete: ...
    def replace(self, *args, **kwargs) -> Incomplete: ...
    def tuple(self, *args, **kwargs) -> Incomplete: ...
    @classmethod
    def now(cls, *args, **kwargs) -> Incomplete: ...

    tzinfo: Incomplete  ## <class 'property'> = <property>
    microsecond: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def combine(cls, *args, **kwargs) -> Incomplete: ...

    EPOCH: Incomplete  ## <class 'datetime'> = datetime.datetime(1970, 1, 1, 0, 0, 0, 0, datetime.timezone(datetime.timedelta(microseconds=0), None), fold=0)
    year: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromordinal(cls, *args, **kwargs) -> Incomplete: ...
    @classmethod
    def fromtimestamp(cls, *args, **kwargs) -> Incomplete: ...

    day: Incomplete  ## <class 'property'> = <property>
    month: Incomplete  ## <class 'property'> = <property>
    second: Incomplete  ## <class 'property'> = <property>
    @classmethod
    def fromisoformat(cls, *args, **kwargs) -> Incomplete: ...

    minute: Incomplete  ## <class 'property'> = <property>
    hour: Incomplete  ## <class 'property'> = <property>
    fold: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...

class timedelta:
    def _fmt(self, *args, **kwargs) -> Incomplete: ...
    def _tuple(self, *args, **kwargs) -> Incomplete: ...
    def total_seconds(self, *args, **kwargs) -> Incomplete: ...
    def isoformat(self, *args, **kwargs) -> Incomplete: ...
    def tuple(self, *args, **kwargs) -> Incomplete: ...

    resolution: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=1)
    min: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=-86399999913600000000)
    max: Incomplete  ## <class 'timedelta'> = datetime.timedelta(microseconds=86399999999999999999)
    microseconds: Incomplete  ## <class 'property'> = <property>
    days: Incomplete  ## <class 'property'> = <property>
    seconds: Incomplete  ## <class 'property'> = <property>
    def __init__(self, *argv, **kwargs) -> None: ...
