from _typeshed import Incomplete

class defaultdict:
    d: Incomplete
    @staticmethod
    def __new__(cls, default_factory=None, **kwargs): ...
    default_factory: Incomplete
    def __init__(self, default_factory=None, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, v) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __missing__(self, key): ...
