from typing import Any

class Task:
    def __init__(self, *argv) -> None: ...

class TaskQueue:
    def __init__(self, *argv) -> None: ...
    def remove(self, *args) -> Any: ...
    def peek(self, *args) -> Any: ...
    def pop_head(self, *args) -> Any: ...
    def push_head(self, *args) -> Any: ...
    def push_sorted(self, *args) -> Any: ...
