from typing import Any

AF_INET: int
AF_INET6: int
SOCK_DGRAM: int
SOCK_RAW: int
SOCK_STREAM: int

def getaddrinfo(*args) -> Any: ...

class socket:
    def __init__(self, *argv) -> None: ...
    def close(self, *args) -> Any: ...
    def read(self, *args) -> Any: ...
    def readinto(self, *args) -> Any: ...
    def readline(self, *args) -> Any: ...
    def send(self, *args) -> Any: ...
    def write(self, *args) -> Any: ...
    def accept(self, *args) -> Any: ...
    def bind(self, *args) -> Any: ...
    def connect(self, *args) -> Any: ...
    def listen(self, *args) -> Any: ...
    def recv(self, *args) -> Any: ...
    def recvfrom(self, *args) -> Any: ...
    def sendto(self, *args) -> Any: ...
    def setblocking(self, *args) -> Any: ...
    def setsockopt(self, *args) -> Any: ...
    def settimeout(self, *args) -> Any: ...
