from typing import Any

class array:
    def __init__(self, *argv) -> None: ...
    def append(self, *args) -> Any: ...
    def extend(self, *args) -> Any: ...
    def decode(self, *args) -> Any: ...
