from typing import Any

class DecompIO:
    def __init__(self, *argv) -> None: ...
    def read(self, *args) -> Any: ...
    def readinto(self, *args) -> Any: ...
    def readline(self, *args) -> Any: ...

def decompress(*args) -> Any: ...
