"""
Module: 'mip.__init__' on micropython-v1.25.0-rp2-RPI_PICO2_W
"""

# MCU: {'build': '', 'ver': '1.25.0', 'version': '1.25.0', 'port': 'rp2', 'board': 'RPI_PICO2_W', 'mpy': 'v6.3', 'family': 'micropython', 'cpu': 'RP2350', 'arch': 'armv7emsp'}
# Stubber: v1.24.0
from __future__ import annotations
from typing import Final
from _typeshed import Incomplete

allowed_mip_url_prefixes: tuple = ()
_CHUNK_SIZE: Final[int] = 128

def _ensure_path_exists(*args, **kwargs) -> Incomplete: ...
def _install_json(*args, **kwargs) -> Incomplete: ...
def _install_package(*args, **kwargs) -> Incomplete: ...
def _rewrite_url(*args, **kwargs) -> Incomplete: ...
def install(*args, **kwargs) -> Incomplete: ...
def _download_file(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...
def _check_exists(*args, **kwargs) -> Incomplete: ...
def _chunk(*args, **kwargs) -> Incomplete: ...
