"""
Module: 'machine' on micropython-v1.26.1-mimxrt-SEEED_ARCH_MIX
"""

# MCU: {'variant': '', 'build': '', 'arch': 'armv7emdp', 'port': 'mimxrt', 'board': 'SEEED_ARCH_MIX', 'board_id': 'SEEED_ARCH_MIX', 'mpy': 'v6.3', 'ver': '1.26.1', 'family': 'micropython', 'cpu': 'MIMXRT1052DVL5B', 'version': '1.26.1'}
# Stubber: v1.26.3
from __future__ import annotations
from typing import Final
from _typeshed import Incomplete

SOFT_RESET: Final[int] = 5
PWRON_RESET: Final[int] = 1
WDT_RESET: Final[int] = 3

def unique_id(*args, **kwargs) -> Incomplete: ...
def disable_irq(*args, **kwargs) -> Incomplete: ...
def dht_readinto(*args, **kwargs) -> Incomplete: ...
def bitstream(*args, **kwargs) -> Incomplete: ...
def bootloader(*args, **kwargs) -> Incomplete: ...
def deepsleep(*args, **kwargs) -> Incomplete: ...
def enable_irq(*args, **kwargs) -> Incomplete: ...
def reset_cause(*args, **kwargs) -> Incomplete: ...
def soft_reset(*args, **kwargs) -> Incomplete: ...
def time_pulse_us(*args, **kwargs) -> Incomplete: ...
def reset(*args, **kwargs) -> Incomplete: ...
def freq(*args, **kwargs) -> Incomplete: ...
def idle(*args, **kwargs) -> Incomplete: ...
def lightsleep(*args, **kwargs) -> Incomplete: ...

mem8: Incomplete  ## <class 'mem'> = <8-bit memory>
mem32: Incomplete  ## <class 'mem'> = <32-bit memory>
mem16: Incomplete  ## <class 'mem'> = <16-bit memory>

class LED:
    def on(self, *args, **kwargs) -> Incomplete: ...
    def toggle(self, *args, **kwargs) -> Incomplete: ...
    def off(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class PWM:
    def duty_u16(self, *args, **kwargs) -> Incomplete: ...
    def freq(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def duty_ns(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2S:
    RX: Final[int] = 0
    MONO: Final[int] = 0
    STEREO: Final[int] = 1
    TX: Final[int] = 1
    def shift(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ADC:
    def read_uv(self, *args, **kwargs) -> Incomplete: ...
    def read_u16(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_mem(self, *args, **kwargs) -> Incomplete: ...
    def writeto_mem(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def writeto(self, *args, **kwargs) -> Incomplete: ...
    def writevto(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def readfrom(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2CTarget:
    IRQ_END_READ: Final[int] = 16
    IRQ_ADDR_MATCH_WRITE: Final[int] = 2
    IRQ_END_WRITE: Final[int] = 32
    IRQ_READ_REQ: Final[int] = 4
    IRQ_ADDR_MATCH_READ: Final[int] = 1
    IRQ_WRITE_REQ: Final[int] = 8
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class UART:
    INV_TX: Final[int] = 1
    INV_RX: Final[int] = 2
    CTS: Final[int] = 2
    IRQ_RXIDLE: Final[int] = 1
    IRQ_TXIDLE: Final[int] = 2
    RTS: Final[int] = 1
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def sendbreak(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def flush(self, *args, **kwargs) -> Incomplete: ...
    def txdone(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def any(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def readline(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SoftI2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_mem(self, *args, **kwargs) -> Incomplete: ...
    def writeto_mem(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def writeto(self, *args, **kwargs) -> Incomplete: ...
    def writevto(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def readfrom(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SoftSPI:
    LSB: Final[int] = 1
    MSB: Final[int] = 0
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write_readinto(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Timer:
    PERIODIC: Final[int] = 2
    ONE_SHOT: Final[int] = 1
    def init(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class WDT:
    def timeout_ms(self, *args, **kwargs) -> Incomplete: ...
    def feed(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Pin:
    OPEN_DRAIN: Final[int] = 2
    IRQ_RISING: Final[int] = 1
    IRQ_FALLING: Final[int] = 2
    IN: Final[int] = 0
    PULL_UP_22K: Final[int] = 3
    OUT: Final[int] = 1
    PULL_UP: Final[int] = 2
    PULL_HOLD: Final[int] = 5
    PULL_DOWN: Final[int] = 0
    DRIVE_2: Final[int] = 3
    DRIVE_1: Final[int] = 2
    DRIVE_0: Final[int] = 1
    PULL_UP_47K: Final[int] = 1
    DRIVE_OFF: Final[int] = 0
    DRIVE_3: Final[int] = 4
    DRIVE_6: Final[int] = 7
    DRIVE_5: Final[int] = 6
    DRIVE_4: Final[int] = 5
    def low(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def toggle(self, *args, **kwargs) -> Incomplete: ...
    def off(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def high(self, *args, **kwargs) -> Incomplete: ...

    class cpu:
        GPIO_EMC_16: Pin  ## = Pin(GPIO_EMC_16)
        GPIO_EMC_15: Pin  ## = Pin(GPIO_EMC_15)
        GPIO_EMC_17: Pin  ## = Pin(GPIO_EMC_17)
        GPIO_EMC_18: Pin  ## = Pin(GPIO_EMC_18)
        GPIO_EMC_12: Pin  ## = Pin(GPIO_EMC_12)
        GPIO_EMC_14: Pin  ## = Pin(GPIO_EMC_14)
        GPIO_EMC_13: Pin  ## = Pin(GPIO_EMC_13)
        WAKEUP: Pin  ## = Pin(WAKEUP)
        GPIO_EMC_24: Pin  ## = Pin(GPIO_EMC_24)
        GPIO_EMC_23: Pin  ## = Pin(GPIO_EMC_23)
        GPIO_EMC_25: Pin  ## = Pin(GPIO_EMC_25)
        GPIO_EMC_19: Pin  ## = Pin(GPIO_EMC_19)
        GPIO_EMC_20: Pin  ## = Pin(GPIO_EMC_20)
        GPIO_EMC_22: Pin  ## = Pin(GPIO_EMC_22)
        GPIO_EMC_21: Pin  ## = Pin(GPIO_EMC_21)
        GPIO_EMC_01: Pin  ## = Pin(GPIO_EMC_01)
        GPIO_EMC_00: Pin  ## = Pin(GPIO_EMC_00)
        GPIO_EMC_02: Pin  ## = Pin(GPIO_EMC_02)
        GPIO_EMC_03: Pin  ## = Pin(GPIO_EMC_03)
        GPIO_B1_13: Pin  ## = Pin(GPIO_B1_13)
        GPIO_B1_15: Pin  ## = Pin(GPIO_B1_15)
        GPIO_B1_14: Pin  ## = Pin(GPIO_B1_14)
        GPIO_EMC_11: Pin  ## = Pin(GPIO_EMC_11)
        GPIO_EMC_09: Pin  ## = Pin(GPIO_EMC_09)
        GPIO_EMC_08: Pin  ## = Pin(GPIO_EMC_08)
        GPIO_EMC_10: Pin  ## = Pin(GPIO_EMC_10)
        GPIO_EMC_04: Pin  ## = Pin(GPIO_EMC_04)
        GPIO_EMC_05: Pin  ## = Pin(GPIO_EMC_05)
        GPIO_EMC_07: Pin  ## = Pin(GPIO_EMC_07)
        GPIO_EMC_06: Pin  ## = Pin(GPIO_EMC_06)
        GPIO_SD_B1_04: Pin  ## = Pin(GPIO_SD_B1_04)
        GPIO_SD_B1_03: Pin  ## = Pin(GPIO_SD_B1_03)
        GPIO_SD_B1_05: Pin  ## = Pin(GPIO_SD_B1_05)
        GPIO_SD_B1_06: Pin  ## = Pin(GPIO_SD_B1_06)
        GPIO_SD_B1_00: Pin  ## = Pin(GPIO_SD_B1_00)
        GPIO_SD_B1_02: Pin  ## = Pin(GPIO_SD_B1_02)
        GPIO_SD_B1_01: Pin  ## = Pin(GPIO_SD_B1_01)
        GPIO_EMC_26: Pin  ## = Pin(GPIO_EMC_26)
        PMIC_ON_REQ: Pin  ## = Pin(PMIC_ON_REQ)
        GPIO_SD_B1_11: Pin  ## = Pin(GPIO_SD_B1_11)
        PMIC_STBY_REQ: Pin  ## = Pin(PMIC_STBY_REQ)
        GPIO_SD_B1_07: Pin  ## = Pin(GPIO_SD_B1_07)
        GPIO_SD_B1_08: Pin  ## = Pin(GPIO_SD_B1_08)
        GPIO_SD_B1_10: Pin  ## = Pin(GPIO_SD_B1_10)
        GPIO_SD_B1_09: Pin  ## = Pin(GPIO_SD_B1_09)
        GPIO_EMC_31: Pin  ## = Pin(GPIO_EMC_31)
        GPIO_EMC_30: Pin  ## = Pin(GPIO_EMC_30)
        GPIO_EMC_32: Pin  ## = Pin(GPIO_EMC_32)
        GPIO_EMC_33: Pin  ## = Pin(GPIO_EMC_33)
        GPIO_EMC_27: Pin  ## = Pin(GPIO_EMC_27)
        GPIO_EMC_29: Pin  ## = Pin(GPIO_EMC_29)
        GPIO_EMC_28: Pin  ## = Pin(GPIO_EMC_28)
        GPIO_EMC_41: Pin  ## = Pin(GPIO_EMC_41)
        GPIO_EMC_39: Pin  ## = Pin(GPIO_EMC_39)
        GPIO_EMC_38: Pin  ## = Pin(GPIO_EMC_38)
        GPIO_EMC_40: Pin  ## = Pin(GPIO_EMC_40)
        GPIO_EMC_34: Pin  ## = Pin(GPIO_EMC_34)
        GPIO_EMC_35: Pin  ## = Pin(GPIO_EMC_35)
        GPIO_EMC_37: Pin  ## = Pin(GPIO_EMC_37)
        GPIO_EMC_36: Pin  ## = Pin(GPIO_EMC_36)
        GPIO_AD_B1_03: Pin  ## = Pin(GPIO_AD_B1_03)
        GPIO_AD_B1_02: Pin  ## = Pin(GPIO_AD_B1_02)
        GPIO_AD_B1_04: Pin  ## = Pin(GPIO_AD_B1_04)
        GPIO_AD_B1_05: Pin  ## = Pin(GPIO_AD_B1_05)
        GPIO_AD_B0_15: Pin  ## = Pin(GPIO_AD_B0_15)
        GPIO_AD_B1_01: Pin  ## = Pin(GPIO_AD_B1_01)
        GPIO_AD_B1_00: Pin  ## = Pin(GPIO_AD_B1_00)
        GPIO_B1_11: Pin  ## = Pin(GPIO_B1_11)
        GPIO_AD_B1_11: Pin  ## = Pin(GPIO_AD_B1_11)
        GPIO_AD_B1_10: Pin  ## = Pin(GPIO_AD_B1_10)
        GPIO_AD_B1_12: Pin  ## = Pin(GPIO_AD_B1_12)
        GPIO_AD_B1_06: Pin  ## = Pin(GPIO_AD_B1_06)
        GPIO_AD_B1_07: Pin  ## = Pin(GPIO_AD_B1_07)
        GPIO_AD_B1_09: Pin  ## = Pin(GPIO_AD_B1_09)
        GPIO_AD_B1_08: Pin  ## = Pin(GPIO_AD_B1_08)
        GPIO_AD_B0_04: Pin  ## = Pin(GPIO_AD_B0_04)
        GPIO_AD_B0_03: Pin  ## = Pin(GPIO_AD_B0_03)
        GPIO_AD_B0_05: Pin  ## = Pin(GPIO_AD_B0_05)
        GPIO_AD_B0_06: Pin  ## = Pin(GPIO_AD_B0_06)
        GPIO_AD_B0_00: Pin  ## = Pin(GPIO_AD_B0_00)
        GPIO_AD_B0_02: Pin  ## = Pin(GPIO_AD_B0_02)
        GPIO_AD_B0_01: Pin  ## = Pin(GPIO_AD_B0_01)
        GPIO_AD_B0_14: Pin  ## = Pin(GPIO_AD_B0_14)
        GPIO_AD_B0_12: Pin  ## = Pin(GPIO_AD_B0_12)
        GPIO_AD_B0_11: Pin  ## = Pin(GPIO_AD_B0_11)
        GPIO_AD_B0_13: Pin  ## = Pin(GPIO_AD_B0_13)
        GPIO_AD_B0_07: Pin  ## = Pin(GPIO_AD_B0_07)
        GPIO_AD_B0_08: Pin  ## = Pin(GPIO_AD_B0_08)
        GPIO_AD_B0_10: Pin  ## = Pin(GPIO_AD_B0_10)
        GPIO_AD_B0_09: Pin  ## = Pin(GPIO_AD_B0_09)
        GPIO_B1_01: Pin  ## = Pin(GPIO_B1_01)
        GPIO_B1_00: Pin  ## = Pin(GPIO_B1_00)
        GPIO_B1_02: Pin  ## = Pin(GPIO_B1_02)
        GPIO_B1_03: Pin  ## = Pin(GPIO_B1_03)
        GPIO_B0_13: Pin  ## = Pin(GPIO_B0_13)
        GPIO_B0_15: Pin  ## = Pin(GPIO_B0_15)
        GPIO_B0_14: Pin  ## = Pin(GPIO_B0_14)
        GPIO_AD_B1_13: Pin  ## = Pin(GPIO_AD_B1_13)
        GPIO_B1_09: Pin  ## = Pin(GPIO_B1_09)
        GPIO_B1_08: Pin  ## = Pin(GPIO_B1_08)
        GPIO_B1_10: Pin  ## = Pin(GPIO_B1_10)
        GPIO_B1_04: Pin  ## = Pin(GPIO_B1_04)
        GPIO_B1_05: Pin  ## = Pin(GPIO_B1_05)
        GPIO_B1_07: Pin  ## = Pin(GPIO_B1_07)
        GPIO_B1_06: Pin  ## = Pin(GPIO_B1_06)
        GPIO_B0_02: Pin  ## = Pin(GPIO_B0_02)
        GPIO_B0_01: Pin  ## = Pin(GPIO_B0_01)
        GPIO_B0_03: Pin  ## = Pin(GPIO_B0_03)
        GPIO_B0_04: Pin  ## = Pin(GPIO_B0_04)
        GPIO_AD_B1_14: Pin  ## = Pin(GPIO_AD_B1_14)
        GPIO_B0_00: Pin  ## = Pin(GPIO_B0_00)
        GPIO_AD_B1_15: Pin  ## = Pin(GPIO_AD_B1_15)
        GPIO_B0_12: Pin  ## = Pin(GPIO_B0_12)
        GPIO_B0_10: Pin  ## = Pin(GPIO_B0_10)
        GPIO_B0_09: Pin  ## = Pin(GPIO_B0_09)
        GPIO_B0_11: Pin  ## = Pin(GPIO_B0_11)
        GPIO_B0_05: Pin  ## = Pin(GPIO_B0_05)
        GPIO_B0_06: Pin  ## = Pin(GPIO_B0_06)
        GPIO_B0_08: Pin  ## = Pin(GPIO_B0_08)
        GPIO_B0_07: Pin  ## = Pin(GPIO_B0_07)
        def __init__(self, *argv, **kwargs) -> None: ...

    class board:
        J5_22: Pin  ## = Pin(GPIO_B0_15)
        J5_25: Pin  ## = Pin(GPIO_B1_02)
        J5_24: Pin  ## = Pin(GPIO_B1_01)
        J5_23: Pin  ## = Pin(GPIO_B1_00)
        J5_26: Pin  ## = Pin(GPIO_B1_03)
        J5_30: Pin  ## = Pin(GPIO_B0_03)
        J5_29: Pin  ## = Pin(GPIO_B0_02)
        J5_28: Pin  ## = Pin(GPIO_B0_01)
        J5_06: Pin  ## = Pin(GPIO_B0_06)
        J5_17: Pin  ## = Pin(GPIO_B0_14)
        J5_12: Pin  ## = Pin(GPIO_B0_09)
        J5_08: Pin  ## = Pin(GPIO_B0_08)
        J5_07: Pin  ## = Pin(GPIO_B0_07)
        J5_13: Pin  ## = Pin(GPIO_B0_10)
        J5_16: Pin  ## = Pin(GPIO_B0_13)
        J5_15: Pin  ## = Pin(GPIO_B0_12)
        J5_14: Pin  ## = Pin(GPIO_B0_11)
        LED_GREEN: Pin  ## = Pin(GPIO_AD_B0_10)
        SCK_RX: Pin  ## = Pin(GPIO_AD_B1_11)
        MCK: Pin  ## = Pin(GPIO_AD_B1_09)
        LED_RED: Pin  ## = Pin(GPIO_AD_B0_09)
        SCK_TX: Pin  ## = Pin(GPIO_AD_B1_14)
        WS_RX: Pin  ## = Pin(GPIO_AD_B1_10)
        SD_TX: Pin  ## = Pin(GPIO_AD_B1_13)
        SD_RX: Pin  ## = Pin(GPIO_AD_B1_12)
        J5_32: Pin  ## = Pin(GPIO_B0_00)
        LED_BLUE: Pin  ## = Pin(GPIO_AD_B0_11)
        J5_36: Pin  ## = Pin(GPIO_AD_B1_13)
        J5_35: Pin  ## = Pin(GPIO_AD_B1_14)
        J5_34: Pin  ## = Pin(GPIO_AD_B1_15)
        J5_37: Pin  ## = Pin(GPIO_AD_B1_12)
        J5_50: Pin  ## = Pin(GPIO_AD_B0_02)
        J5_43: Pin  ## = Pin(GPIO_AD_B1_01)
        J5_42: Pin  ## = Pin(GPIO_AD_B1_00)
        WS_TX: Pin  ## = Pin(GPIO_AD_B1_15)
        J3_12: Pin  ## = Pin(GPIO_B1_09)
        J3_15: Pin  ## = Pin(GPIO_AD_B0_15)
        J3_14: Pin  ## = Pin(GPIO_AD_B0_14)
        J3_13: Pin  ## = Pin(GPIO_B1_10)
        J3_16: Pin  ## = Pin(GPIO_AD_B1_00)
        J3_20: Pin  ## = Pin(GPIO_AD_B0_12)
        J3_19: Pin  ## = Pin(GPIO_AD_B0_13)
        J3_17: Pin  ## = Pin(GPIO_AD_B1_01)
        J5_05: Pin  ## = Pin(GPIO_B0_05)
        J3_11: Pin  ## = Pin(GPIO_B1_07)
        J3_06: Pin  ## = Pin(GPIO_EMC_41)
        J3_05: Pin  ## = Pin(GPIO_B1_06)
        J3_04: Pin  ## = Pin(GPIO_B1_11)
        J3_07: Pin  ## = Pin(GPIO_EMC_40)
        J3_10: Pin  ## = Pin(GPIO_B1_08)
        J3_09: Pin  ## = Pin(GPIO_B1_04)
        J3_08: Pin  ## = Pin(GPIO_B1_05)
        J4_13: Pin  ## = Pin(GPIO_AD_B1_13)
        J4_16: Pin  ## = Pin(GPIO_AD_B1_02)
        J4_15: Pin  ## = Pin(GPIO_AD_B1_15)
        J4_14: Pin  ## = Pin(GPIO_AD_B1_14)
        J4_17: Pin  ## = Pin(GPIO_AD_B1_03)
        J5_04: Pin  ## = Pin(GPIO_B0_04)
        J4_20: Pin  ## = Pin(GPIO_AD_B0_06)
        J4_19: Pin  ## = Pin(GPIO_AD_B0_07)
        J4_04: Pin  ## = Pin(GPIO_AD_B1_04)
        J4_12: Pin  ## = Pin(GPIO_AD_B1_12)
        J4_07: Pin  ## = Pin(GPIO_AD_B1_07)
        J4_06: Pin  ## = Pin(GPIO_AD_B1_06)
        J4_05: Pin  ## = Pin(GPIO_AD_B1_05)
        J4_08: Pin  ## = Pin(GPIO_AD_B1_08)
        J4_11: Pin  ## = Pin(GPIO_AD_B1_11)
        J4_10: Pin  ## = Pin(GPIO_AD_B1_10)
        J4_09: Pin  ## = Pin(GPIO_AD_B1_09)
        def __init__(self, *argv, **kwargs) -> None: ...

    def __init__(self, *argv, **kwargs) -> None: ...

class Signal:
    def off(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class RTC:
    ALARM0: Final[int] = 0
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def cancel(self, *args, **kwargs) -> Incomplete: ...
    def datetime(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def calibration(self, *args, **kwargs) -> Incomplete: ...
    def alarm(self, *args, **kwargs) -> Incomplete: ...
    def alarm_cancel(self, *args, **kwargs) -> Incomplete: ...
    def alarm_left(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SDCard:
    def present(self, *args, **kwargs) -> Incomplete: ...
    def ioctl(self, *args, **kwargs) -> Incomplete: ...
    def readblocks(self, *args, **kwargs) -> Incomplete: ...
    def writeblocks(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def info(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SPI:
    LSB: Final[int] = 1
    MSB: Final[int] = 0
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write_readinto(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
