from typing import List, Optional, Tuple, Union, Any
from _typeshed import Incomplete as Incomplete

STA_IF: int
AP_IF: int

def hostname(*args, **kwargs) -> Any: ...
def route(*args, **kwargs) -> Any: ...
def country(*args, **kwargs) -> Any: ...
