from typing import Any

Node = Any

class ATOM:
    def __init__(self, np_n: Any) -> None: ...
    def get_button_status(self) -> Any: ...
    def set_button_callback(self, cb: Any) -> None: ...
    def set_pixel_color(self, num: Any, r: Any, g: Any, b: Any) -> None: ...
    def get_pixel_color(self, num: Any) -> Any: ...
    def set_pixels_color(self, r: Any, g: Any, b: Any) -> None: ...

class Lite(ATOM):
    def __init__(self) -> None: ...

class Matrix(ATOM):
    def __init__(self) -> None: ...
