
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class BMP280:
    def compute_delay_time() -> None: ...
    def read_compensated_data() -> None: ...
    def read_raw_data() -> None: ...
class array:
    def append() -> None: ...
    def decode() -> None: ...
    def extend() -> None: ...
def unpack() -> None: ...
def unpack_from() -> None: ...
