
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Emoji:
    def clear() -> None: ...
    def draw_square() -> None: ...
    def show_love() -> None: ...
    def show_map() -> None: ...
    def show_normal() -> None: ...
def sleep() -> None: ...
