
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Sh200q:
    def _accel_fs() -> None: ...
    def _gyro_fs() -> None: ...
    def _regChar() -> None: ...
    def _regInit() -> None: ...
    def _regThreeShort() -> None: ...
    def adcRest() -> None: ...
    def deinit() -> None: ...
def const() -> None: ...
