
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def _httpHanderConfig() -> None: ...
def _httpHanderRoot() -> None: ...
def doConnect() -> None: ...
def saveWiFi() -> None: ...
def webserver_start() -> None: ...
