from typing import Any, Optional

class deque(queu):
    def __init__(self, iterable, maxlen, flags: Optional[Any]) -> None: ...
    def append(self, x) -> Any: ...
    def popleft(self) -> Any: ...

class OrderedDict(dict):
    def __init__(self, *args) -> None: ...

def namedtuple(name, fields) -> Any: ...
