sep: str

def normcase(s): ...
def normpath(s): ...
def abspath(s): ...
def join(*args): ...
def split(path): ...
def dirname(path): ...
def basename(path): ...
def exists(path): ...

lexists = exists

def isdir(path): ...
def isfile(path): ...
def expanduser(s): ...
