from typing import Any, Optional

class deque:
    def __init__(self, iterable, maxlen, flags: Optional[Any]) -> None: ...
    def append(self, x) -> Any: ...
    def popleft(self) -> Any: ...

class namedtuple:
    def __init__(self, name, fields) -> None: ...

class OrderedDict:
    def __init__(self, *args) -> None: ...
