"""
Module: 'mip' on micropython-v1.29.0-esp32-ESP32_GENERIC_P4-PRE_REV3_C6_WIFI
"""

# MCU: {'variant': 'PRE_REV3_C6_WIFI', 'build': '', 'arch': 'unknown', 'port': 'esp32', 'board': 'ESP32_GENERIC_P4', 'board_id': 'ESP32_GENERIC_P4-PRE_REV3_C6_WIFI', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'ESP32-P4', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from _typeshed import Incomplete

_HOSTS: dict = {}

def _ensure_path_exists(*args, **kwargs) -> Incomplete: ...
def _download_file(*args, **kwargs) -> Incomplete: ...
def _install_json(*args, **kwargs) -> Incomplete: ...
def _install_package(*args, **kwargs) -> Incomplete: ...
def _rewrite_url(*args, **kwargs) -> Incomplete: ...
def _chunk(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...
def install(*args, **kwargs) -> Incomplete: ...
def _check_exists(*args, **kwargs) -> Incomplete: ...
