"""
Module: 'uhashlib' on micropython-v1.29.0-esp32-ESP32_GENERIC_P4-PRE_REV3_C6_WIFI
"""

# MCU: {'variant': 'PRE_REV3_C6_WIFI', 'build': '', 'arch': 'unknown', 'port': 'esp32', 'board': 'ESP32_GENERIC_P4', 'board_id': 'ESP32_GENERIC_P4-PRE_REV3_C6_WIFI', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'ESP32-P4', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from typing import Any, AsyncGenerator, Final, Generator

from _typeshed import Incomplete

class sha1:
    def digest(self, *args, **kwargs) -> Incomplete: ...
    def update(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class sha256:
    def digest(self, *args, **kwargs) -> Incomplete: ...
    def update(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class md5:
    def digest(self, *args, **kwargs) -> Incomplete: ...
    def update(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
