def cos() -> None: ...

e: float

def exp() -> None: ...
def log() -> None: ...
def log10() -> None: ...
def phase() -> None: ...

pi: float

def polar() -> None: ...
def rect() -> None: ...
def sin() -> None: ...
def sqrt() -> None: ...
