from typing import Any

HEAP_DATA: int
HEAP_EXEC: int

class Partition:
    BOOT: int
    RUNNING: int
    TYPE_APP: int
    TYPE_DATA: int
    def find() -> None: ...
    def get_next_update() -> None: ...
    def info() -> None: ...
    def ioctl() -> None: ...
    def mark_app_valid_cancel_rollback() -> None: ...
    def readblocks() -> None: ...
    def set_boot() -> None: ...
    def writeblocks() -> None: ...

class RMT:
    def clock_div() -> None: ...
    def deinit() -> None: ...
    def loop() -> None: ...
    def source_freq() -> None: ...
    def wait_done() -> None: ...
    def write_pulses() -> None: ...

class ULP:
    RESERVE_MEM: int
    def load_binary() -> None: ...
    def run() -> None: ...
    def set_wakeup_period() -> None: ...

WAKEUP_ALL_LOW: Any
WAKEUP_ANY_HIGH: Any

def hall_sensor() -> None: ...
def idf_heap_info() -> None: ...
def raw_temperature() -> None: ...
def wake_on_ext0() -> None: ...
def wake_on_ext1() -> None: ...
def wake_on_touch() -> None: ...
