from io import *
from typing import Any

class UioStream:
    _s: Any
    _is_bin: Any
    def __init__(self, s, is_bin) -> None: ...
    def write(self, data, off: Any | None = ..., sz: Any | None = ...) -> None: ...
    def __getattr__(self, attr): ...
    def __enter__(self): ...
    def __exit__(self, *args): ...

def open(name, mode: str = ..., *args, **kw): ...
