from typing import Any

MICROPY_PY_UTIME_TICKS_PERIOD: Any
_PASSTHRU: Any

def sleep_ms(t) -> None: ...
def sleep_us(t) -> None: ...
def ticks_ms(): ...
def ticks_us(): ...
def ticks_diff(ticks1, ticks2) -> int: ...

ticks_cpu = ticks_us
