from . import sx126x as sx126x
from .async_modem import AsyncModem as AsyncModem
from .sync_modem import SyncModem as SyncModem
from _typeshed import Incomplete

_CMD_CLR_ERRORS: Incomplete
_REG_OCP: Incomplete

class NucleoWL55RFConfig:
    _FE_CTRL: Incomplete
    def __init__(self) -> None: ...
    def _set_fe_ctrl(self, values) -> None: ...
    def rx(self) -> None: ...
    def tx(self, hp) -> None: ...
    def idle(self) -> None: ...

class DIO1:
    def irq(self, handler, _) -> None: ...

class _WL55SubGhzModem(sx126x._SX126x):
    _hp: bool
    def __init__(self, lora_cfg: Incomplete | None = ..., tcxo_millivolts: int = ..., ant_sw=...) -> None: ...
    def _clear_errors(self) -> None: ...
    def _clear_irq(self, clear_bits: int = ...) -> None: ...
    def _tx_hp(self): ...
    def _get_pa_tx_params(self, output_power, tx_ant): ...

class WL55SubGhzModem(_WL55SubGhzModem, SyncModem): ...
class AsyncWL55SubGhzModem(_WL55SubGhzModem, AsyncModem): ...
