"""
Module: 'aioespnow' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

class AIOESPNow:
    _data: list = []
    _none_tuple: tuple = ()
    def peer_count(self) -> Incomplete: ...
    def recv(self, x1) -> Incomplete: ...
    def mod_peer(self, *args, **kwargs) -> Incomplete: ...
    def irecv(self, x1) -> Incomplete: ...
    def stats(self) -> Incomplete: ...
    def recvinto(self, *args, **kwargs) -> Incomplete: ...
    def set_pmk(self, x1) -> Incomplete: ...
    def any(self) -> Incomplete: ...
    def add_peer(self, *args, **kwargs) -> Incomplete: ...
    def active(self, *args, **kwargs) -> Incomplete: ...
    def send(self, *args, **kwargs) -> Incomplete: ...
    def config(self, *args, **kwargs) -> Incomplete: ...
    def get_peers(self) -> Incomplete: ...
    def get_peer(self, x1) -> Incomplete: ...
    def del_peer(self, x1) -> Incomplete: ...
    def irq(self, x1) -> Incomplete: ...
    async def asend(self, x1, x2, x3) -> Incomplete: ...
    async def arecv(self) -> Incomplete: ...
    async def airecv(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
