"""
Module: 'cmath' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

e: float = 2.7182818
pi: float = 3.1415928

def polar(x0) -> Incomplete: ...
def sqrt(x0) -> Incomplete: ...
def rect(x0, x1) -> Incomplete: ...
def sin(x0) -> Incomplete: ...
def exp(x0) -> Incomplete: ...
def cos(x0) -> Incomplete: ...
def phase(x0) -> Incomplete: ...
def log(x0) -> Incomplete: ...
def log10(x0) -> Incomplete: ...
