"""
Module: 'inspect' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

def getargspec(x0) -> Incomplete: ...
def getmodule(x0, x1) -> Incomplete: ...
def getframeinfo(x0, x1) -> Incomplete: ...
def ismodule(x0) -> Incomplete: ...
def isclass(x0) -> Incomplete: ...
def getsource(x0) -> Incomplete: ...
def currentframe() -> Incomplete: ...
def getmro(x0) -> Incomplete: ...
def getfile(x0) -> Incomplete: ...
def getsourcefile(x0) -> Incomplete: ...
def isgeneratorfunction(x0) -> Incomplete: ...
def signature(x0) -> Incomplete: ...
def ismethod(x0) -> Incomplete: ...
def iscoroutinefunction(x0) -> Incomplete: ...
def iscoroutine(x0) -> Incomplete: ...
def getmembers(x0, x1) -> Incomplete: ...
def isfunction(x0) -> Incomplete: ...
def isgenerator(x0) -> Incomplete: ...

class _ct:
    def __init__(self, *argv, **kwargs) -> None: ...

async def _g() -> Incomplete: ...

_Instance: Incomplete  ## <class '_Class'> = <_Class object at ...>

class Signature:
    def __init__(self, *argv, **kwargs) -> None: ...

class _Class:
    def meth(self) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
