"""
Module: 'math' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

inf: float = inf
nan: float = nan
pi: float = 3.1415928
e: float = 2.7182818
tau: float = 6.2831856

def ldexp(x0, x1) -> Incomplete: ...
def lgamma(x0) -> Incomplete: ...
def trunc(x0) -> Incomplete: ...
def isclose(*args, **kwargs) -> Incomplete: ...
def gamma(x0) -> Incomplete: ...
def isnan(x0) -> Incomplete: ...
def isfinite(x0) -> Incomplete: ...
def isinf(x0) -> Incomplete: ...
def sqrt(x0) -> Incomplete: ...
def sinh(x0) -> Incomplete: ...
def log(*args, **kwargs) -> Incomplete: ...
def tan(x0) -> Incomplete: ...
def tanh(x0) -> Incomplete: ...
def log2(x0) -> Incomplete: ...
def log10(x0) -> Incomplete: ...
def sin(x0) -> Incomplete: ...
def modf(x0) -> Incomplete: ...
def radians(x0) -> Incomplete: ...
def atanh(x0) -> Incomplete: ...
def atan2(x0, x1) -> Incomplete: ...
def atan(x0) -> Incomplete: ...
def ceil(x0) -> Incomplete: ...
def copysign(x0, x1) -> Incomplete: ...
def frexp(x0) -> Incomplete: ...
def acos(x0) -> Incomplete: ...
def pow(x0, x1) -> Incomplete: ...
def asinh(x0) -> Incomplete: ...
def acosh(x0) -> Incomplete: ...
def asin(x0) -> Incomplete: ...
def factorial(x0) -> Incomplete: ...
def fabs(x0) -> Incomplete: ...
def expm1(x0) -> Incomplete: ...
def floor(x0) -> Incomplete: ...
def fmod(x0, x1) -> Incomplete: ...
def cos(x0) -> Incomplete: ...
def degrees(x0) -> Incomplete: ...
def cosh(x0) -> Incomplete: ...
def exp(x0) -> Incomplete: ...
def erf(x0) -> Incomplete: ...
def erfc(x0) -> Incomplete: ...
