"""
Module: 'time' on micropython-v1.28.0-esp32-ESP32_GENERIC_S2
"""

# MCU: {'variant': '', 'build': '', 'arch': 'xtensawin', 'port': 'esp32', 'board': 'ESP32_GENERIC_S2', 'board_id': 'ESP32_GENERIC_S2', 'mpy': 'v6.3', 'ver': '1.28.0', 'family': 'micropython', 'cpu': 'ESP32S2', 'version': '1.28.0'}
# Stubber: v1.28.1
from __future__ import annotations
from _typeshed import Incomplete

def ticks_diff(x0, x1) -> Incomplete: ...
def ticks_add(x0, x1) -> Incomplete: ...
def ticks_cpu() -> Incomplete: ...
def time() -> Incomplete: ...
def ticks_ms() -> Incomplete: ...
def ticks_us() -> Incomplete: ...
def time_ns() -> Incomplete: ...
def localtime(*args, **kwargs) -> Incomplete: ...
def sleep_us(x0) -> Incomplete: ...
def gmtime(*args, **kwargs) -> Incomplete: ...
def sleep_ms(x0) -> Incomplete: ...
def mktime(x0) -> Incomplete: ...
def sleep(x0) -> Incomplete: ...
