from typing import Any

MONO_HMSB: int
MONO_HLSB: int
RGB565: int
MONO_VLSB: int
MVLSB: int
GS2_HMSB: int
GS8: int
GS4_HMSB: int

def FrameBuffer1(*args, **kwargs) -> Any: ...

class FrameBuffer:
    def poly(self, *args, **kwargs) -> Any: ...
    def vline(self, *args, **kwargs) -> Any: ...
    def pixel(self, *args, **kwargs) -> Any: ...
    def text(self, *args, **kwargs) -> Any: ...
    def rect(self, *args, **kwargs) -> Any: ...
    def scroll(self, *args, **kwargs) -> Any: ...
    def ellipse(self, *args, **kwargs) -> Any: ...
    def line(self, *args, **kwargs) -> Any: ...
    def blit(self, *args, **kwargs) -> Any: ...
    def hline(self, *args, **kwargs) -> Any: ...
    def fill(self, *args, **kwargs) -> Any: ...
    def fill_rect(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
