from typing import Any

class AK8963:
    def _register_char(self, *args) -> Any: ...
    def _register_short(self, *args) -> Any: ...
    def _register_three_shorts(self, *args) -> Any: ...
    adjustement: Any
    magnetic: Any
    whoami: Any

class I2C:
    CBTYPE_ADDR: int
    CBTYPE_NONE: int
    CBTYPE_RXDATA: int
    CBTYPE_TXDATA: int
    MASTER: int
    READ: int
    SLAVE: int
    WRITE: int
    def address(self, *args) -> Any: ...
    def begin(self, *args) -> Any: ...
    def callback(self, *args) -> Any: ...
    def clock_timing(self, *args) -> Any: ...
    def data_timing(self, *args) -> Any: ...
    def deinit(self, *args) -> Any: ...
    def end(self, *args) -> Any: ...
    def getdata(self, *args) -> Any: ...
    def init(self, *args) -> Any: ...
    def is_ready(self, *args) -> Any: ...
    def read_byte(self, *args) -> Any: ...
    def read_bytes(self, *args) -> Any: ...
    def readfrom(self, *args) -> Any: ...
    def readfrom_into(self, *args) -> Any: ...
    def readfrom_mem(self, *args) -> Any: ...
    def readfrom_mem_into(self, *args) -> Any: ...
    def resetbusy(self, *args) -> Any: ...
    def scan(self, *args) -> Any: ...
    def setdata(self, *args) -> Any: ...
    def start(self, *args) -> Any: ...
    def start_timing(self, *args) -> Any: ...
    def stop(self, *args) -> Any: ...
    def stop_timing(self, *args) -> Any: ...
    def timeout(self, *args) -> Any: ...
    def write_byte(self, *args) -> Any: ...
    def write_bytes(self, *args) -> Any: ...
    def writeto(self, *args) -> Any: ...
    def writeto_mem(self, *args) -> Any: ...

MODE_CONTINOUS_MEASURE_1: int
MODE_CONTINOUS_MEASURE_2: int
MODE_EXTERNAL_TRIGGER_MEASURE: int
MODE_SINGLE_MEASURE: int
OUTPUT_14_BIT: int
OUTPUT_16_BIT: int

class Pin:
    IN: int
    INOUT: int
    INOUT_OD: int
    IRQ_ANYEDGE: int
    IRQ_DISABLE: int
    IRQ_FALLING: int
    IRQ_HILEVEL: int
    IRQ_LOLEVEL: int
    IRQ_RISING: int
    OUT: int
    OUT_OD: int
    PULL_DOWN: int
    PULL_FLOAT: int
    PULL_UP: int
    PULL_UPDOWN: int
    def init(self, *args) -> Any: ...
    def irqvalue(self, *args) -> Any: ...
    def value(self, *args) -> Any: ...

_MODE_FUSE_ROM_ACCESS: int
_MODE_POWER_DOWN: int
_MODE_SELF_TEST: int
_SO_14BIT: float
_SO_16BIT: float

def const(*args) -> Any: ...

ustruct: Any
