from typing import Any

SMTP: int
SMTPS: int

def ftp_get(*args) -> Any: ...
def ftp_list(*args) -> Any: ...
def ftp_put(*args) -> Any: ...
def get(*args) -> Any: ...
def getmail(*args) -> Any: ...
def info(*args) -> Any: ...
def options(*args) -> Any: ...
def post(*args) -> Any: ...
def sendmail(*args) -> Any: ...
