from typing import Any

Node = Any

def ftp_get() -> None: ...
def ftp_list() -> None: ...
def ftp_put() -> None: ...
def get() -> None: ...
def getmail() -> None: ...
def info() -> None: ...
def options() -> None: ...
def post() -> None: ...
def sendmail() -> None: ...
