from typing import Any

def collect(*args) -> Any: ...
def collectif(*args) -> Any: ...
def disable(*args) -> Any: ...
def enable(*args) -> Any: ...
def isenabled(*args) -> Any: ...
def mem_alloc(*args) -> Any: ...
def mem_free(*args) -> Any: ...
def threshold(*args) -> Any: ...
