from typing import Any

def certificate(*args) -> Any: ...
def debug(*args) -> Any: ...
def get(*args) -> Any: ...
def head(*args) -> Any: ...
def patch(*args) -> Any: ...
def post(*args) -> Any: ...
def put(*args) -> Any: ...
