from typing import Any

Node = Any

def certificate() -> None: ...
def debug() -> None: ...
def get() -> None: ...
def head() -> None: ...
def patch() -> None: ...
def post() -> None: ...
def put() -> None: ...
