from typing import Any

Node = Any

class SSD1306:
    def contrast() -> None: ...
    def fill() -> None: ...
    def init_display() -> None: ...
    def invert() -> None: ...
    def pixel() -> None: ...
    def poweroff() -> None: ...
    def scroll() -> None: ...
    def show() -> None: ...
    def text() -> None: ...

class SSD1306_I2C:
    def contrast() -> None: ...
    def fill() -> None: ...
    def init_display() -> None: ...
    def invert() -> None: ...
    def pixel() -> None: ...
    def poweroff() -> None: ...
    def poweron() -> None: ...
    def scroll() -> None: ...
    def show() -> None: ...
    def text() -> None: ...
    def write_cmd() -> None: ...
    def write_data() -> None: ...

class SSD1306_SPI:
    def contrast() -> None: ...
    def fill() -> None: ...
    def init_display() -> None: ...
    def invert() -> None: ...
    def pixel() -> None: ...
    def poweroff() -> None: ...
    def poweron() -> None: ...
    def scroll() -> None: ...
    def show() -> None: ...
    def text() -> None: ...
    def write_cmd() -> None: ...
    def write_data() -> None: ...

def const() -> None: ...
