from typing import Any

TRACE_ALL: int
TRACE_AUTH: int
TRACE_CONN: int
TRACE_ERROR: int
TRACE_KEX: int
TRACE_NONE: int
TRACE_PUBLICKEY: int
TRACE_SCP: int
TRACE_SFTP: int
TRACE_SOCKET: int
TRACE_TRANS: int

def exec(*args) -> Any: ...
def get(*args) -> Any: ...
def list(*args) -> Any: ...
def llist(*args) -> Any: ...
def mkdir(*args) -> Any: ...
def options(*args) -> Any: ...
def put(*args) -> Any: ...
