from typing import Any

Node = Any

class Calibrate:
    def calibError() -> None: ...
    def calibrate() -> None: ...
    def drawCrossHair() -> None: ...
    def readCoordinates() -> None: ...
    def tpcalib() -> None: ...
