from typing import Any

SDMODE_1LINE: int
SDMODE_4LINE: int
SDMODE_SPI: int

def chdir(*args) -> Any: ...
def getcwd(*args) -> Any: ...
def getdrive(*args) -> Any: ...
def ilistdir(*args) -> Any: ...
def listdir(*args) -> Any: ...
def mkdir(*args) -> Any: ...
def mountsd(*args) -> Any: ...
def remove(*args) -> Any: ...
def rename(*args) -> Any: ...
def rmdir(*args) -> Any: ...
def sdconfig(*args) -> Any: ...
def stat(*args) -> Any: ...
def statvfs(*args) -> Any: ...
def umountsd(*args) -> Any: ...
def uname(*args) -> Any: ...
def urandom(*args) -> Any: ...
