from typing import Any

DIRTYPE: str

class FileSection:
    def read(self, *args) -> Any: ...
    def readinto(self, *args) -> Any: ...
    def skip(self, *args) -> Any: ...

REGTYPE: str
TAR_HEADER: Any

class TarFile:
    def extractfile(self, *args) -> Any: ...
    def next(self, *args) -> Any: ...

class TarInfo: ...

def roundup(*args) -> Any: ...

uctypes: Any
