from typing import Any

class Response:
    def close(self, *args) -> Any: ...
    content: Any
    def json(self, *args) -> Any: ...
    text: Any

def delete(*args) -> Any: ...
def get(*args) -> Any: ...
def head(*args) -> Any: ...
def patch(*args) -> Any: ...
def post(*args) -> Any: ...
def put(*args) -> Any: ...
def request(*args) -> Any: ...

usocket: Any
