"""
Module: 'gc' on micropython-v1.26.0-rp2-RPI_PICO2
"""

# MCU: {'mpy': 'v6.3', 'build': '', 'ver': '1.26.0', 'arch': 'armv7emsp', 'version': '1.26.0', 'port': 'rp2', 'board': 'RPI_PICO2', 'family': 'micropython', 'board_id': 'RPI_PICO2', 'variant': '', 'cpu': 'RP2350'}
# Stubber: v1.26.0
from __future__ import annotations
from _typeshed import Incomplete

def mem_alloc(*args, **kwargs) -> Incomplete: ...
def isenabled(*args, **kwargs) -> Incomplete: ...
def mem_free(*args, **kwargs) -> Incomplete: ...
def threshold(*args, **kwargs) -> Incomplete: ...
def collect(*args, **kwargs) -> Incomplete: ...
def enable(*args, **kwargs) -> Incomplete: ...
def disable(*args, **kwargs) -> Incomplete: ...
