
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def espidf_info() -> None: ...
def exit() -> None: ...
def mpycore() -> None: ...
def print_exception() -> None: ...
def tz() -> None: ...
