
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Stream:
    def __init__(self, s: str, e: Any={}) -> None: ...
    def get_extra_info(self, v: Any) -> Any: ...
        #   0: return self.e[v]
        # ? 0: return self.e[v]
    def close(self) -> None: ...
    def write(self, buf: Any) -> None: ...
class Server:
    def close(self) -> None: ...
