"""
Module: 'itertools' on micropython-v1.28.0-webassembly-pyscript
"""

# MCU: {'family': 'micropython', 'version': '1.28.0', 'build': '', 'ver': '1.28.0', 'port': 'webassembly', 'board': 'pyscript', 'board_id': 'pyscript', 'variant': '', 'cpu': 'Emscripten', 'mpy': 'v6.3', 'arch': ''}
# Stubber: v1.28.3
from __future__ import annotations

from typing import Any, AsyncGenerator, Final, Generator

from _typeshed import Incomplete

def tee(x0, x1) -> Incomplete: ...
async def repeat(x0, x1) -> Incomplete: ...
async def islice(x0, x1, x2, x3) -> Incomplete: ...
async def starmap(x0, x1) -> Incomplete: ...
async def count(x0, x1) -> Incomplete: ...
async def accumulate(x0, x1) -> Incomplete: ...
async def cycle(x0) -> Incomplete: ...
async def chain() -> Incomplete: ...
