"""
Module: 'ubinascii' on micropython-v1.24.0-preview-stm32-PYBV11
"""

# MCU: {'version': '1.24.0-preview', 'mpy': 'v6.3', 'port': 'stm32', 'board': 'PYBV11', 'family': 'micropython', 'build': 'preview.62.g908ab1cec', 'arch': 'armv7emsp', 'ver': '1.24.0-preview-preview.62.g908ab1cec', 'cpu': 'STM32F405RG'}
# Stubber: v1.20.0
from __future__ import annotations
from _typeshed import Incomplete

def crc32(*args, **kwargs) -> Incomplete: ...
def hexlify(*args, **kwargs) -> Incomplete: ...
def unhexlify(*args, **kwargs) -> Incomplete: ...
def b2a_base64(*args, **kwargs) -> Incomplete: ...
def a2b_base64(*args, **kwargs) -> Incomplete: ...
