"""
Module: 'ustruct' on micropython-v1.24.0-preview-stm32-PYBV11
"""

# MCU: {'version': '1.24.0-preview', 'mpy': 'v6.3', 'port': 'stm32', 'board': 'PYBV11', 'family': 'micropython', 'build': 'preview.60.gcebc9b0ae', 'arch': 'armv7emsp', 'ver': '1.24.0-preview-preview.60.gcebc9b0ae', 'cpu': 'STM32F405RG'}
# Stubber: v1.20.0
from __future__ import annotations
from _typeshed import Incomplete

def pack_into(*args, **kwargs) -> Incomplete: ...
def unpack(*args, **kwargs) -> Incomplete: ...
def unpack_from(*args, **kwargs) -> Incomplete: ...
def pack(*args, **kwargs) -> Incomplete: ...
def calcsize(*args, **kwargs) -> Incomplete: ...
