from typing import Any

def bitstream(*args) -> Any: ...

class NeoPixel:
    def __init__(self, *argv, **kwargs) -> None: ...
    def write(self, *args) -> Any: ...
    def fill(self, *args) -> Any: ...
    ORDER: tuple
