PAD: str

def _transform() -> None: ...
def a2b_base64() -> None: ...
def a2b_hex() -> None: ...
def b2a_base64() -> None: ...
def b2a_hex() -> None: ...
def crc32() -> None: ...
def hexlify() -> None: ...

table_a2b_base64: str
table_b2a_base64: str

def unhexlify() -> None: ...
