from typing import Any

class Motor:
    def angle(self, *argv) -> Any: ...
    def dc(self, *argv) -> Any: ...
    def reset_angle(self, *argv) -> Any: ...
    def run(self, *argv) -> Any: ...
    def run_angle(self, *argv) -> Any: ...
    def run_target(self, *argv) -> Any: ...
    def run_time(self, *argv) -> Any: ...
    def run_until_stalled(self, *argv) -> Any: ...
    def set_dc_settings(self, *argv) -> Any: ...
    def set_pid_settings(self, *argv) -> Any: ...
    def set_run_settings(self, *argv) -> Any: ...
    def speed(self, *argv) -> Any: ...
    def stalled(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...
    def track_target(self, *argv) -> Any: ...
