from typing import Any

_sha224: Any
_sha256: Any
_sha384: Any
_sha512: Any

def init() -> None: ...
def new() -> None: ...

class sha1:
    def digest(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

class sha224:
    block_size: int
    def copy(self, *argv) -> Any: ...
    def digest(self, *argv) -> Any: ...
    digest_size: int
    digestsize: int
    def hexdigest(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

class sha256:
    def digest(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

class sha384:
    block_size: int
    def copy(self, *argv) -> Any: ...
    def digest(self, *argv) -> Any: ...
    digest_size: int
    digestsize: int
    def hexdigest(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

class sha512:
    block_size: int
    def copy(self, *argv) -> Any: ...
    def digest(self, *argv) -> Any: ...
    digest_size: int
    digestsize: int
    def hexdigest(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...

uhashlib: Any
