from typing import Any

class JSONDecoder:
    def decode(self, *argv) -> Any: ...
    def raw_decode(self, *argv) -> Any: ...

class JSONEncoder:
    def default(self, *argv) -> Any: ...
    def encode(self, *argv) -> Any: ...
    item_separator: str
    def iterencode(self, *argv) -> Any: ...
    key_separator: str

_default_decoder: Any
_default_encoder: Any
decoder: Any

def dump() -> None: ...
def dumps() -> None: ...

encoder: Any

def load() -> None: ...
def loads() -> None: ...

scanner: Any
