from typing import Any

A: int
ASCII: int
DOTALL: int
I: int
IGNORECASE: int
M: int
MULTILINE: int

class PCREMatch:
    def end(self, *argv) -> Any: ...
    def group(self, *argv) -> Any: ...
    def groups(self, *argv) -> Any: ...
    def span(self, *argv) -> Any: ...
    def start(self, *argv) -> Any: ...

class PCREPattern:
    def findall(self, *argv) -> Any: ...
    def match(self, *argv) -> Any: ...
    def search(self, *argv) -> Any: ...
    def split(self, *argv) -> Any: ...
    def sub(self, *argv) -> Any: ...

PCRE_ANCHORED: int
PCRE_INFO_CAPTURECOUNT: int
S: int
U: int
UNICODE: int
VERBOSE: int
X: int
array: Any

def compile() -> None: ...
def escape() -> None: ...

ffilib: Any

def findall() -> None: ...
def match() -> None: ...

pcre: Any
pcre_compile: Any
pcre_exec: Any
pcre_fullinfo: Any

def search() -> None: ...
def split() -> None: ...
def sub() -> None: ...

sys: Any
