class Struct:
    def pack() -> None: ...
    def unpack() -> None: ...

def calcsize() -> None: ...
def pack() -> None: ...
def pack_into() -> None: ...
def unpack() -> None: ...
def unpack_from() -> None: ...
