from typing import Any

class OrderedDict:
    def clear(self, *argv) -> Any: ...
    def copy(self, *argv) -> Any: ...
    def fromkeys(self, *argv) -> Any: ...
    def get(self, *argv) -> Any: ...
    def items(self, *argv) -> Any: ...
    def keys(self, *argv) -> Any: ...
    def pop(self, *argv) -> Any: ...
    def popitem(self, *argv) -> Any: ...
    def setdefault(self, *argv) -> Any: ...
    def update(self, *argv) -> Any: ...
    def values(self, *argv) -> Any: ...

class deque:
    def append(self, *argv) -> Any: ...
    def popleft(self, *argv) -> Any: ...

def namedtuple() -> None: ...
