from typing import Any

class PinBase: ...

class Signal:
    def off(self, *argv) -> Any: ...
    def on(self, *argv) -> Any: ...
    def value(self, *argv) -> Any: ...

mem16: Any
mem32: Any
mem8: Any

def time_pulse_us() -> None: ...
