def errno() -> None: ...
def getenv() -> None: ...
def ilistdir() -> None: ...
def mkdir() -> None: ...
def stat() -> None: ...
def statvfs() -> None: ...
def system() -> None: ...
def unlink() -> None: ...
