from typing import Any

class websocket:
    def close(self, *argv) -> Any: ...
    def ioctl(self, *argv) -> Any: ...
    def read(self, *argv) -> Any: ...
    def readinto(self, *argv) -> Any: ...
    def readline(self, *argv) -> Any: ...
    def write(self, *argv) -> Any: ...
