name: "commit changes"
description: ""
inputs:
  message:
    description: "commit message"
    required: true
    default: "commit changes, but only if actual stubs changed"


runs:
  using: composite
  steps:
    - name: Check for relevant changes (enhanced diff)
      uses: ./.github/actions/enhanced-diff
      id: diff
      with:
        verbose: "true"

    - name: show outputs
      run: |
        echo "changed: ${{steps.diff.outputs.changed}}"
        echo "total count: ${{steps.diff.outputs.count}}"
        echo "non-json count: ${{steps.diff.outputs.non_json_count}}"
        echo "json count: ${{steps.diff.outputs.json_count}}"
      shell: bash


    - run: git pull origin main --rebase --autostash
      if: ${{steps.diff.outputs.changed == 'true'}} 
      shell: bash


    - name: Commit the changes
      uses: EndBug/add-and-commit@v9
      if: ${{steps.diff.outputs.changed == 'true'}} AND ${{ !env.ACT }}
      with:
        message: ${{ inputs.message }}
      
    - name: Do not Commit the changes if running in ACT
      run: echo "Running locally in ACT; Skipped publish stubs for ${{matrix.version}}"
      shell: bash
      if : ${{ env.ACT }}
