from typing import Any

class DHT11:
    def humidity(self, *args) -> Any: ...
    def measure(self, *args) -> Any: ...
    def temperature(self, *args) -> Any: ...

class DHT22:
    def humidity(self, *args) -> Any: ...
    def measure(self, *args) -> Any: ...
    def temperature(self, *args) -> Any: ...

class DHTBase:
    def measure(self, *args) -> Any: ...

def dht_readinto(*args) -> Any: ...
