"""
Module: 'umachine' on micropython-v1.26.1-mimxrt-MIMXRT1010_EVK
"""

# MCU: {'variant': '', 'build': '', 'arch': 'armv7emsp', 'port': 'mimxrt', 'board': 'MIMXRT1010_EVK', 'board_id': 'MIMXRT1010_EVK', 'mpy': 'v6.3', 'ver': '1.26.1', 'family': 'micropython', 'cpu': 'MIMXRT1011DAE5A', 'version': '1.26.1'}
# Stubber: v1.26.3
from __future__ import annotations
from typing import Any, Final, Generator
from _typeshed import Incomplete

SOFT_RESET: Final[int] = 5
PWRON_RESET: Final[int] = 1
WDT_RESET: Final[int] = 3

def unique_id(*args, **kwargs) -> Incomplete: ...
def disable_irq(*args, **kwargs) -> Incomplete: ...
def dht_readinto(*args, **kwargs) -> Incomplete: ...
def bitstream(*args, **kwargs) -> Incomplete: ...
def bootloader(*args, **kwargs) -> Incomplete: ...
def deepsleep(*args, **kwargs) -> Incomplete: ...
def enable_irq(*args, **kwargs) -> Incomplete: ...
def reset_cause(*args, **kwargs) -> Incomplete: ...
def soft_reset(*args, **kwargs) -> Incomplete: ...
def time_pulse_us(*args, **kwargs) -> Incomplete: ...
def reset(*args, **kwargs) -> Incomplete: ...
def freq(*args, **kwargs) -> Incomplete: ...
def idle(*args, **kwargs) -> Incomplete: ...
def lightsleep(*args, **kwargs) -> Incomplete: ...

mem8: Incomplete  ## <class 'mem'> = <8-bit memory>
mem32: Incomplete  ## <class 'mem'> = <32-bit memory>
mem16: Incomplete  ## <class 'mem'> = <16-bit memory>

class LED:
    def on(self, *args, **kwargs) -> Incomplete: ...
    def toggle(self, *args, **kwargs) -> Incomplete: ...
    def off(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class WDT:
    def timeout_ms(self, *args, **kwargs) -> Incomplete: ...
    def feed(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2S:
    RX: Final[int] = 0
    MONO: Final[int] = 0
    STEREO: Final[int] = 1
    TX: Final[int] = 1
    def shift(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ADC:
    def read_uv(self, *args, **kwargs) -> Incomplete: ...
    def read_u16(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_mem(self, *args, **kwargs) -> Incomplete: ...
    def writeto_mem(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def writeto(self, *args, **kwargs) -> Incomplete: ...
    def writevto(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def readfrom(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2CTarget:
    IRQ_END_READ: Final[int] = 16
    IRQ_ADDR_MATCH_WRITE: Final[int] = 2
    IRQ_END_WRITE: Final[int] = 32
    IRQ_READ_REQ: Final[int] = 4
    IRQ_ADDR_MATCH_READ: Final[int] = 1
    IRQ_WRITE_REQ: Final[int] = 8
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SoftI2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_mem(self, *args, **kwargs) -> Incomplete: ...
    def writeto_mem(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def writeto(self, *args, **kwargs) -> Incomplete: ...
    def writevto(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def readfrom(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SoftSPI:
    LSB: Final[int] = 1
    MSB: Final[int] = 0
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write_readinto(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Timer:
    PERIODIC: Final[int] = 2
    ONE_SHOT: Final[int] = 1
    def init(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class UART:
    INV_TX: Final[int] = 1
    INV_RX: Final[int] = 2
    CTS: Final[int] = 2
    IRQ_RXIDLE: Final[int] = 1
    IRQ_TXIDLE: Final[int] = 2
    RTS: Final[int] = 1
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def sendbreak(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def flush(self, *args, **kwargs) -> Incomplete: ...
    def txdone(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def any(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def readline(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class PWM:
    def duty_u16(self, *args, **kwargs) -> Incomplete: ...
    def freq(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def duty_ns(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Signal:
    def off(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Pin:
    OPEN_DRAIN: Final[int] = 2
    IRQ_RISING: Final[int] = 1
    IRQ_FALLING: Final[int] = 2
    IN: Final[int] = 0
    PULL_UP_22K: Final[int] = 3
    OUT: Final[int] = 1
    PULL_UP: Final[int] = 2
    PULL_HOLD: Final[int] = 5
    PULL_DOWN: Final[int] = 0
    DRIVE_2: Final[int] = 3
    DRIVE_1: Final[int] = 2
    DRIVE_0: Final[int] = 1
    PULL_UP_47K: Final[int] = 1
    DRIVE_OFF: Final[int] = 0
    DRIVE_3: Final[int] = 4
    DRIVE_6: Final[int] = 7
    DRIVE_5: Final[int] = 6
    DRIVE_4: Final[int] = 5
    def low(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def toggle(self, *args, **kwargs) -> Incomplete: ...
    def off(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def high(self, *args, **kwargs) -> Incomplete: ...

    class cpu:
        GPIO_SD_00: Pin  ## = Pin(GPIO_SD_00)
        GPIO_AD_14: Pin  ## = Pin(GPIO_AD_14)
        GPIO_AD_13: Pin  ## = Pin(GPIO_AD_13)
        GPIO_SD_01: Pin  ## = Pin(GPIO_SD_01)
        GPIO_SD_02: Pin  ## = Pin(GPIO_SD_02)
        PMIC_ON_REQ: Pin  ## = Pin(PMIC_ON_REQ)
        GPIO_AD_09: Pin  ## = Pin(GPIO_AD_09)
        GPIO_AD_08: Pin  ## = Pin(GPIO_AD_08)
        GPIO_AD_12: Pin  ## = Pin(GPIO_AD_12)
        GPIO_AD_10: Pin  ## = Pin(GPIO_AD_10)
        GPIO_AD_11: Pin  ## = Pin(GPIO_AD_11)
        GPIO_SD_11: Pin  ## = Pin(GPIO_SD_11)
        GPIO_SD_10: Pin  ## = Pin(GPIO_SD_10)
        GPIO_SD_09: Pin  ## = Pin(GPIO_SD_09)
        GPIO_SD_12: Pin  ## = Pin(GPIO_SD_12)
        GPIO_SD_13: Pin  ## = Pin(GPIO_SD_13)
        GPIO_SD_03: Pin  ## = Pin(GPIO_SD_03)
        GPIO_SD_05: Pin  ## = Pin(GPIO_SD_05)
        GPIO_SD_04: Pin  ## = Pin(GPIO_SD_04)
        GPIO_SD_08: Pin  ## = Pin(GPIO_SD_08)
        GPIO_SD_06: Pin  ## = Pin(GPIO_SD_06)
        GPIO_SD_07: Pin  ## = Pin(GPIO_SD_07)
        GPIO_07: Pin  ## = Pin(GPIO_07)
        GPIO_06: Pin  ## = Pin(GPIO_06)
        GPIO_05: Pin  ## = Pin(GPIO_05)
        GPIO_08: Pin  ## = Pin(GPIO_08)
        GPIO_09: Pin  ## = Pin(GPIO_09)
        GPIO_AD_07: Pin  ## = Pin(GPIO_AD_07)
        GPIO_01: Pin  ## = Pin(GPIO_01)
        GPIO_00: Pin  ## = Pin(GPIO_00)
        GPIO_04: Pin  ## = Pin(GPIO_04)
        GPIO_02: Pin  ## = Pin(GPIO_02)
        GPIO_03: Pin  ## = Pin(GPIO_03)
        GPIO_AD_04: Pin  ## = Pin(GPIO_AD_04)
        GPIO_AD_03: Pin  ## = Pin(GPIO_AD_03)
        GPIO_AD_02: Pin  ## = Pin(GPIO_AD_02)
        GPIO_AD_05: Pin  ## = Pin(GPIO_AD_05)
        GPIO_AD_06: Pin  ## = Pin(GPIO_AD_06)
        GPIO_10: Pin  ## = Pin(GPIO_10)
        GPIO_12: Pin  ## = Pin(GPIO_12)
        GPIO_11: Pin  ## = Pin(GPIO_11)
        GPIO_AD_01: Pin  ## = Pin(GPIO_AD_01)
        GPIO_13: Pin  ## = Pin(GPIO_13)
        GPIO_AD_00: Pin  ## = Pin(GPIO_AD_00)
        def __init__(self, *argv, **kwargs) -> None: ...

    class board:
        LED_GREEN: Pin  ## = Pin(GPIO_11)
        ENC_B: Pin  ## = Pin(GPIO_AD_06)
        PWM_AT: Pin  ## = Pin(GPIO_02)
        MCK: Pin  ## = Pin(GPIO_08)
        PWM_AB: Pin  ## = Pin(GPIO_01)
        D7: Pin  ## = Pin(GPIO_AD_02)
        D6: Pin  ## = Pin(GPIO_AD_01)
        ENC_A: Pin  ## = Pin(GPIO_AD_05)
        D8: Pin  ## = Pin(GPIO_SD_02)
        D9: Pin  ## = Pin(GPIO_03)
        D5: Pin  ## = Pin(GPIO_01)
        SD_TX: Pin  ## = Pin(GPIO_04)
        SD_RX: Pin  ## = Pin(GPIO_03)
        PWM_BB: Pin  ## = Pin(GPIO_03)
        VOLT_DCB: Pin  ## = Pin(GPIO_AD_09)
        WS_RX: Pin  ## = Pin(GPIO_02)
        PWM_CB: Pin  ## = Pin(GPIO_05)
        PWM_BT: Pin  ## = Pin(GPIO_04)
        SCK_TX: Pin  ## = Pin(GPIO_06)
        PWM_CT: Pin  ## = Pin(GPIO_06)
        SCK_RX: Pin  ## = Pin(GPIO_01)
        WS_TX: Pin  ## = Pin(GPIO_07)
        CUR_A: Pin  ## = Pin(GPIO_AD_01)
        A5: Pin  ## = Pin(GPIO_AD_02)
        CUR_DCB: Pin  ## = Pin(GPIO_AD_10)
        CUR_B: Pin  ## = Pin(GPIO_AD_02)
        CUR_C: Pin  ## = Pin(GPIO_AD_07)
        A1: Pin  ## = Pin(GPIO_AD_09)
        A0: Pin  ## = Pin(GPIO_AD_07)
        A4: Pin  ## = Pin(GPIO_AD_01)
        A2: Pin  ## = Pin(GPIO_AD_10)
        A3: Pin  ## = Pin(GPIO_AD_14)
        D4: Pin  ## = Pin(GPIO_08)
        D15: Pin  ## = Pin(GPIO_02)
        D14: Pin  ## = Pin(GPIO_01)
        D0: Pin  ## = Pin(GPIO_09)
        D2: Pin  ## = Pin(GPIO_AD_05)
        D3: Pin  ## = Pin(GPIO_AD_06)
        D10: Pin  ## = Pin(GPIO_AD_05)
        D1: Pin  ## = Pin(GPIO_10)
        D13: Pin  ## = Pin(GPIO_AD_06)
        D11: Pin  ## = Pin(GPIO_AD_04)
        D12: Pin  ## = Pin(GPIO_AD_03)
        def __init__(self, *argv, **kwargs) -> None: ...

    def __init__(self, *argv, **kwargs) -> None: ...

class RTC:
    ALARM0: Final[int] = 0
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def cancel(self, *args, **kwargs) -> Incomplete: ...
    def datetime(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def calibration(self, *args, **kwargs) -> Incomplete: ...
    def alarm(self, *args, **kwargs) -> Incomplete: ...
    def alarm_cancel(self, *args, **kwargs) -> Incomplete: ...
    def alarm_left(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SPI:
    LSB: Final[int] = 1
    MSB: Final[int] = 0
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write_readinto(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
