# Micropython v1.29.0-preview frozen stubs
def partial(func, *args, **kwargs): ...
def update_wrapper(wrapper, wrapped, assigned=None, updated=None): ...
def wraps(wrapped, assigned=None, updated=None): ...
def reduce(function, iterable, initializer=None): ...
