# Micropython v1.29.0-preview frozen stubs
def attrgetter(attr): ...
def lt(a, b): ...
def le(a, b): ...
def gt(a, b): ...
def ge(a, b): ...
def eq(a, b): ...
def ne(a, b): ...
def add(a, b): ...
def and_(a, b): ...
def floordiv(a, b): ...
def inv(a): ...

invert = inv

def mod(a, b): ...
def mul(a, b): ...
def neg(a): ...
def or_(a, b): ...
def pow(a, b): ...
def sub(a, b): ...
def truediv(a, b): ...
def xor(a, b): ...
