from typing import Any

ADDR_RANDOM: int
ADDR_PUBLIC: int

def log_error(*args, **kwargs) -> Any: ...
def log_warn(*args, **kwargs) -> Any: ...
def stop(*args, **kwargs) -> Any: ...
def register_services(*args, **kwargs) -> Any: ...
def const(*args, **kwargs) -> Any: ...
def log_info(*args, **kwargs) -> Any: ...
def config(*args, **kwargs) -> Any: ...

class BufferedCharacteristic:
    def on_read(self, *args, **kwargs) -> Any: ...
    def notify(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    indicate: Any
    written: Any
    def __init__(self, *argv, **kwargs) -> None: ...

class Descriptor:
    def write(self, *args, **kwargs) -> Any: ...
    def on_read(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    written: Any
    def __init__(self, *argv, **kwargs) -> None: ...

class scan:
    cancel: Any
    def __init__(self, *argv, **kwargs) -> None: ...

class DeviceDisconnectedError(Exception): ...
