from typing import Any

log_level: int

def log_error(*args, **kwargs) -> Any: ...
def ble_irq(*args, **kwargs) -> Any: ...
def ensure_active(*args, **kwargs) -> Any: ...
def register_irq_handler(*args, **kwargs) -> Any: ...
def log_warn(*args, **kwargs) -> Any: ...
def stop(*args, **kwargs) -> Any: ...
def config(*args, **kwargs) -> Any: ...
def log_info(*args, **kwargs) -> Any: ...

ble: Any

class GattError(Exception): ...
