from typing import Any

class Calc:
    def _available(self, *argv) -> Any: ...
    def _update(self, *argv) -> Any: ...
    def clearStr(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def deleteStrLast(self, *argv) -> Any: ...
    def isNewKeyPress(self, *argv) -> Any: ...
    def readKey(self, *argv) -> Any: ...
    def readStr(self, *argv) -> Any: ...

i2c_bus: Any
