from typing import Any

class Encode:
    def _available(self, *argv) -> Any: ...
    def _update(self, *argv) -> Any: ...
    def clearValue(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def getDir(self, *argv) -> Any: ...
    def getPress(self, *argv) -> Any: ...
    def getValue(self, *argv) -> Any: ...
    def setLed(self, *argv) -> Any: ...

i2c_bus: Any
time: Any
