from typing import Any

class ADC:
    def read() -> None: ...
    def read_timed() -> None: ...
    def read_timed_multi() -> None: ...

class ADCAll:
    def read_channel() -> None: ...
    def read_core_temp() -> None: ...
    def read_core_vbat() -> None: ...
    def read_core_vref() -> None: ...
    def read_vref() -> None: ...

class Accel:
    def filtered_xyz() -> None: ...
    def read() -> None: ...
    def tilt() -> None: ...
    def write() -> None: ...
    def x() -> None: ...
    def y() -> None: ...
    def z() -> None: ...

class CAN:
    BUS_OFF: int
    ERROR_ACTIVE: int
    ERROR_PASSIVE: int
    ERROR_WARNING: int
    LIST16: int
    LIST32: int
    LOOPBACK: int
    MASK16: int
    MASK32: int
    NORMAL: int
    SILENT: int
    SILENT_LOOPBACK: int
    STOPPED: int
    def any() -> None: ...
    def clearfilter() -> None: ...
    def deinit() -> None: ...
    def info() -> None: ...
    def init() -> None: ...
    def initfilterbanks() -> None: ...
    def recv() -> None: ...
    def restart() -> None: ...
    def rxcallback() -> None: ...
    def send() -> None: ...
    def setfilter() -> None: ...
    def state() -> None: ...

class DAC:
    CIRCULAR: int
    NORMAL: int
    def deinit() -> None: ...
    def init() -> None: ...
    def noise() -> None: ...
    def triangle() -> None: ...
    def write() -> None: ...
    def write_timed() -> None: ...

class ExtInt:
    EVT_FALLING: int
    EVT_RISING: int
    EVT_RISING_FALLING: int
    IRQ_FALLING: int
    IRQ_RISING: int
    IRQ_RISING_FALLING: int
    def disable() -> None: ...
    def enable() -> None: ...
    def line() -> None: ...
    def regs() -> None: ...
    def swint() -> None: ...

class Flash:
    def ioctl() -> None: ...
    def readblocks() -> None: ...
    def writeblocks() -> None: ...

class I2C:
    MASTER: int
    SLAVE: int
    def deinit() -> None: ...
    def init() -> None: ...
    def is_ready() -> None: ...
    def mem_read() -> None: ...
    def mem_write() -> None: ...
    def recv() -> None: ...
    def scan() -> None: ...
    def send() -> None: ...

class LCD:
    def command() -> None: ...
    def contrast() -> None: ...
    def fill() -> None: ...
    def get() -> None: ...
    def light() -> None: ...
    def pixel() -> None: ...
    def show() -> None: ...
    def text() -> None: ...
    def write() -> None: ...

class LED:
    def intensity() -> None: ...
    def off() -> None: ...
    def on() -> None: ...
    def toggle() -> None: ...

class Pin:
    AF1_TIM1: int
    AF1_TIM2: int
    AF2_TIM3: int
    AF2_TIM4: int
    AF2_TIM5: int
    AF3_TIM10: int
    AF3_TIM11: int
    AF3_TIM8: int
    AF3_TIM9: int
    AF4_I2C1: int
    AF4_I2C2: int
    AF5_SPI1: int
    AF5_SPI2: int
    AF7_USART1: int
    AF7_USART2: int
    AF7_USART3: int
    AF8_UART4: int
    AF8_USART6: int
    AF9_CAN1: int
    AF9_CAN2: int
    AF9_TIM12: int
    AF9_TIM13: int
    AF9_TIM14: int
    AF_OD: int
    AF_PP: int
    ALT: int
    ALT_OPEN_DRAIN: int
    ANALOG: int
    IN: int
    IRQ_FALLING: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    OUT_OD: int
    OUT_PP: int
    PULL_DOWN: int
    PULL_NONE: int
    PULL_UP: int
    def af() -> None: ...
    def af_list() -> None: ...
    board: Any
    cpu: Any
    def debug() -> None: ...
    def dict() -> None: ...
    def gpio() -> None: ...
    def high() -> None: ...
    def init() -> None: ...
    def irq() -> None: ...
    def low() -> None: ...
    def mapper() -> None: ...
    def mode() -> None: ...
    def name() -> None: ...
    def names() -> None: ...
    def off() -> None: ...
    def on() -> None: ...
    def pin() -> None: ...
    def port() -> None: ...
    def pull() -> None: ...
    def value() -> None: ...

class RTC:
    def calibration() -> None: ...
    def datetime() -> None: ...
    def info() -> None: ...
    def init() -> None: ...
    def wakeup() -> None: ...

SD: Any

class SDCard:
    def info() -> None: ...
    def ioctl() -> None: ...
    def power() -> None: ...
    def present() -> None: ...
    def read() -> None: ...
    def readblocks() -> None: ...
    def write() -> None: ...
    def writeblocks() -> None: ...

class SPI:
    LSB: int
    MASTER: int
    MSB: int
    SLAVE: int
    def deinit() -> None: ...
    def init() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def recv() -> None: ...
    def send() -> None: ...
    def send_recv() -> None: ...
    def write() -> None: ...
    def write_readinto() -> None: ...

class Servo:
    def angle() -> None: ...
    def calibration() -> None: ...
    def pulse_width() -> None: ...
    def speed() -> None: ...

class Switch:
    def callback() -> None: ...
    def value() -> None: ...

class Timer:
    BOTH: int
    BRK_HIGH: int
    BRK_LOW: int
    BRK_OFF: int
    CENTER: int
    DOWN: int
    ENC_A: int
    ENC_AB: int
    ENC_B: int
    FALLING: int
    HIGH: int
    IC: int
    LOW: int
    OC_ACTIVE: int
    OC_FORCED_ACTIVE: int
    OC_FORCED_INACTIVE: int
    OC_INACTIVE: int
    OC_TIMING: int
    OC_TOGGLE: int
    PWM: int
    PWM_INVERTED: int
    RISING: int
    UP: int
    def callback() -> None: ...
    def channel() -> None: ...
    def counter() -> None: ...
    def deinit() -> None: ...
    def freq() -> None: ...
    def init() -> None: ...
    def period() -> None: ...
    def prescaler() -> None: ...
    def source_freq() -> None: ...

class UART:
    CTS: int
    IRQ_RXIDLE: int
    RTS: int
    def any() -> None: ...
    def deinit() -> None: ...
    def init() -> None: ...
    def irq() -> None: ...
    def read() -> None: ...
    def readchar() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def sendbreak() -> None: ...
    def write() -> None: ...
    def writechar() -> None: ...

class USB_HID:
    def recv() -> None: ...
    def send() -> None: ...

class USB_VCP:
    CTS: int
    RTS: int
    def any() -> None: ...
    def close() -> None: ...
    def init() -> None: ...
    def isconnected() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def readlines() -> None: ...
    def recv() -> None: ...
    def send() -> None: ...
    def setinterrupt() -> None: ...
    def write() -> None: ...

def bootloader() -> None: ...
def country() -> None: ...
def delay() -> None: ...
def dht_readinto() -> None: ...
def disable_irq() -> None: ...
def elapsed_micros() -> None: ...
def elapsed_millis() -> None: ...
def enable_irq() -> None: ...
def fault_debug() -> None: ...
def freq() -> None: ...
def hard_reset() -> None: ...
def have_cdc() -> None: ...
def hid() -> None: ...

hid_keyboard: Any
hid_mouse: Any

def info() -> None: ...
def main() -> None: ...
def micros() -> None: ...
def millis() -> None: ...
def mount() -> None: ...
def pwm() -> None: ...
def repl_info() -> None: ...
def repl_uart() -> None: ...
def rng() -> None: ...
def servo() -> None: ...
def standby() -> None: ...
def stop() -> None: ...
def sync() -> None: ...
def udelay() -> None: ...
def unique_id() -> None: ...
def usb_mode() -> None: ...
def wfi() -> None: ...
