from _typeshed import Incomplete as Incomplete

def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class ClientDiscover:
    def __init__(self, *argv, **kwargs) -> None: ...

class DeviceConnection:
    def services(self, *args, **kwargs) -> Incomplete: ...
    def is_connected(self, *args, **kwargs) -> Incomplete: ...
    def timeout(self, *args, **kwargs) -> Incomplete: ...
    l2cap_accept: Incomplete
    exchange_mtu: Incomplete
    pair: Incomplete
    l2cap_connect: Incomplete
    service: Incomplete
    disconnect: Incomplete
    device_task: Incomplete
    disconnected: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class ClientDescriptor:
    write: Incomplete
    read: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class ClientCharacteristic:
    def descriptors(self, *args, **kwargs) -> Incomplete: ...
    subscribe: Incomplete
    notified: Incomplete
    indicated: Incomplete
    read: Incomplete
    descriptor: Incomplete
    write: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class ClientService:
    def characteristics(self, *args, **kwargs) -> Incomplete: ...
    characteristic: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class BaseClientCharacteristic:
    write: Incomplete
    read: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class deque:
    def popleft(self, *args, **kwargs) -> Incomplete: ...
    def append(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

ble: Incomplete

class GattError(Exception): ...
