from _typeshed import Incomplete as Incomplete

def register_irq_handler(*args, **kwargs) -> Incomplete: ...
def log_error(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class L2CAPChannel:
    def available(self, *args, **kwargs) -> Incomplete: ...
    disconnected: Incomplete
    recvinto: Incomplete
    send: Incomplete
    flush: Incomplete
    disconnect: Incomplete
    def __init__(self, *argv, **kwargs) -> None: ...

class L2CAPConnectionError(Exception): ...
