
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def acos() -> None: ...
def asin() -> None: ...
def atan() -> None: ...
def atan2() -> None: ...
def ceil() -> None: ...
def copysign() -> None: ...
def cos() -> None: ...
def degrees() -> None: ...
def exp() -> None: ...
def fabs() -> None: ...
def floor() -> None: ...
def fmod() -> None: ...
def frexp() -> None: ...
def isfinite() -> None: ...
def isinf() -> None: ...
def isnan() -> None: ...
def ldexp() -> None: ...
def log() -> None: ...
def modf() -> None: ...
def pow() -> None: ...
def radians() -> None: ...
def sin() -> None: ...
def sqrt() -> None: ...
def tan() -> None: ...
def trunc() -> None: ...
