
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def callback() -> None: ...
def getaddrinfo() -> None: ...
def print_pcbs() -> None: ...
def reset() -> None: ...
class socket: ...
