class OrderedDict:
    def clear() -> None: ...
    def copy() -> None: ...
    def fromkeys() -> None: ...
    def get() -> None: ...
    def items() -> None: ...
    def keys() -> None: ...
    def pop() -> None: ...
