from typing import Any, Optional

def sleep_type(sleep_type: Optional[Any]) -> Any: ...
def deepsleep(time_us: int = ...) -> Any: ...
def flash_id() -> Any: ...
def flash_size() -> Any: ...
def flash_user_start() -> Any: ...
def flash_read(byte_offset, length_or_buffer) -> Any: ...
def flash_write(byte_offset, bytes) -> Any: ...
def flash_erase(sector_no) -> Any: ...
def set_native_code_location(start, length) -> Any: ...
