from typing import Any, Optional

def const(expr) -> Any: ...
def opt_level(level: Optional[Any]) -> Any: ...
def alloc_emergency_exception_buf(size) -> Any: ...
def mem_info(verbose: Optional[Any]) -> None: ...
def qstr_info(verbose: Optional[Any]) -> None: ...
def stack_use() -> int: ...
def heap_lock() -> Any: ...
def heap_unlock() -> Any: ...
def heap_locked() -> int: ...
def kbd_intr(chr) -> None: ...
def schedule(func, arg) -> Any: ...
