from typing import Any, List, Optional, Tuple

DEBUG: Any

class regex:
    def match(self, string) -> Any: ...
    def search(self, string) -> Any: ...
    def sub(self, replace, string, count: int = ..., flags: int = ...) -> Any: ...
    def split(self, string, max_split: int = ...) -> List[str]: ...

class match:
    def group(self, index) -> str: ...
    def groups(self) -> Tuple: ...
    def start(self, index: Optional[Any]) -> int: ...
    def end(self, index: Optional[Any]) -> int: ...
    def span(self, index: Optional[Any]) -> Tuple: ...

def compile(regex_str, flags: Optional[Any]) -> regex: ...
def search(regex_str, string) -> Any: ...
def sub(regex_str, replace, string, count: int = ..., flags: int = ...) -> str: ...
