from _typeshed import Incomplete as Incomplete

def platform(*args, **kwargs) -> Incomplete: ...
def python_compiler(*args, **kwargs) -> Incomplete: ...
def libc_ver(*args, **kwargs) -> Incomplete: ...
