from _typeshed import Incomplete as Incomplete

def asm_pio(*args, **kwargs) -> Incomplete: ...
def asm_pio_encode(*args, **kwargs) -> Incomplete: ...
def bootsel_button(*args, **kwargs) -> Incomplete: ...
def country(*args, **kwargs) -> Incomplete: ...
def const(*args, **kwargs) -> Incomplete: ...

class PIOASMError(Exception): ...
