
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Align: ...
class Display:
    def _next_line() -> None: ...
    def _reset_text_history() -> None: ...
    def clear() -> None: ...
    def image() -> None: ...
    def text() -> None: ...
class Ev3devDisplay:
    def image() -> None: ...
    def reset_screen() -> None: ...
    def scroll() -> None: ...
    def text_grid() -> None: ...
    def text_pixels() -> None: ...
class ImageFile: ...
