
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Display:
    def _next_line() -> None: ...
    def _reset_text_history() -> None: ...
    def clear() -> None: ...
    def image() -> None: ...
    def text() -> None: ...
class Speaker:
    def beep() -> None: ...
    def beeps() -> None: ...
    def file() -> None: ...
    def speech() -> None: ...
    def tune() -> None: ...
def buttons() -> None: ...
def exit() -> None: ...
def light() -> None: ...
