from _typeshed import Incomplete as Incomplete

def check_bootsec(*args, **kwargs) -> Incomplete: ...
def fs_corrupted(*args, **kwargs) -> Incomplete: ...
def setup(*args, **kwargs) -> Incomplete: ...

bdev: Incomplete
