
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Partition:
    def find() -> None: ...
    def get_next_update() -> None: ...
    def info() -> None: ...
    def ioctl() -> None: ...
    def readblocks() -> None: ...
    def set_boot() -> None: ...
    def writeblocks() -> None: ...
