from typing import Any

TAR_HEADER: Any
DIRTYPE: str
REGTYPE: str

def roundup(val, align): ...

class FileSection:
    f: Any
    content_len: Any
    align: Any
    def __init__(self, f, content_len, aligned_len) -> None: ...
    def read(self, sz: int = ...): ...
    def readinto(self, buf): ...
    def skip(self) -> None: ...

class TarInfo:
    def __str__(self): ...

class TarFile:
    f: Any
    subf: Any
    def __init__(self, name: Any | None = ..., fileobj: Any | None = ...) -> None: ...
    def next(self): ...
    def __iter__(self): ...
    def __next__(self): ...
    def extractfile(self, tarinfo): ...
