from typing import Any

ENCODER_ADDR: int

class Lego:
    def deinit(self, *argv) -> Any: ...

class Lego_Motor:
    def _available(self, *argv) -> Any: ...
    def _read_encoder(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def position_update(self, *argv) -> Any: ...
    def read_encoder(self, *argv) -> Any: ...
    def run_distance(self, *argv) -> Any: ...
    def run_to(self, *argv) -> Any: ...
    def set_pwm(self, *argv) -> Any: ...
    def stop(self, *argv) -> Any: ...

M5GO_WHEEL_ADDR: int
MOTOR_CTRL_ADDR: int

def const() -> None: ...
def constrain() -> None: ...
def dead_area() -> None: ...

i2c_bus: Any
machine: Any
module: Any
motor1_pwm: int
motor2_pwm: int
os: Any
time: Any
ustruct: Any
