from typing import Any

class LidarBot:
    def controlWheel(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def goAhead(self, *argv) -> Any: ...
    def goBack(self, *argv) -> Any: ...
    def setOneRgb(self, *argv) -> Any: ...
    def setRgb(self, *argv) -> Any: ...
    def setServo(self, *argv) -> Any: ...
    def setStepMotor(self, *argv) -> Any: ...
    def turnLeft(self, *argv) -> Any: ...
    def turnRight(self, *argv) -> Any: ...

class LidarStep:
    def controlWheel(self, *argv) -> Any: ...
    def goAhead(self, *argv) -> Any: ...
    def goBack(self, *argv) -> Any: ...
    def setOneRgb(self, *argv) -> Any: ...
    def setRgb(self, *argv) -> Any: ...
    def setServo(self, *argv) -> Any: ...
    def setStepMotor(self, *argv) -> Any: ...
    def turnLeft(self, *argv) -> Any: ...
    def turnRight(self, *argv) -> Any: ...

controlMap: Any
machine: Any
