from typing import Any

class Lorawan:
    def _monitor(self, *argv) -> Any: ...
    def _reset(self, *argv) -> Any: ...
    def _setMode(self, *argv) -> Any: ...
    def _uart_cb(self, *argv) -> Any: ...
    def _waitTimeout(self, *argv) -> Any: ...
    def _write(self, *argv) -> Any: ...
    def deinit(self, *argv) -> Any: ...
    def initP2PMode(self, *argv) -> Any: ...
    def initRxMode(self, *argv) -> Any: ...
    def txStr(self, *argv) -> Any: ...

machine: Any
module: Any
timEx: Any
time: Any
