from _typeshed import Incomplete

class HMAC:
    _outer: Incomplete
    _inner: Incomplete
    digest_size: Incomplete
    block_size: Incomplete
    def __init__(self, key, msg=None, digestmod=None) -> None: ...
    @property
    def name(self): ...
    def update(self, msg) -> None: ...
    def copy(self): ...
    def _current(self): ...
    def digest(self): ...
    def hexdigest(self): ...

def new(key, msg=None, digestmod=None): ...
