"""
Pyscript 2025.2.3 type-stub.
see: https://docs.pyscript.net/2025.2.3/api/
"""

from typing import Any

code = ...
protocols = ...
reason = ...
methods = ...

class EventMessage:
    def __init__(self, event) -> None: ...
    def __getattr__(self, attr) -> Any | memoryview[int] | str: ...

class WebSocket:
    CONNECTING = ...
    OPEN = ...
    CLOSING = ...
    CLOSED = ...
    def __init__(self, **kw) -> None: ...
    def __getattr__(self, attr) -> Any: ...
    def __setattr__(self, attr, value) -> None: ...
    def close(self, **kw) -> None: ...
    def send(self, data) -> None: ...
