"""
Module: '_onewire' on micropython-v1.29.0-esp32-ESP32_GENERIC_P4-PRE_REV3_C6_WIFI
"""

# MCU: {'variant': 'PRE_REV3_C6_WIFI', 'build': '', 'arch': 'unknown', 'port': 'esp32', 'board': 'ESP32_GENERIC_P4', 'board_id': 'ESP32_GENERIC_P4-PRE_REV3_C6_WIFI', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'ESP32-P4', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from _typeshed import Incomplete

def reset(*args, **kwargs) -> Incomplete: ...
def writebyte(*args, **kwargs) -> Incomplete: ...
def writebit(*args, **kwargs) -> Incomplete: ...
def crc8(*args, **kwargs) -> Incomplete: ...
def readbyte(*args, **kwargs) -> Incomplete: ...
def readbit(*args, **kwargs) -> Incomplete: ...
