"""
Module: 'ds18x20' on micropython-v1.29.0-esp32-ESP32_GENERIC_P4-PRE_REV3_C6_WIFI
"""

# MCU: {'variant': 'PRE_REV3_C6_WIFI', 'build': '', 'arch': 'unknown', 'port': 'esp32', 'board': 'ESP32_GENERIC_P4', 'board_id': 'ESP32_GENERIC_P4-PRE_REV3_C6_WIFI', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'ESP32-P4', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from _typeshed import Incomplete

def const(*args, **kwargs) -> Incomplete: ...

class DS18X20:
    def read_scratch(self, *args, **kwargs) -> Incomplete: ...
    def read_temp(self, *args, **kwargs) -> Incomplete: ...
    def write_scratch(self, *args, **kwargs) -> Incomplete: ...
    def convert_temp(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
