from typing import Any

_LPS22_CTRL_REG1: Any
_LPS22_CTRL_REG2: Any
_LPS22_STATUS: Any
_LPS22_TEMP_OUT_L: Any
_LPS22_PRESS_OUT_XL: Any
_LPS22_PRESS_OUT_L: Any

class LPS22H:
    i2c: Any
    addr: Any
    oneshot: Any
    buf: Any
    def __init__(self, i2c, address: int = ..., oneshot: bool = ...) -> None: ...
    def _int16(self, d): ...
    def _write_reg(self, reg, dat) -> None: ...
    def _read_reg(self, reg, width: int = ...): ...
    def _tigger_oneshot(self, b) -> None: ...
    def set_oneshot_mode(self, oneshot) -> None: ...
    def pressure(self): ...
    def temperature(self): ...
    def altitude(self): ...
