from typing import Any

PWRON_RESET: int
HARD_RESET: int
SOFT_RESET: int
WDT_RESET: int
DEEPSLEEP_RESET: int

def disable_irq(*args, **kwargs) -> Any: ...
def reset_cause(*args, **kwargs) -> Any: ...
def enable_irq(*args, **kwargs) -> Any: ...
def bitstream(*args, **kwargs) -> Any: ...
def dht_readinto(*args, **kwargs) -> Any: ...
def bootloader(*args, **kwargs) -> Any: ...
def soft_reset(*args, **kwargs) -> Any: ...
def freq(*args, **kwargs) -> Any: ...
def reset(*args, **kwargs) -> Any: ...
def time_pulse_us(*args, **kwargs) -> Any: ...
def lightsleep(*args, **kwargs) -> Any: ...
def idle(*args, **kwargs) -> Any: ...
def unique_id(*args, **kwargs) -> Any: ...

class WDT:
    def timeout_ms(self, *args, **kwargs) -> Any: ...
    def feed(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

mem8: Any
mem32: Any
mem16: Any

class PWM:
    def freq(self, *args, **kwargs) -> Any: ...
    def duty_u16(self, *args, **kwargs) -> Any: ...
    def duty_ns(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ADC:
    def read_u16(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class DAC:
    def write(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Any: ...
    def readfrom_into(self, *args, **kwargs) -> Any: ...
    def readfrom_mem(self, *args, **kwargs) -> Any: ...
    def writeto_mem(self, *args, **kwargs) -> Any: ...
    def scan(self, *args, **kwargs) -> Any: ...
    def writeto(self, *args, **kwargs) -> Any: ...
    def writevto(self, *args, **kwargs) -> Any: ...
    def start(self, *args, **kwargs) -> Any: ...
    def readfrom(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def stop(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Pin:
    OUT: int
    OPEN_DRAIN: int
    LOW_POWER: int
    PULL_DOWN: int
    PULL_OFF: int
    PULL_UP: int
    IRQ_RISING: int
    HIGH_POWER: int
    IN: int
    IRQ_FALLING: int
    def irq(self, *args, **kwargs) -> Any: ...
    def toggle(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def on(self, *args, **kwargs) -> Any: ...
    def low(self, *args, **kwargs) -> Any: ...
    def off(self, *args, **kwargs) -> Any: ...
    def high(self, *args, **kwargs) -> Any: ...
    def value(self, *args, **kwargs) -> Any: ...
    def disable(self, *args, **kwargs) -> Any: ...
    def drive(self, *args, **kwargs) -> Any: ...

    class board:
        LED: Any
        MOSI: Any
        MISO: Any
        D5: Any
        DOTSTAR_DATA: Any
        DOTSTAR_CLK: Any
        USB_DP: Any
        SWDIO: Any
        SCK: Any
        USB_DM: Any
        SCL: Any
        SWCLK: Any
        SDA: Any
        A3_D12: Any
        A5: Any
        A4_D13: Any
        A0_D9: Any
        A2_D11: Any
        A1_D10: Any
        D4: Any
        D1: Any
        A6_D2: Any
        D3: Any
        AREF: Any
        D0: Any
        BUTTON: Any
        def __init__(self, *argv, **kwargs) -> None: ...

    class cpu:
        PA23: Any
        PA24: Any
        PA25: Any
        PA27: Any
        PA18: Any
        PA22: Any
        PA19: Any
        PA20: Any
        PA21: Any
        PB09: Any
        PB10: Any
        PB11: Any
        PB22: Any
        PA30: Any
        PB08: Any
        PA31: Any
        PB02: Any
        PB03: Any
        PB23: Any
        PA04: Any
        PA05: Any
        PA06: Any
        PA07: Any
        PA17: Any
        PA03: Any
        PA00: Any
        PA01: Any
        PA02: Any
        PA13: Any
        PA14: Any
        PA15: Any
        PA16: Any
        PA08: Any
        PA12: Any
        PA09: Any
        PA10: Any
        PA11: Any
        def __init__(self, *argv, **kwargs) -> None: ...

    def __init__(self, *argv, **kwargs) -> None: ...

class SoftSPI:
    LSB: int
    MSB: int
    def deinit(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def write_readinto(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Timer:
    PERIODIC: int
    ONE_SHOT: int
    def init(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class UART:
    def flush(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def txdone(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def sendbreak(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    def any(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def readline(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SoftI2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Any: ...
    def readfrom_into(self, *args, **kwargs) -> Any: ...
    def readfrom_mem(self, *args, **kwargs) -> Any: ...
    def writeto_mem(self, *args, **kwargs) -> Any: ...
    def scan(self, *args, **kwargs) -> Any: ...
    def writeto(self, *args, **kwargs) -> Any: ...
    def writevto(self, *args, **kwargs) -> Any: ...
    def start(self, *args, **kwargs) -> Any: ...
    def readfrom(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def stop(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class RTC:
    def datetime(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def calibration(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SPI:
    LSB: int
    MSB: int
    def deinit(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def write_readinto(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Signal:
    def off(self, *args, **kwargs) -> Any: ...
    def on(self, *args, **kwargs) -> Any: ...
    def value(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
