from _typeshed import Incomplete as Incomplete

def mem_alloc(*args, **kwargs) -> Incomplete: ...
def isenabled(*args, **kwargs) -> Incomplete: ...
def mem_free(*args, **kwargs) -> Incomplete: ...
def threshold(*args, **kwargs) -> Incomplete: ...
def collect(*args, **kwargs) -> Incomplete: ...
def enable(*args, **kwargs) -> Incomplete: ...
def disable(*args, **kwargs) -> Incomplete: ...
