"""
Module: 'ujson' on micropython-v1.24.0-preview-esp32-ESP32_GENERIC_S3
"""

# MCU: {'version': '1.24.0-preview', 'mpy': 'v6.3', 'port': 'esp32', 'board': 'ESP32_GENERIC_S3', 'family': 'micropython', 'build': 'preview.86.g557d31ed2', 'arch': 'xtensawin', 'ver': '1.24.0-preview-preview.86.g557d31ed2', 'cpu': 'ESP32S3'}
# Stubber: v1.20.0
from __future__ import annotations
from _typeshed import Incomplete

def loads(*args, **kwargs) -> Incomplete: ...
def load(*args, **kwargs) -> Incomplete: ...
def dumps(*args, **kwargs) -> Incomplete: ...
def dump(*args, **kwargs) -> Incomplete: ...
