from typing import Any

def const(*args, **kwargs) -> Any: ...

class LSM6DSOX:
    def read_mlc_output(self, *args, **kwargs) -> Any: ...
    def set_embedded_functions(self, *args, **kwargs) -> Any: ...
    def read_gyro(self, *args, **kwargs) -> Any: ...
    def read_accel(self, *args, **kwargs) -> Any: ...
    def reset(self, *args, **kwargs) -> Any: ...
    def set_mem_bank(self, *args, **kwargs) -> Any: ...
    def load_mlc(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
