from _typeshed import Incomplete

class IMU:
    imu: Incomplete
    def __init__(self, bus) -> None:
        """Initializes Gyro, Accelerometer and Magnetometer using default values."""
    def gyro(self): ...
    def accel(self): ...
    def magnet(self): ...
