
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def set_led(state: Any) -> None: ...
def toggle_led(state: Any) -> None: ...
def get_amb_light() -> Any: ...
    #   0: return adc.read()
    # ? 0: return adc.read()
def set_ldo2_power(state: Any) -> None: ...
def dotstar_color_wheel(wheel_pos: Any) -> Union[Tuple[, Any, Any], Tuple[Any, , Any], Tuple[Any, Any, ]]: ...
def go_deepsleep(t: Any) -> None: ...
