
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class CardKB:
    def _available() -> None: ...
    def _monitor() -> None: ...
    def deinit() -> None: ...
    def isNewKeyPress() -> None: ...
