
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Ext_io:
    def _available() -> None: ...
    def _get_mode() -> None: ...
    def deinit() -> None: ...
    def digitRead() -> None: ...
    def digitReadPort() -> None: ...
    def digitWrite() -> None: ...
    def digitWritePort() -> None: ...
    def setPinMode() -> None: ...
    def setPortMode() -> None: ...
def const() -> None: ...
