from typing import Any

ACK_FAIL: int
ACK_FULL: int
ACK_NOUSER: int
ACK_SUCCESS: int
ACK_TIMEOUT: int
ACK_USER_EXIST: int
ACK_USER_OCCUPIED: int

class Finger:
    def _monitor() -> None: ...
    def _write() -> None: ...
    def addUser() -> None: ...
    def deinit() -> None: ...
    def getUnknownCb() -> None: ...
    def readFingerCb() -> None: ...
    def readUser() -> None: ...
    def removeAllUser() -> None: ...
    def removeUser() -> None: ...

machine: Any
timEx: Any
time: Any
unit: Any
