
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Finger:
    def _monitor() -> None: ...
    def _write() -> None: ...
    def addUser() -> None: ...
    def deinit() -> None: ...
    def getUnknownCb() -> None: ...
    def readFingerCb() -> None: ...
    def readUser() -> None: ...
    def removeAllUser() -> None: ...
    def removeUser() -> None: ...
