
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Ir:
    def _irq_cb() -> None: ...
    def _update() -> None: ...
    def deinit() -> None: ...
    def rxStatus() -> None: ...
    def txOff() -> None: ...
    def txOn() -> None: ...
class PWM:
    def deinit() -> None: ...
    def duty() -> None: ...
    def freq() -> None: ...
    def init() -> None: ...
    def list() -> None: ...
    def pause() -> None: ...
    def resume() -> None: ...
class Pin:
    def deinit() -> None: ...
    def init() -> None: ...
    def irq() -> None: ...
    def off() -> None: ...
    def on() -> None: ...
    def value() -> None: ...
class Timer:
    def deinit() -> None: ...
    def init() -> None: ...
    def value() -> None: ...
