
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Mlx90640:
    def deinit() -> None: ...
    def getCenterTmp() -> None: ...
    def getMaxTmp() -> None: ...
    def getMinTmp() -> None: ...
    def getTmp() -> None: ...
    def setColorMaxTmp() -> None: ...
    def setColorMinTmp() -> None: ...
    def update() -> None: ...
