
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Tracker:
    def _available() -> None: ...
    def _register_char() -> None: ...
    def _register_short() -> None: ...
    def deinit() -> None: ...
    def getAnalogValue() -> None: ...
    def getDigitalValue() -> None: ...
    def setAnalogValue() -> None: ...
