
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Lego:
    def deinit() -> None: ...
class Lego_Motor:
    def _available() -> None: ...
    def _read_encoder() -> None: ...
    def deinit() -> None: ...
    def position_update() -> None: ...
    def read_encoder() -> None: ...
    def run_distance() -> None: ...
    def run_to() -> None: ...
    def set_pwm() -> None: ...
    def stop() -> None: ...
def const() -> None: ...
def constrain() -> None: ...
def dead_area() -> None: ...
