
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class AlsaError: ...
class Mixer:
    def close() -> None: ...
    def set_beep_volume() -> None: ...
    def set_pcm_volume() -> None: ...
class PCM:
    def close() -> None: ...
    def play() -> None: ...
def _check_error() -> None: ...
def addressof() -> None: ...
def calcsize() -> None: ...
def unpack() -> None: ...
