
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class SMBus:
    def _access() -> None: ...
    def block_process_call() -> None: ...
    def process_call() -> None: ...
    def read_block_data() -> None: ...
    def read_byte() -> None: ...
    def read_byte_data() -> None: ...
    def read_i2c_block_data() -> None: ...
    def read_word_data() -> None: ...
    def set_address() -> None: ...
    def write_block_data() -> None: ...
    def write_byte() -> None: ...
    def write_byte_data() -> None: ...
    def write_i2c_block_data() -> None: ...
    def write_quick() -> None: ...
    def write_word_data() -> None: ...
def ioctl() -> None: ...
