
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Timeout:
    def _run() -> None: ...
    def cancel() -> None: ...
    def close() -> None: ...
    def start() -> None: ...
    def wait() -> None: ...
class Timer:
    def elapsed_time() -> None: ...
    def reset() -> None: ...
    def wait() -> None: ...
def _thread_runner() -> None: ...
def addressof() -> None: ...
def debug_print() -> None: ...
def fork() -> None: ...
def libc() -> None: ...
def poll() -> None: ...
def sizeof() -> None: ...
class struct: ...
def write_at_index() -> None: ...
