"""
Module: 'machine' on micropython-v1.29.0-nrf-SEEED_XIAO_NRF52
"""

# MCU: {'variant': '', 'build': '', 'arch': 'armv7emsp', 'port': 'nrf', 'board': 'SEEED_XIAO_NRF52', 'board_id': 'SEEED_XIAO_NRF52', 'mpy': 'v6.3', 'ver': '1.29.0', 'family': 'micropython', 'cpu': 'NRF52840', 'version': '1.29.0'}
# Stubber: v1.28.6
from __future__ import annotations

from typing import Final

from _typeshed import Incomplete

PWRON_RESET: Final[int] = 16
LOCKUP_RESET: Final[int] = 3
LPCOMP_RESET: Final[int] = 17
NFC_RESET: Final[int] = 19
SOFT_RESET: Final[int] = 2
WDT_RESET: Final[int] = 1
DEBUG_IF_RESET: Final[int] = 18
HARD_RESET: Final[int] = 0

def info(*args, **kwargs) -> Incomplete: ...
def idle(*args, **kwargs) -> Incomplete: ...
def disable_irq(*args, **kwargs) -> Incomplete: ...
def freq(*args, **kwargs) -> Incomplete: ...
def enable_irq(*args, **kwargs) -> Incomplete: ...
def deepsleep(*args, **kwargs) -> Incomplete: ...
def sleep(*args, **kwargs) -> Incomplete: ...
def lightsleep(*args, **kwargs) -> Incomplete: ...
def soft_reset(*args, **kwargs) -> Incomplete: ...
def mem_backup(*args, **kwargs) -> Incomplete: ...
def reset_cause(*args, **kwargs) -> Incomplete: ...
def reset(*args, **kwargs) -> Incomplete: ...
def unique_id(*args, **kwargs) -> Incomplete: ...
def bootloader(*args, **kwargs) -> Incomplete: ...

class RTCounter:
    ONESHOT: Final[int] = 0
    FREQUENCY: Final[int] = 8
    PERIODIC: Final[int] = 1
    def counter(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Pin:
    PULL_DOWN: Final[int] = 1
    IRQ_RISING: Final[int] = 1
    OUT: Final[int] = 1
    PULL_DISABLED: Final[int] = 0
    PULL_UP: Final[int] = 3
    IRQ_FALLING: Final[int] = 2
    IN: Final[int] = 0
    def name(self, *args, **kwargs) -> Incomplete: ...
    def names(self, *args, **kwargs) -> Incomplete: ...
    def mode(self, *args, **kwargs) -> Incomplete: ...
    def low(self, *args, **kwargs) -> Incomplete: ...
    def pull(self, *args, **kwargs) -> Incomplete: ...
    def off(self, *args, **kwargs) -> Incomplete: ...
    def port(self, *args, **kwargs) -> Incomplete: ...
    def pin(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def af_list(self, *args, **kwargs) -> Incomplete: ...
    def af(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def high(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    @classmethod
    def dict(cls, *args, **kwargs) -> Incomplete: ...

    class cpu:
        P37: Pin  ## = Pin(37, mode=IN, pull=PULL_DISABLED)
        P9: Pin  ## = Pin(9, mode=IN, pull=PULL_DISABLED)
        P36: Pin  ## = Pin(36, mode=IN, pull=PULL_DISABLED)
        P4: Pin  ## = Pin(4, mode=IN, pull=PULL_DISABLED)
        P38: Pin  ## = Pin(38, mode=IN, pull=PULL_DISABLED)
        P39: Pin  ## = Pin(39, mode=IN, pull=PULL_DISABLED)
        P31: Pin  ## = Pin(31, mode=IN, pull=PULL_DISABLED)
        P35: Pin  ## = Pin(35, mode=IN, pull=PULL_DISABLED)
        P30: Pin  ## = Pin(30, mode=OUT, pull=PULL_DISABLED)
        P34: Pin  ## = Pin(34, mode=IN, pull=PULL_DISABLED)
        P32: Pin  ## = Pin(32, mode=IN, pull=PULL_DISABLED)
        P33: Pin  ## = Pin(33, mode=IN, pull=PULL_DISABLED)
        P5: Pin  ## = Pin(5, mode=IN, pull=PULL_DISABLED)
        P40: Pin  ## = Pin(40, mode=OUT, pull=PULL_DISABLED)
        P47: Pin  ## = Pin(47, mode=IN, pull=PULL_DISABLED)
        P8: Pin  ## = Pin(8, mode=IN, pull=PULL_DISABLED)
        P6: Pin  ## = Pin(6, mode=OUT, pull=PULL_DISABLED)
        P7: Pin  ## = Pin(7, mode=IN, pull=PULL_DISABLED)
        P42: Pin  ## = Pin(42, mode=IN, pull=PULL_DISABLED)
        P46: Pin  ## = Pin(46, mode=IN, pull=PULL_DISABLED)
        P41: Pin  ## = Pin(41, mode=IN, pull=PULL_DISABLED)
        P45: Pin  ## = Pin(45, mode=IN, pull=PULL_DISABLED)
        P43: Pin  ## = Pin(43, mode=IN, pull=PULL_DISABLED)
        P44: Pin  ## = Pin(44, mode=IN, pull=PULL_DISABLED)
        P15: Pin  ## = Pin(15, mode=IN, pull=PULL_DISABLED)
        P3: Pin  ## = Pin(3, mode=IN, pull=PULL_DISABLED)
        P14: Pin  ## = Pin(14, mode=IN, pull=PULL_DISABLED)
        P18: Pin  ## = Pin(18, mode=IN, pull=PULL_DISABLED)
        P16: Pin  ## = Pin(16, mode=IN, pull=PULL_DISABLED)
        P17: Pin  ## = Pin(17, mode=OUT, pull=PULL_DISABLED)
        P1: Pin  ## = Pin(1, mode=IN, pull=PULL_DISABLED)
        P13: Pin  ## = Pin(13, mode=IN, pull=PULL_DISABLED)
        P0: Pin  ## = Pin(0, mode=IN, pull=PULL_DISABLED)
        P12: Pin  ## = Pin(12, mode=IN, pull=PULL_DISABLED)
        P10: Pin  ## = Pin(10, mode=IN, pull=PULL_DISABLED)
        P11: Pin  ## = Pin(11, mode=IN, pull=PULL_DISABLED)
        P26: Pin  ## = Pin(26, mode=OUT, pull=PULL_DISABLED)
        P19: Pin  ## = Pin(19, mode=IN, pull=PULL_DISABLED)
        P25: Pin  ## = Pin(25, mode=IN, pull=PULL_DISABLED)
        P29: Pin  ## = Pin(29, mode=IN, pull=PULL_DISABLED)
        P27: Pin  ## = Pin(27, mode=IN, pull=PULL_DISABLED)
        P28: Pin  ## = Pin(28, mode=IN, pull=PULL_DISABLED)
        P20: Pin  ## = Pin(20, mode=IN, pull=PULL_DISABLED)
        P24: Pin  ## = Pin(24, mode=IN, pull=PULL_DISABLED)
        P2: Pin  ## = Pin(2, mode=IN, pull=PULL_DISABLED)
        P23: Pin  ## = Pin(23, mode=IN, pull=PULL_DISABLED)
        P21: Pin  ## = Pin(21, mode=IN, pull=PULL_DISABLED)
        P22: Pin  ## = Pin(22, mode=IN, pull=PULL_DISABLED)
        def __init__(self, *argv, **kwargs) -> None: ...

    @classmethod
    def mapper(cls, *args, **kwargs) -> Incomplete: ...

    class board:
        P42: Pin  ## = Pin(42, mode=IN, pull=PULL_DISABLED)
        UART1_TX: Pin  ## = Pin(43, mode=IN, pull=PULL_DISABLED)
        P41: Pin  ## = Pin(41, mode=IN, pull=PULL_DISABLED)
        PDM_CLK: Pin  ## = Pin(32, mode=IN, pull=PULL_DISABLED)
        P6: Pin  ## = Pin(6, mode=OUT, pull=PULL_DISABLED)
        P8: Pin  ## = Pin(8, mode=IN, pull=PULL_DISABLED)
        P35: Pin  ## = Pin(35, mode=IN, pull=PULL_DISABLED)
        P39: Pin  ## = Pin(39, mode=IN, pull=PULL_DISABLED)
        P34: Pin  ## = Pin(34, mode=IN, pull=PULL_DISABLED)
        P38: Pin  ## = Pin(38, mode=IN, pull=PULL_DISABLED)
        P36: Pin  ## = Pin(36, mode=IN, pull=PULL_DISABLED)
        P37: Pin  ## = Pin(37, mode=IN, pull=PULL_DISABLED)
        SPI0_MISO: Pin  ## = Pin(46, mode=IN, pull=PULL_DISABLED)
        PDM_DATA: Pin  ## = Pin(16, mode=IN, pull=PULL_DISABLED)
        READ_BAT: Pin  ## = Pin(14, mode=IN, pull=PULL_DISABLED)
        UART1_RX: Pin  ## = Pin(44, mode=IN, pull=PULL_DISABLED)
        SPI0_MOSI: Pin  ## = Pin(47, mode=IN, pull=PULL_DISABLED)
        SPI0_SCK: Pin  ## = Pin(45, mode=IN, pull=PULL_DISABLED)
        QSPI_D0: Pin  ## = Pin(20, mode=IN, pull=PULL_DISABLED)
        QSPI_SCK: Pin  ## = Pin(21, mode=IN, pull=PULL_DISABLED)
        QSPI_CS: Pin  ## = Pin(25, mode=IN, pull=PULL_DISABLED)
        QSPI_D3: Pin  ## = Pin(23, mode=IN, pull=PULL_DISABLED)
        QSPI_D1: Pin  ## = Pin(24, mode=IN, pull=PULL_DISABLED)
        QSPI_D2: Pin  ## = Pin(22, mode=IN, pull=PULL_DISABLED)
        IMU_INT1: Pin  ## = Pin(11, mode=IN, pull=PULL_DISABLED)
        P33: Pin  ## = Pin(33, mode=IN, pull=PULL_DISABLED)
        D5_A5: Pin  ## = Pin(5, mode=IN, pull=PULL_DISABLED)
        IMU_SDA: Pin  ## = Pin(7, mode=IN, pull=PULL_DISABLED)
        IMU_PWR: Pin  ## = Pin(40, mode=OUT, pull=PULL_DISABLED)
        IMU_SCL: Pin  ## = Pin(27, mode=IN, pull=PULL_DISABLED)
        D0_A0: Pin  ## = Pin(2, mode=IN, pull=PULL_DISABLED)
        D4_A4: Pin  ## = Pin(4, mode=IN, pull=PULL_DISABLED)
        ADC0_BAT: Pin  ## = Pin(31, mode=IN, pull=PULL_DISABLED)
        D3_A3: Pin  ## = Pin(29, mode=IN, pull=PULL_DISABLED)
        D1_A1: Pin  ## = Pin(3, mode=IN, pull=PULL_DISABLED)
        D2_A2: Pin  ## = Pin(28, mode=IN, pull=PULL_DISABLED)
        P18: Pin  ## = Pin(18, mode=IN, pull=PULL_DISABLED)
        NFC1: Pin  ## = Pin(9, mode=IN, pull=PULL_DISABLED)
        P17: Pin  ## = Pin(17, mode=OUT, pull=PULL_DISABLED)
        P30: Pin  ## = Pin(30, mode=OUT, pull=PULL_DISABLED)
        P19: Pin  ## = Pin(19, mode=IN, pull=PULL_DISABLED)
        P26: Pin  ## = Pin(26, mode=OUT, pull=PULL_DISABLED)
        P0: Pin  ## = Pin(0, mode=IN, pull=PULL_DISABLED)
        P15: Pin  ## = Pin(15, mode=IN, pull=PULL_DISABLED)
        NFC2: Pin  ## = Pin(10, mode=IN, pull=PULL_DISABLED)
        P13: Pin  ## = Pin(13, mode=IN, pull=PULL_DISABLED)
        P1: Pin  ## = Pin(1, mode=IN, pull=PULL_DISABLED)
        P12: Pin  ## = Pin(12, mode=IN, pull=PULL_DISABLED)
        def __init__(self, *argv, **kwargs) -> None: ...

    def __init__(self, *argv, **kwargs) -> None: ...

mem8: Incomplete  ## <class 'mem'> = <8-bit memory>

class UART:
    IRQ_RX: Final[int] = 2
    IRQ_TXIDLE: Final[int] = 1
    def writechar(self, *args, **kwargs) -> Incomplete: ...
    def flush(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def txdone(self, *args, **kwargs) -> Incomplete: ...
    def readchar(self, *args, **kwargs) -> Incomplete: ...
    def irq(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def any(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def readline(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ADC:
    def battery_level(self, *args, **kwargs) -> Incomplete: ...
    def read_u16(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class PWM:
    def duty_u16(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def freq(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def duty_ns(self, *args, **kwargs) -> Incomplete: ...
    def duty(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class I2C:
    def readfrom_mem(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_mem_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_into(self, *args, **kwargs) -> Incomplete: ...
    def writevto(self, *args, **kwargs) -> Incomplete: ...
    def writeto_mem(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def writeto(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def readfrom(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Temp:
    def read(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SoftI2C:
    def readfrom_mem(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_mem_into(self, *args, **kwargs) -> Incomplete: ...
    def readfrom_into(self, *args, **kwargs) -> Incomplete: ...
    def writevto(self, *args, **kwargs) -> Incomplete: ...
    def writeto_mem(self, *args, **kwargs) -> Incomplete: ...
    def scan(self, *args, **kwargs) -> Incomplete: ...
    def writeto(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def readfrom(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Timer:
    PERIODIC: Final[int] = 1
    ONESHOT: Final[int] = 0
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def period(self, *args, **kwargs) -> Incomplete: ...
    def time(self, *args, **kwargs) -> Incomplete: ...
    def stop(self, *args, **kwargs) -> Incomplete: ...
    def start(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

mem32: Incomplete  ## <class 'mem'> = <32-bit memory>
mem16: Incomplete  ## <class 'mem'> = <16-bit memory>

class Signal:
    def off(self, *args, **kwargs) -> Incomplete: ...
    def on(self, *args, **kwargs) -> Incomplete: ...
    def value(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SPI:
    LSB: Final[int] = 1
    MSB: Final[int] = 0
    def deinit(self, *args, **kwargs) -> Incomplete: ...
    def init(self, *args, **kwargs) -> Incomplete: ...
    def write_readinto(self, *args, **kwargs) -> Incomplete: ...
    def read(self, *args, **kwargs) -> Incomplete: ...
    def write(self, *args, **kwargs) -> Incomplete: ...
    def readinto(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
