# This will attempt to retrieve and add/update the hand coded stubs from cpwood/Pico-Stub

name: Get pico-go stubs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 5"   # Run every Friday at 01:00

jobs:
  # job prepare sets everything up
  get-stubs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true

    # Most scripts will be run from the stubs repo, set that as default
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/micropython-stubs
  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      ######################################
      # Check out repos side-by-side:
      # josverl/micropython-stubs
      # cpwood/Pico-Stub
      ######################################

      - name: Checkout stubs repo
        uses: actions/checkout@v2
        with:
          repository: josverl/micropython-stubs
          path: micropython-stubs

      - name: Checkout stubber repo
        uses: actions/checkout@v2
        with:
          repository: josverl/micropython-stubber
          path: micropython-stubber

      # simplify processing using symlink
      - name: create symlink for all_stubs
        working-directory: ${{github.workspace}}/micropython-stubber
        run: |
          ln -s ${{github.workspace}}/micropython-stubs/stubs all-stubs --force


      # integrate stubs from this repo
      - name: Checkout Pico-Stub repo
        uses: actions/checkout@v2
        with:
          repository: cpwood/Pico-Stub
          path: Pico-Stub

      # make Python work
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      ######################################
      # This is where the actual work starts
      ######################################

      - name: add/update Pico-Stub/dist/pylance/*.*
        working-directory: ${{github.workspace}}
        shell: pwsh
        run: |
          copy-item ./Pico-Stub/dist/pylance/*.* ./micropython-stubs/stubs/micropython-pico-go -Recurse -Force
          copy-item ./Pico-Stub/LICENSE ./micropython-stubs/stubs/micropython-pico-go/LICENSE

      # Todo: add manifest.json

      # - name: Update stubs with .pyi ${{ matrix.version }}
      #   run: |
      #     python ./src/update_pyi.py

      # - name: Update Documentation
      #  working-directory: ${{github.workspace}}/micropython-stubber
      #  shell: pwsh
      #  run: |
      #    scripts/update_docs.ps1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        # ref: https://github.com/peter-evans/create-pull-request
        with:
          path: micropython-stubs
          title: '${{ steps.extract_branch.outputs.branch }} : add/update Pico-Stub modules'
          commit-message: add/update Pico-Stub modules
          branch: pico-stub-updates
          reviewers: josverl          
          labels: |
            automated pr
            micropython
            Pico-Stub
          delete-branch: true

      # - name: exit gracefully
      #   run: |
      #     echo 'avoid throwing a fit when an existing PR was updated'
      #   if: ${{steps.cpr.exit == 1 }}
      #   # if: ${{ failure() }}

