name: test stub quality
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main]
  #   paths-ignore:
  #     - '**.md'
  #     - 'docs/**'

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stubs repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: josverl
          # domain: ${{github.repository_owner}}

      # dummy pytest
      - name: run pytest
        run: |
          pytest ./tests --junitxml=./results/results.xml

      - name: run pyright on stubs
        if: always()
        run: |
          pyright stubs | tee ./results/pyright-all-stubs.log

      - name: Fixup pyright logs 
        shell: pwsh
        run: |
          ./tests/fix-pyrightlogs.ps1

      - uses: actions/upload-artifact@v2
        with:
          name: pyright
          path: ./results/pyright-all-stubs.log

      - name: Testspace push test content
        run: testspace "[all-stubs]./results/pyright-all-stubs.log{lint}" ./results/results.xml
