"""
Module: 'random' on micropython-v1.25.0-rp2-RPI_PICO2_W
"""

# MCU: {'build': '', 'ver': '1.25.0', 'version': '1.25.0', 'port': 'rp2', 'board': 'RPI_PICO2_W', 'mpy': 'v6.3', 'family': 'micropython', 'cpu': 'RP2350', 'arch': 'armv7emsp'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def randrange(*args, **kwargs) -> Incomplete: ...
def random(*args, **kwargs) -> Incomplete: ...
def seed(*args, **kwargs) -> Incomplete: ...
def uniform(*args, **kwargs) -> Incomplete: ...
def choice(*args, **kwargs) -> Incomplete: ...
def randint(*args, **kwargs) -> Incomplete: ...
def getrandbits(*args, **kwargs) -> Incomplete: ...
