
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def get_lcd(lcd: Any) -> Any: ...
    #   0: return lcd
    # ? 0: return lcd
def show_adc(lcd: Any, adc: Any) -> None: ...
def test_features(lcd: Any, orient: Any=lcd160cr.PORTRAIT) -> None: ...
def test_mandel(lcd: Any, orient: Any=lcd160cr.PORTRAIT) -> Optional[int]:
    def in_set(c: Any) -> Optional[int]: ...
def test_all(lcd: Any, orient: Any=lcd160cr.PORTRAIT) -> None: ...
