from uasyncio.core import *
from _typeshed import Incomplete
from collections.abc import Generator

DEBUG: int
log: Incomplete

def set_debug(val) -> None: ...

class PollEventLoop(EventLoop):
    poller: Incomplete
    objmap: Incomplete
    def __init__(self, runq_len: int = ..., waitq_len: int = ...) -> None: ...
    def add_reader(self, sock, cb, *args) -> None: ...
    def remove_reader(self, sock) -> None: ...
    def add_writer(self, sock, cb, *args) -> None: ...
    def remove_writer(self, sock) -> None: ...
    def wait(self, delay) -> None: ...

class StreamReader:
    polls: Incomplete
    ios: Incomplete
    def __init__(self, polls, ios: Incomplete | None = ...) -> None: ...
    def read(self, n: int = ...) -> Generator[Incomplete, None, Incomplete]: ...
    def readexactly(self, n) -> Generator[Incomplete, None, Incomplete]: ...
    def readline(self) -> Generator[Incomplete, None, Incomplete]: ...
    def aclose(self) -> Generator[Incomplete, None, None]: ...
    def __repr__(self): ...

class StreamWriter:
    s: Incomplete
    extra: Incomplete
    def __init__(self, s, extra) -> None: ...
    def awrite(self, buf, off: int = ..., sz: int = ...) -> Generator[Incomplete, None, None]: ...
    def awriteiter(self, iterable) -> None: ...
    def aclose(self) -> Generator[Incomplete, None, None]: ...
    def get_extra_info(self, name, default: Incomplete | None = ...): ...
    def __repr__(self): ...

def open_connection(host, port, ssl: bool = ...) -> Generator[Incomplete, None, Incomplete]: ...
def start_server(client_coro, host, port, backlog: int = ...) -> Generator[Incomplete, None, None]: ...
