"""
Module: 'ure' on micropython-v1.24.0-preview-rp2-RPI_PICO
"""

# MCU: {'build': 'preview.63.gcfa55b4ca', 'ver': '1.24.0-preview-preview.63.gcfa55b4ca', 'version': '1.24.0-preview', 'port': 'rp2', 'board': 'RPI_PICO', 'mpy': 'v6.3', 'family': 'micropython', 'cpu': 'RP2040', 'arch': 'armv6m'}
# Stubber: v1.20.0
from __future__ import annotations
from _typeshed import Incomplete

def sub(*args, **kwargs) -> Incomplete: ...
def search(*args, **kwargs) -> Incomplete: ...
def match(*args, **kwargs) -> Incomplete: ...
def compile(*args, **kwargs) -> Incomplete: ...
