from typing import Any

class CancelledError: ...

DEBUG: int

class EventLoop:
    def call_at_() -> None: ...
    def call_later() -> None: ...
    def call_later_ms() -> None: ...
    def call_soon() -> None: ...
    def close() -> None: ...
    def create_task() -> None: ...
    def run_forever() -> None: ...
    def run_until_complete() -> None: ...
    def stop() -> None: ...
    def time() -> None: ...
    def wait() -> None: ...

class IORead:
    def handle() -> None: ...

class IOReadDone:
    def handle() -> None: ...

class IOWrite:
    def handle() -> None: ...

class IOWriteDone:
    def handle() -> None: ...

class PollEventLoop:
    def add_reader() -> None: ...
    def add_writer() -> None: ...
    def call_at_() -> None: ...
    def call_later() -> None: ...
    def call_later_ms() -> None: ...
    def call_soon() -> None: ...
    def close() -> None: ...
    def create_task() -> None: ...
    def remove_reader() -> None: ...
    def remove_writer() -> None: ...
    def run_forever() -> None: ...
    def run_until_complete() -> None: ...
    def stop() -> None: ...
    def time() -> None: ...
    def wait() -> None: ...

class SleepMs:
    def handle() -> None: ...

class StopLoop:
    def handle() -> None: ...

class StreamReader:
    aclose: Any
    read: Any
    readexactly: Any
    readline: Any

class StreamWriter:
    aclose: Any
    awrite: Any
    awriteiter: Any
    def get_extra_info() -> None: ...

class SysCall:
    def handle() -> None: ...

class SysCall1:
    def handle() -> None: ...

def Task() -> None: ...

class TimeoutError: ...
class TimeoutObj: ...

_socket: Any

def cancel() -> None: ...

core: Any

def coroutine() -> None: ...
def ensure_future() -> None: ...
def get_event_loop() -> None: ...

log: Any
open_connection: Any
select: Any

def set_debug() -> None: ...

sleep: Any
sleep_ms: Any
start_server: Any
time: Any

class type_gen:
    def close() -> None: ...
    def pend_throw() -> None: ...
    def send() -> None: ...
    def throw() -> None: ...

uasyncio: Any
ucollections: Any
uerrno: Any
utimeq: Any

def wait_for() -> None: ...

wait_for_ms: Any
