"""
Module: 'aioespnow' on micropython-v1.22.0-esp32-ESP32_GENERIC
"""

# MCU: {'family': 'micropython', 'version': '1.22.0', 'build': '', 'ver': 'v1.22.0', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'cpu': 'ESP32', 'mpy': 'v6.2', 'arch': 'xtensawin'}
# Stubber: v1.16.2
from _typeshed import Incomplete


class AIOESPNow:
    def peer_count(self, *args, **kwargs) -> Incomplete: ...

    def recv(self, *args, **kwargs) -> Incomplete: ...

    def mod_peer(self, *args, **kwargs) -> Incomplete: ...

    def get_peers(self, *args, **kwargs) -> Incomplete: ...

    def stats(self, *args, **kwargs) -> Incomplete: ...

    def recvinto(self, *args, **kwargs) -> Incomplete: ...

    def set_pmk(self, *args, **kwargs) -> Incomplete: ...

    def irecv(self, *args, **kwargs) -> Incomplete: ...

    def get_peer(self, *args, **kwargs) -> Incomplete: ...

    def active(self, *args, **kwargs) -> Incomplete: ...

    def send(self, *args, **kwargs) -> Incomplete: ...

    def any(self, *args, **kwargs) -> Incomplete: ...

    def del_peer(self, *args, **kwargs) -> Incomplete: ...

    def add_peer(self, *args, **kwargs) -> Incomplete: ...

    def config(self, *args, **kwargs) -> Incomplete: ...

    def irq(self, *args, **kwargs) -> Incomplete: ...

    asend: Incomplete  ## <class 'generator'> = <generator>
    arecv: Incomplete  ## <class 'generator'> = <generator>
    airecv: Incomplete  ## <class 'generator'> = <generator>

    def __init__(self, *argv, **kwargs) -> None: ...
