"""
Module: 'dht' on micropython-v1.22.0-esp32-ESP32_GENERIC
"""

# MCU: {'family': 'micropython', 'version': '1.22.0', 'build': '', 'ver': 'v1.22.0', 'port': 'esp32', 'board': 'ESP32_GENERIC', 'cpu': 'ESP32', 'mpy': 'v6.2', 'arch': 'xtensawin'}
# Stubber: v1.16.2
from _typeshed import Incomplete


def dht_readinto(*args, **kwargs) -> Incomplete: ...


class DHTBase:
    def measure(self, *args, **kwargs) -> Incomplete: ...

    def __init__(self, *argv, **kwargs) -> None: ...


class DHT22:
    def measure(self, *args, **kwargs) -> Incomplete: ...

    def temperature(self, *args, **kwargs) -> Incomplete: ...

    def humidity(self, *args, **kwargs) -> Incomplete: ...

    def __init__(self, *argv, **kwargs) -> None: ...


class DHT11:
    def measure(self, *args, **kwargs) -> Incomplete: ...

    def temperature(self, *args, **kwargs) -> Incomplete: ...

    def humidity(self, *args, **kwargs) -> Incomplete: ...

    def __init__(self, *argv, **kwargs) -> None: ...
