from typing import Any

class DHTBase:
    pin: Any
    buf: Any
    def __init__(self, pin) -> None: ...
    def measure(self) -> None: ...

class DHT11(DHTBase):
    def humidity(self) -> None: ...
    def temperature(self) -> None: ...

class DHT22(DHTBase):
    def humidity(self) -> None: ...
    def temperature(self) -> None: ...
