from typing import Any

TAR_HEADER: Any
DIRTYPE: str
REGTYPE: str

def roundup(val, align) -> None: ...

class FileSection:
    f: Any
    content_len: Any
    align: Any
    def __init__(self, f, content_len, aligned_len) -> None: ...
    def read(self, sz: int = ...): ...
    def readinto(self, buf) -> None: ...
    def skip(self) -> None: ...

class TarInfo:
    def __str__(self) -> None: ...

class TarFile:
    f: Any
    subf: Any
    def __init__(self, name: Union[Any, None] = ..., fileobj: Union[Any, None] = ...) -> None: ...
    def next(self) -> None: ...
    def __iter__(self): ...
    def __next__(self) -> None: ...
    def extractfile(self, tarinfo) -> None: ...
