from typing import Any

debug: bool
index_urls: Any
install_path: Any
cleanup_files: Any
gzdict_sz: Any
file_buf: Any

class NotFoundError(Exception): ...

def op_split(path) -> None: ...
def _makedirs(name, mode: int = ...): ...
def save_file(fname, subf) -> None: ...
def install_tar(f, prefix) -> None: ...
def expandhome(s) -> None: ...

warn_ussl: bool

def url_open(url) -> None: ...
def get_pkg_metadata(name) -> None: ...
def fatal(msg, exc: Union[Any, None] = ...) -> None: ...
def install_pkg(pkg_spec, install_path) -> None: ...
def install(to_install, install_path: Union[Any, None] = ...) -> None: ...
def get_install_path() -> None: ...
def cleanup() -> None: ...
def help() -> None: ...
def main() -> None: ...
