from typing import Any

class Response:
    raw: Any
    encoding: str
    _cached: Any
    def __init__(self, f) -> None: ...
    def close(self) -> None: ...
    @property
    def content(self) -> None: ...
    @property
    def text(self) -> None: ...
    def json(self) -> None: ...

def request(
    method,
    url,
    data: Union[Any, None] = ...,
    json: Union[Any, None] = ...,
    headers=...,
    stream: Union[Any, None] = ...,
    auth: Union[Any, None] = ...,
    timeout: Union[Any, None] = ...,
    parse_headers: bool = ...,
): ...
def head(url, **kw) -> None: ...
def get(url, **kw) -> None: ...
def post(url, **kw) -> None: ...
def put(url, **kw) -> None: ...
def patch(url, **kw) -> None: ...
def delete(url, **kw) -> None: ...
