from typing import Any

listen_s: Any
client_s: Any
DEBUG: int
_DEFAULT_STATIC_HOST: Any
static_host = _DEFAULT_STATIC_HOST

def server_handshake(cl) -> None: ...
def send_html(cl) -> None: ...
def setup_conn(port, accept_handler) -> None: ...
def accept_conn(listen_sock) -> None: ...
def stop() -> None: ...
def start(port: int = ..., password: Union[Any, None] = ..., accept_handler=...) -> None: ...
def start_foreground(port: int = ..., password: Union[Any, None] = ...) -> None: ...
