from typing import Any

def const(*args) -> Any: ...
def alloc_emergency_exception_buf(*args) -> Any: ...
def heap_lock(*args) -> Any: ...
def heap_unlock(*args) -> Any: ...
def kbd_intr(*args) -> Any: ...
def mem_info(*args) -> Any: ...
def opt_level(*args) -> Any: ...
def qstr_info(*args) -> Any: ...
def schedule(*args) -> Any: ...
def stack_use(*args) -> Any: ...
